### ISSUE TITLE
Washing machine display is always on.

### ISSUE THREAD

**Issue by labaland** [ekutner/home-connect-hass#101]
Hej! Min engelska är crap så skriver på svenska. Då jag tror du är svensk :D

Displayen på min tvättmaskin (WAU28PEHSN) är i stort sett alltid på sen jag installerade denna integration. Den går i viloläge och sen efter en stund så vaknar den igen, displayen börjar lysa och maskinen tickar igång. Har ej det problemet med min diskmaskin(SMU6ZCS01S).

Du råkar inte veta varför eller om jag kan ändra något?
Tack för en bra integration! :) 

-----

The display on my washing machine (WAU28PEHSN) is pretty much always on since I installed this integration. It goes to sleep and then after a while it wakes up again. I don't have that problem with my dishwasher (SMU6ZCS01S).

You don't happen to know why or if I can change anything?

**Comment by ekutner** [comment]
I have no idea. The integration is not talking directly to the appliance. It talks to the Home Connect servers through their API, so I don't see how it can be affecting this.
