### ISSUE TITLE
Add FAQ about Home Connect User Account for Testing

### ISSUE THREAD

**Issue by Zerwin** [ekutner/home-connect-hass#103]
**Is your feature request related to a problem? Please describe.**
Home Connect recently implemented Singlekey ID, and made it a requirement if you register for a new non develop account for Home Connect. One problem that seems to exist is that if the Singlekey ID account was registered with an email that has an upper case letter, the Home Connect API will return a 400 Bad Response on the last step of adding the integration in Home Assistant (The frontend just shows a popup saying Error with no explanation). 

**Describe the solution you'd like**
Adding a bullet point in the FAQ advising ppl to only use lower case emails for their non developer accounts could save ppl a lot of time debugging.

**Comment by ekutner** [comment]
That's an interesting issue. Since I didn't experience it first hand I think it would be best if you can provide the exact wording for the FAQ and I'll add it or just create a PR, if you know how to do that.

**Comment by Zerwin** [comment]
I created a PR https://github.com/ekutner/home-connect-hass/pull/104 for it.

**Comment by ekutner** [comment]
Thank you. Merged.
