### ISSUE TITLE
Showing the correct state of dishwasher

### ISSUE THREAD

**Issue by EvertJob** [ekutner/home-connect-hass#105]
**Is your feature request related to a problem? Please describe.**
Current the state of `Siemens Dishwasher - Operation State` is `BSH.Common.EnumType.OperationState.Inactive` it would be nicer (and easier to make some automations) if the state could be "Inactive" and "Running" or "Active"

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
Using the state as provided but that would be a lot harder to share, edit and remember

<img width="1369" alt="Screenshot 2022-09-05 at 14 01 08" src="https://user-images.githubusercontent.com/58138839/188444241-393c2dc1-c086-4b5d-9900-19716088981a.png">

**Comment by ekutner** [comment]
This is based on translation files. What is you configuration and what language do you have configured in HA?

**Comment by EvertJob** [comment]
```
home_connect_alt:
  client_id: 2EA4F1E7FC32DEAB42CB7FDE715A03DAD1D55BEC61CECADC6FA0EC9182DAF9EB
  client_secret: F4DE8B220A9725B189D5355D342699016FD05F40A86E27455EAF145791668E9B```

Language is set to English

**Comment by ekutner** [comment]
1. Just to be clear, are you seeing these values in the current sensors state or only in history? If in history then this is a known HA bug that doesn't translate history value. If in current sensor values, please provide a screenshot.
2. It's never a good idea sharing private/secret keys in public. I strongly recommend you reset your keys (to be honest I'm not even sure if that is possible), or just create a new app and use a different set of keys.

**Comment by ekutner** [comment]
And just to address your point about automation. The integration is intentionally using the same ENUM values used by the API for two reasons: 1) it allows using the HC documentation for reference; 2) The values are consistent across different languages which allows for sharing of automation scripts.
