### ISSUE TITLE
CottonEco not supported?

### ISSUE THREAD

**Issue by rr19-hub** [ekutner/home-connect-hass#107]
The Bosch washing machine wayh2840 can be controlled so far well with this integration, thank you very much. However, we always use _CottonEco_ and unfortunately _CottonEco_ can neither be selected nor started.

- Switch the maschine manually to _CottonEco_ => `sensor.bosch_wayh2840_xxx_active_program` correctly contains `LaundryCare.Washer.Program.Cotton.CottonEco`
- But in the dashboard `xx_laundrycare_washer_option_spinspeed`, `xx_laundrycare_washer_option_temperature` and `xx_programs` are greyed out.
- Activate RemoteStart on the machine
- The start button (`xx_start_pause`) becomes active, but an error message appears when pressed.

If you add _CottonEco_ or _Cotton_Eco_ to `select.bosch_wayh2840_xxx_programs` in addition to _Cotton_, an error appears when selecting:

Can the Eco programme be activated somehow or is this not possible via the API? What is annoying is that the machine cannot be started remotely once the Eco programme has been switched on. On [https://github.com/DavidMStraub/homeassistant-homeconnect/issues/131](https://github.com/DavidMStraub/homeassistant-homeconnect/issues/131) an `Eco4060` is mentioned, are the programmes perhaps called something else?

**Comment by ekutner** [comment]
It is indeed not supported by the API. There are quite a lot of options/programs that the mobile app can access but are not accessible through the API.
