### ISSUE TITLE
LOADING_FAILED after RUNNING

### ISSUE THREAD

**Issue by joshfranklin918760** [ekutner/home-connect-hass#108]
## Describe the bug
In the Device info screen for Home Connect Service, Home Connect Status changes from RUNNING to LOADING_FAILED after a few minutes. I don't see the error in the FAQ as a potential error, so I'm not sure where to go from here.

## Version of the custom_component
latest on HACS

## Configuration

home_connect_alt:
  client_id: "REDACTED"
  client_secret: "REDACTED"
logger:
  default: warn
  logs:
    home_connect_async: debug
    home_connect_alt: debug
    custom_components.home_connect_alt: debug

## Debug log

```text
Log Details (WARNING)


Logger: home_connect_async.homeconnect
Source: /usr/local/lib/python3.10/site-packages/home_connect_async/homeconnect.py:176 
First occurred: 7:51:39 PM (3 occurrences) 
Last logged: 8:25:43 PM

Failed to load data from Home Connect (('Failed to get a valid response from Home Connect server', 902, None, None, None))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/homeconnect.py", line 139, in async_load_data
    response = await self._api.async_get('/api/homeappliances')
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 118, in async_get
    return await self._async_request('GET', endpoint)
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 113, in _async_request
    raise HomeConnectError("Failed to get a valid response from Home Connect server", 902)
home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)
```

**Comment by ekutner** [comment]
This looks like a network problem. If it is still happening then please attach the complete log file.

**Comment by EvertJob** [comment]
I'm having the same issue. @joshfranklin918760 did it start working at your install?

**Comment by joshfranklin918760** [comment]
> I'm having the same issue. @joshfranklin918760 did it start working at your install?

I created another dev account at home connect and I changed over the yaml client ID and restarted HASS. Then I removed\re-added the integration and it started working again, but it stops a day or so later and I have to switch it again to another account.

**Comment by ekutner** [comment]
This usually happens when the API rate limit is hit. The full debug log would confirm that (although the expected error then would be 429 and not 902).

**Comment by joshfranklin918760** [comment]
I think I got the culprit. I had a dashboard item reporting the status of a HomeConnect entity. Since I've removed it, I haven't been hitting the limit.

**Comment by ekutner** [comment]
No, it can't be that, that sensor reflects the internal state of the integration, it doesn't make any API calls so can't contribute to the limit.

**Comment by joshfranklin918760** [comment]
Thanks! It looks to be stable now, so if I see that again, I'll upload the debug log.

FYI, I enabled the logger, and pressed the debug button in home connect but didn't get any log output.

**Comment by joshfranklin918760** [comment]
I added this to my config per the docs.

logger:
  default: warn
  logs:
    home_connect_async: debug
    home_connect_alt: debug
    custom_components.home_connect_alt: debug

**Comment by ekutner** [comment]
assuming you have the right indentation, which was lost here, then it looks correct. You should see log information in the homeassistant.log file.
FYI, you can use the "add code" button in the comment toolbar to preserve the indentation.

**Comment by joshfranklin918760** [comment]
Yep, indentation is correct. I copied and pasted direct from your githiub page and that preserved the indentation on the config.

I'll keep an eye out on this and update here with the logs. 

Appreciate the help and the amazing add on! I was using the HomeBridge add on previously and this is much better and more tightly integrated into HA. Really appreciate the work!
