### ISSUE TITLE
Mismatch between selectable programs and actual programs on laundry machine

### ISSUE THREAD

**Issue by meros** [ekutner/home-connect-hass#112]
## Describe the bug
The machine has a quick program that cannot be started remotely, the reason being it is not selectable in the drop down, even though it's reflected in the state when manually selected. Press start doesn't work as well.

## Version of the custom_component

0.5.7

## Screenshots:
Selecting the Auto program works as expected
<img width="330" alt="Screenshot 2022-09-14 at 18 13 29" src="https://user-images.githubusercontent.com/450310/190208529-95115341-4b21-4d23-875b-33df5c951bbf.png">

The quick program is only reflected in the read only state. Cannnot remote start when this happens
<img width="322" alt="Screenshot 2022-09-14 at 18 13 09" src="https://user-images.githubusercontent.com/450310/190208532-4e54befe-6e55-4a65-a3ab-044939db38cf.png">

**Comment by ekutner** [comment]
There are a lot of programs/options that can't be set by the API. That's a limitation of the Home Connect API, not of the integration.
