### ISSUE TITLE
showing additional notification

### ISSUE THREAD

**Issue by bkbartk** [ekutner/home-connect-hass#115]
**Describe the solution you'd like**
The Official Home Connect app gives messages like device cleaning solutions. and errors.
I would like to have those message also available in HA.
I don't know if the API supports this or not but it would be a nice addition

**Describe alternatives you've considered**
Using the Home Connect App

**Comment by ekutner** [comment]
That would be nice but unfortunately both of these requests are not supported by the public HC API.
Feel free to submit a request to HC to expose this information in the API and I'll be happy to add support for it.

**Comment by bkbartk** [comment]
> Hello Bart.
 
I’ve added your request to our internal API wishlist, unfortunately I’m not able to tell you if or when this could be added. I can guarantee that we’ll review your proposal though J
 
Best Regards,
Hubert
 
Your Home Connect Developer Team
https://developer.home-connect.com/

**Comment by cstosgale** [comment]
Hi, I was wondering if there's any update on this issue? I'd be interested in being able to get notifications like this as well!

**Comment by EnricoBettella** [comment]
I’m interested in this feature too.
HC API documentation [now lists all events](https://api-docs.home-connect.com/events/#home-appliance-state-changes), and for example “Salt nearly empty” event too.
Is there a chance that they could be ported to home assistant? I didn’t get if they’re on the public API, but since they’re documented I do think so.

**Comment by ekutner** [comment]
Home Connect events are already being exposed by the integration as Home Assistant events.

**Comment by EnricoBettella** [comment]
Oh… sorry🫠 I must have missed something. How can I listen for those HC events? They don’t seem to appear on the registry nor in the events tab under developer settings, but I think I’m on the wrong way now

**Comment by ekutner** [comment]
They do appear in the developers events tab
