### ISSUE TITLE
Siemens EQ.9 Connect sensors 'state_class'

### ISSUE THREAD

**Issue by ChristophCaina** [ekutner/home-connect-hass#118]
Hi, I already had an older Ticket open, where I complained about missing options (like statistics) from the HomeConnect app...
To be fair, it seems that I have installed the wrong (default) HomeConnect app - which does not provide these information...

Today, I have changed to the home-connect alt integration - and in fact, I do get several statistics from the device (not all, but much better than in the old setup ;) )

BUT:
I noticed, that some of the counters could be improved...
It would be great, if they could get a state_class attribute (total_increasing)... this would allow to generate further statistics (like amount cups of coffee per day / week... etc.)

for example:
`sensor.siemens_ti*******_*********45de_consumerproducts_coffeemaker_status_beveragecountercoffee`
```
state: 306
device_class: home_connect_alt__status
icon: mdi:gauge-full
friendly_name: Siemens Kaffeevollautomat - Anzahl Kaffeegetränke
```

furthermore - the device class given here - is at least no official device class from HomeAssistant... ;)

**Comment by ekutner** [comment]
The integration is completely generic, every appliance exposes different controls and metrics and the integration automatically exposes in Home Assistant everything that is made available by the API. The integration is using metadata exposed by the API to know the type of value but that information doesn't go as deep as what you are looking for so there is no way to do it other than manually mapping all the data fields, which is not something I plan to do.

**Comment by ChristophCaina** [comment]
hm... okey, thank you.

but still, one question might be allowed here :)

Checking the statistics information provided by the application - it seems:

sensor.siemens_ti9578x1de_68a40e8445de_consumerproducts_coffeemaker_status_beveragecounterhotwater
Counter Hot-Water seems to be a "numeric" value - statistic can be generated.
![grafik](https://user-images.githubusercontent.com/26391061/197419274-71f3d4c0-ed92-4479-a3f2-5df4bda9d8a0.png)

it does have a unit_of_measurement, which is "ml"...
```
unit_of_measurement: ml
device_class: home_connect_alt__status
icon: mdi:gauge-full
friendly_name: Siemens Kaffeevollautomat - Menge Heißwasser
```

for the other sensors - like
sensor.siemens_ti9578x1de_68a40e8445de_consumerproducts_coffeemaker_status_beveragecountercoffee
we do not have a unit_of_measurement (OK, HomeAssistant does not provide "cups" as a measurement, I guess ;)"
And this is why we can't see any type of statistic here, right?                                                                   
```
device_class: home_connect_alt__status
icon: mdi:gauge-full
friendly_name: Siemens Kaffeevollautomat - Anzahl Kaffeegetränke
```
![grafik](https://user-images.githubusercontent.com/26391061/197419343-a35dfb04-f9e5-46cb-9f2f-84c5b304ff77.png)

**Comment by ekutner** [comment]
When the units are provided by the API the integration uses it to set the HA entity units. If you don't see it then the API doesn't have it.

**Comment by ekutner** [comment]
What would you expect to see?

**Comment by d0np3p3** [comment]
unit_of_measurement: none
Should give us a graph line

**Comment by ekutner** [comment]
I've released 0.6.0-b1 that tries to handle this scenario while also allowing to explicitly set the units for entities in the configuration. 
Try it (you have to allow beta versions in HACS in order to see it) and let me know if it works for you.

**Comment by d0np3p3** [comment]
The Beta doesn't work for me, I can try it again with log later.

**Comment by ekutner** [comment]
Doesn't work how?

**Comment by d0np3p3** [comment]
Same issue, see https://github.com/ekutner/home-connect-hass/issues/159

**Comment by ekutner** [comment]
If you have the same issue then you didn't add the configuration for setting the units. Anyway, that is fixed now.

**Comment by d0np3p3** [comment]
Okay thank you very much,
I don't know how to add the config... (not yet)

**Comment by ekutner** [comment]
In the README

**Comment by ChristophCaina** [comment]
Hi,
I've noticed that change in the new beta (?) [don't know if it is still beta]...
And came across the following:

I do have a binary_sensor in my application - that does not have a specific Device_class...

```
binary_sensor.siemens_ti9578x1de_68a40e8445de_connected
```
![grafik](https://user-images.githubusercontent.com/26391061/218305334-23cac2d6-69b5-4b5d-9827-795b8b222a44.png)

I would consider, that this specific entitiy should be device_class = connectivity

Example:
![grafik](https://user-images.githubusercontent.com/26391061/218305413-0e0881fb-4cc6-4560-a28f-23a2e952d4e5.png)
![grafik](https://user-images.githubusercontent.com/26391061/218305416-84b733f2-7c2d-4cb2-bc7e-5ae30a3c930a.png)

This would also allow the usage of the new state color options provided by HomeAssistant, where you can define specific colors on device_class level.
Could this be added (at least) as optional configuration as shown in the readme for unit / icon?

**Comment by ekutner** [comment]
You can actually already do it in the configuration. Just add 
```
entity_settings:
  Connected:
    class: connectivity
```

**Comment by ChristophCaina** [comment]
thanks, great :)

**Comment by d0np3p3** [comment]
Yes if you set it to none it looks like this:
![Screenshot_20230212-232322~2.png](https://user-images.githubusercontent.com/93970411/218341015-74b26181-d3fb-4a25-81de-2090d7ebfcd7.png)

**Comment by ekutner** [comment]
When you set it to none you are actually setting it to the string "none". If you want to set it to nothing then you should use *null*

**Comment by ChristophCaina** [comment]
Hi,

one question about the "unit of measurement"...
is it possible to handle "cup / cups"  somehow?

![grafik](https://user-images.githubusercontent.com/26391061/218412722-93d8fb3c-9d0c-4ac8-8941-300b8158d78a.png)

Meaning: 1 Cup or 2 Cups (0 Cups) ...

**Comment by ChristophCaina** [comment]
Also, do we have an option to change the Icon based on the state of an entity?
For example:
The Switch "Cup-warmer" - I would like to use the "coffee-off-outline" icon when the sensor / switch is off and the coffee-outline icon when it is on.
Right now, it is using the "slider" icon by default - and with the entity settings, I could change the default color - but don't know, if I can change the icon based on the state... :)

**Comment by ekutner** [comment]
I'm not aware of a way to change the units from singular to plural and custom state dependent icons are also not supported.
