### ISSUE TITLE
Redirect URI 404 Not Found

### ISSUE THREAD

**Issue by ElyFNV** [ekutner/home-connect-hass#125]
Hi @ekutner 
I have connected my dishwasher to Home Assistant through the Home Connect Alt integration for months and it has always worked flawlessly. No problem. A month ago I had to change my modem and, as a result, I had to reset my dishwasher to the initial settings. I tried to set up the Home Connect Alt integration again, but every time I get the error "404 not found".
And I don't know why but every time any integration needs a redirect uri always ends up in the same "404 not found" error.
I use an account with Nabu Casa. It always worked perfectly, until with the latest updates the uri redirect was changed from "/auth/external/callback" to "/redirect/oauth".

As I said, I have now tried to reintegrate the Home Connect Alt integration, but of course I always get the "404 not found" error. And I don't know what I'm doing wrong, since I use "https://nabucasaurl/redirect/oauth" as callback URI.

Searching on the internet I found many solutions that claimed to re-enable the home assistant's "default_config" service. However I have never disabled it! In fact in the configuration.yaml I still have the entry "default_config:".

Do you know how to fix this?
Help me please! Thank you!

**Comment by ekutner** [comment]
I don't use Nabu Casa so can't say for sure but I believe the URL should always be the same one, as documented in the README file. Until now, in all cases of issues with the initial authentication it always ended up being when people didn't follow the instructions carefully enough so I would start with making absolutely sure that you followed the instructions to the letter and everything is configured as it should be.

**Comment by Adze1502** [comment]
What worked for me (and stated in home assistant documentation):

If you don’t have [My Home Assistant](https://www.home-assistant.io/integrations/my) on your installation, you can use <HOME_ASSISTANT_URL>/auth/external/callback as the redirect URI instead.

The <HOME_ASSISTANT_URL> must be the same as used during the configuration/ authentication process.

Internal examples: http://192.168.0.2:8123/auth/external/callback, http://homeassistant.local:8123/auth/external/callback.”

**Comment by ElyFNV** [comment]
> What worked for me (and stated in home assistant documentation):
> 
> If you don’t have [My Home Assistant](https://www.home-assistant.io/integrations/my) on your installation, you can use <HOME_ASSISTANT_URL>/auth/external/callback as the redirect URI instead.
> 
> The <HOME_ASSISTANT_URL> must be the same as used during the configuration/ authentication process.
> 
> Internal examples: http://192.168.0.2:8123/auth/external/callback, [http://homeassistant.local:8123/auth/external/callback.”](http://homeassistant.local:8123/auth/external/callback.%E2%80%9D)

I have "My Home Assistant" on my installation... However the Callback URI does not work for me... I dont know why. It always give me "404 not found" error.

**Comment by ekutner** [comment]
You need to configure the app as instructed in the README

**Comment by ElyFNV** [comment]
> You need to configure the app as instructed in the README

I did it. I did everything as the readme says... In fact I already had the integration working. Then I replaced my modem, changed wifi password and then had to reconfigure everything. Since then, I don't know why, the integration keeps giving me callback URI error. Before, everything worked perfectly.

**Comment by ekutner** [comment]
This shouldn't have anything to do with your modem.
Please post a screenshot of your app configuration, of your "my" configuration and the full url where you get the 404 error.

**Comment by ElyFNV** [comment]
> This shouldn't have anything to do with your modem. Please post a screenshot of your app configuration, of your "my" configuration and the full url where you get the 404 error.

I don't know why but now that I'm trying to go through all the integration steps again, if I write the Home Connect Alt configuration in my "configuration.yaml" file Home Assistant goes into a "configuration check" loop and prevents me from restarting the server. When I delete the Home Connect Alt configuration written, everything returns to normal and the "configuration check" is passed. I don't understand what is happening now! It has never happened before! My God.....

**Comment by ekutner** [comment]
Are you sure the integration is actually installed?

**Comment by ElyFNV** [comment]
> Are you sure the integration is actually installed?
I installed the add from HACS. Then rebooted the server. Then I created a new application on the Home Connect Developer Website; then added the config info (ID and Secret) into the "configuration.yaml" file. Tried to restart the server but without success, because the configuration check entered in a loop (as said before). 
So I tried to remove the info from "configuration.yaml" file and tries to add the Home Connect Alt integration without them. Obviously it gives an error. It tells me "Please wait, the setup for Home Connect Alt is starting" then, after 5 minutes of buffering it gives me the following error: "something went wrong".

**Comment by ekutner** [comment]
What is the configuration you are trying to add and fails to get verified?

**Comment by ElyFNV** [comment]
> What is the configuration you are trying to add and fails to get verified?

Simply this one:

`home_connect_alt:
  client_id: < Your Client ID >
  client_secret: < You Client Secret >`

**Comment by ekutner** [comment]
Are they properly indented?

**Comment by ElyFNV** [comment]
Yes. I copied from the repository and paste in my config file. Then replaced the id and secret with mine.
![1](https://user-images.githubusercontent.com/37159948/204036132-c02ab50a-279e-4695-ad43-19426547f85f.png)

**Comment by ekutner** [comment]
I have no idea why it wouldn't verify. Things to try:
1. This is a long shot but try typing those keywords manually instead of copying from the repo, Maybe there is some strange unreadable character that is inserted when copying. For the verification you don't need the correct ID and secret so you can put some random character there, just to verify that the config gets validated.
2. Remove the integration in hacks restart HA add it back then restart again.

**Comment by ElyFNV** [comment]
Well... removing and re-adding the integration from HACS fixed it.
Now I'll try to configure everything. As soon as I encounter the usual Callback URI error, I'll attach all the information you previously asked me for.
Thank you!

**Comment by ElyFNV** [comment]
Please post a screenshot of your app configuration, of your "my" configuration and the full url where you get the 404 error.
So... I attached a screenshot of my "configuration.yaml" file, where you can see that I have the "default_config" written.
Then I attached also the screenshot of the error I get.
My callback URI is this one: https://MYSECRETCODE.ui.nabu.casa/redirect/oauth.
However, if I copy-paste that URL on chrome I get "error 404 not found".... I don't know why. And if I use it as callback URI for Home Connect Alt I get the error I attached below.
![1](https://user-images.githubusercontent.com/37159948/204042210-b6816234-1319-489f-9e93-6209d3543e0a.png)
![2](https://user-images.githubusercontent.com/37159948/204042211-36c1c5a0-55a0-45e2-a105-fa23dfe5da62.png)

**Comment by ekutner** [comment]
This is not what the README says. Just do what is says.

**Comment by ElyFNV** [comment]
> This is not what the README says. Just do what is says.

I don't understand what you mean. I followed the README. If there is something I didn't do correctly or I skipped could you tell me? It is the 1,000th time I've double-checked but can't figure out where I'm wrong.
Sorry for my ignorance. I really appreciate your patience

**Comment by ekutner** [comment]
This is not the redirect url specified in the readme

**Comment by ElyFNV** [comment]
> rl specified in the read
In the README the redirect URI is: "https://my.home-assistant.io/redirect/oauth".
Probably I'm doing it wrong but... isn't "https://my.home-assistant.io" the URL of my HA instance? Because my HA instance is at my nabu casa URL. I don't know if I'm explaining myself correctly.

**Comment by ekutner** [comment]
Ignore nabu casa, it's not relevant here.  https://my.home-assistant.io/ is exactly the url you should configure, after you visit that url and configure it to point to your local HA instance, the one you can access on your local network.

**Comment by ElyFNV** [comment]
> Ignore nabu casa, it's not relevant here. https://my.home-assistant.io/ is exactly the url you should configure, after you visit that url and configure it to point to your local HA instance, the one you can access on your local network.

So, do I have to use my internal IP address? Because if I cannot use Nabu Casa URL, it means I do not have other URLs to use for my HA instance. And my internal address cannot be an HTTPS, but only a HTTP.

**Comment by ekutner** [comment]
Yes, use your ip address, it doesn't have to be https

**Comment by ElyFNV** [comment]
> Yes, use your ip address, it doesn't have to be https

Ok. So... There has been progress. I used my internal IP. And I actually managed to do the setup... or, at least, almost all of the setup. But in the end I get an alert with only "error" written. Nothing else. And, in fact, if I copy the following URL (http://192.168.1.51:8123/redirect/oauth) into the browser, it always gives me the "404 not found" error. 
![1](https://user-images.githubusercontent.com/37159948/204055179-fcadac7a-6c5a-40b3-98dc-8addf444553f.PNG)

**Comment by ekutner** [comment]
it's normal for it to give 404 when it's not waiting for a connection. are you using this IP to access HA when you are adding the integration or accessing through nabu casa? you should access it directly HA directly through the IP address

**Comment by ElyFNV** [comment]
> it's normal for it to give 404 when it's not waiting for a connection. are you using this IP to access HA when you are adding the integration or accessing through nabu casa? you should access it directly HA directly through the IP address

OK. I was trying to setup the integration accessing Home Assistant from Nabu Casa. I tried now accessing from the internal IP.
It is worse... I dont know why. It gives me this error (attached below). The configuration doesn't even start.
![Cattura](https://user-images.githubusercontent.com/37159948/204058021-d7f9b9d8-d119-47d8-ba5d-503829628b3c.PNG)

**Comment by ekutner** [comment]
Post a screenshot of your HC app config

**Comment by ElyFNV** [comment]
Do you mean of my configuration.yaml file? Because I cannot even reach the initial configuration of Home Connect Alt due to the error it gives me at the beginning.

**Comment by ekutner** [comment]
The home connect app

**Comment by ElyFNV** [comment]
![Cattura](https://user-images.githubusercontent.com/37159948/204058455-036646d4-49c8-4b8c-bd05-b299e9c5d1f3.PNG)

**Comment by ekutner** [comment]
The redirect uri should be https://my.home-assistant.io/redirect/oauth  which is exactly what the README says and what I asked you to do 10 messages ago. If you just follow the setup instructions to the letter it would work.

**Comment by ElyFNV** [comment]
> The redirect uri should be https://my.home-assistant.io/redirect/oauth which is exactly what the README says and what I asked you to do 10 messages ago. If you just follow the setup instructions to the letter it would work.

Sorry. I tried also with that one before. It didn't work. Always same error... Tried with that one URI right now, accessing from my internal IP to HA and setting up the integration. Same error.

**Comment by ekutner** [comment]
After you change the redirect URI it takes time to take effect, there's a note about that in the readme as well. 
If it doesn't start working in an hour then please post your app screenshot again, to verify you have the correct configuration now. Al's, navigate to https://my.home-assistant.io/ and take a screenshot of that screen as well.

**Comment by ElyFNV** [comment]
![1](https://user-images.githubusercontent.com/37159948/204060484-b4e03ec6-35ff-461c-bae2-95a21aceb5dc.PNG)

**Comment by ekutner** [comment]
this looks good. it should work now, once the config change takes effect. if it still doesn't then post the app screenshot again

**Comment by ElyFNV** [comment]
So. I tried again now. It didnt give me the same error of before. I tried accessing from my internal IP to HA and setting up the integration. The interface for configuring Home Connect came out. However, I get the same error that I gave you in the screenshot just before. That is, a generic error when I go to click on "link to HA", as showed below.
![1](https://user-images.githubusercontent.com/37159948/204063409-2cdd163c-a086-469b-9305-326308d35296.PNG)
![2](https://user-images.githubusercontent.com/37159948/204063411-b5558ffa-cc93-4d17-adc8-4a77ef0d8bdf.PNG)
![3](https://user-images.githubusercontent.com/37159948/204063412-1030c570-8289-440f-b12d-d8c28ac7e9da.PNG)


> this looks good. it should work now, once the config change takes effect. if it still doesn't then post the app screenshot again

**Comment by ekutner** [comment]
post the hc app screenshot

**Comment by ElyFNV** [comment]
![11](https://user-images.githubusercontent.com/37159948/204063685-65b5e33f-a6c7-406b-bd50-2d0a350b9d25.png)
![22](https://user-images.githubusercontent.com/37159948/204063737-7dd03a00-3fc9-48af-abab-2022ad855e30.png)

The full URL of the browser where I have to press on "link account" is this one: "https://my.home-assistant.io/redirect/oauth/?code=eyJ4LXJlZyI6IkVVIiwieC1lbnYiOiJQUkQiLCJ0b2tlbiI6IjJiZWQ4YzRkLTQ2N2QtNGZiZC04OGIyLWE3MWYyNjYwZjA1MyIsImNsdHkiOiJwcml2YXRlIn0%3D&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbG93X2lkIjoiNTc0YmIzNGI4MzE2YzM1OGY2ZmI0NjZkMDYyYjM3OGMiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL215LmhvbWUtYXNzaXN0YW50LmlvL3JlZGlyZWN0L29hdXRoIn0.exFJVxeXz3p-tJ6CBxBDwezPKI9YuMj3ysjJUYlsbsM&grant_type=authorization_code"

**Comment by ekutner** [comment]
This all looks ok now so please double check that you copied the secret key correctly to the configuration.yaml file and if you did then try removing the integration from hacs, like you did before. If that still doesn't solve it then please upload the complete log file.

**Comment by ElyFNV** [comment]
Finally! It worked! I removed and re-added the integration from HACS. Restarted the server and now everything works!
I am very sorry to have bothered you so much and I am extremely grateful to you for having all this patience. You managed to follow me, despite my great difficulties. And you managed to solve the problem. Thank you very much indeed. I appreciate it very much.

**Comment by ekutner** [comment]
Happy to hear that, hope you enjoy it.
