### ISSUE TITLE
How to monitor power consumption (to save on the power bill)

### ISSUE THREAD

**Issue by oywino** [ekutner/home-connect-hass#126]
## Describe the bug
I'm not sure if this is a bug or not, but my primary purpose of integrating all my Siemens kitchen appliances with Home Assistant, is to monitor their power consumption, and consequently manage when to let them operate (or not) according to the current power price forecast.
However, not a single on of my 4 Siemens devices (fridge, induction-top, micro and dishwasher) has an attribute reporting its power consumption in real time (or in any time).
So I guess my question is: Is it a fact that no Siemens appliance is designed to report power consumption ?!?  Or should I expect to find an attribute for this, but something in my setup (using this CC) is incorrect?
I have a ton of other useless attributes, so the integration itself seems to work ok.

## Version of the custom_component
 0.5.7

## Configuration

```yaml

Add your configuration here.
home_connect_alt:
  client_id: 301C08ED8D8A494B5FCEC88B0B749DE37A4823324462D1xxxxxxxxxxxxxxxxx
  client_secret: 0B39561B9F8DD3346FCAAE16D115CAFBE9AA433E99CB62F2xxxxxxxxxxxxxxxxx
  name_template: $brand $appliance - $name```


## Debug log

<!-- 
Check the README for instuctions on how to enable debug logging

If the bug results in an exception paste it below, in all other cases please attach the entire log file
-->

```text
Add your logs here (or attach the log file).

```

**Comment by ekutner** [comment]
What you get is what the API exposes, if it's not there then it's not available in the API. The right place for questions like that is in the discussions section.
