### ISSUE TITLE
Cannot select Microwave programs for Microwave/Oven combination

### ISSUE THREAD

**Issue by rhpijnacker** [ekutner/home-connect-hass#128]
The integration of my Microwave/Oven combination seems to be working fine for the oven functions.
When I start a microwave program, I see Cooking.Oven.Program.Microwave.600Watt being started.

However, when I try to add an automation to start a program, only the Cooking.Oven.Program.Heating.X options are present in the combobox.

## Version of the custom_component

Using version 0.5.7.

- I'm not sure what configuration data to add
- I added the debug logging to configuration.yaml as described, but get no debug logging in the logfile.

**Comment by ekutner** [comment]
The data should be in the log file but if you don't see those options in the dropdown list then it's most likely not being sent by the API. It happens a lot that there are programs which are available in the appliance itself and the mobile app but are not available for selection through the API.

**Comment by rhpijnacker** [comment]
I managed to enable the debug logging:

[home-assistant.log](https://github.com/ekutner/home-connect-hass/files/9923889/home-assistant.log)

**Comment by ekutner** [comment]
There were 7 available programs received from the API, if the dropdown is showing 7 programs then it is showing everything that was received.
In general you can use the select_program and start_program services to select/start a program but you the API will reject a program which is not listed as available.

**Comment by rhpijnacker** [comment]
There are actually 11 programs to be selected from the dropdown. (All of them HeatingMode related.)
I tried editing a yaml script to select_program Cooking.Oven.Program.Microwave.600Watt, but as you predicted, that is not allowed.

**Comment by ekutner** [comment]
You're right, I didn't notice you had two appliances. The dishwasher has 7 programs and the oven has 11. 
I'm closing this issue now because there is nothing I can do about it, these are the programs made available by the API.
