### ISSUE TITLE
dishwasher relaxant / salt low level warning ?

### ISSUE THREAD

**Issue by gibman** [ekutner/home-connect-hass#129]
From time to time I receive a notification ony my siemens home connect app telling me that salt and/or relaxant levels on my dishwasher are low thus need refilling.

it would be great id these could be exposed as a binary sensor in home assistant.
is this part of the home connect api ?

**Comment by ekutner** [comment]
Duplicate of #53

**Comment by ekutner** [comment]
duplicate of #115
