### ISSUE TITLE
Missing Controls for Dishwasher

### ISSUE THREAD

**Issue by carlhye** [ekutner/home-connect-hass#130]
In the Dishwasher controls in HA, I can turn on/off the options for 'Silence on Demand', and 'Vario Speed Plus', but I am missing the options to turn on/off the options: 'Brilliance Dry', and 'Intensiv Zone' - these are only available as binary sensors.

**Available switches:**
`switch.012010***************_dishcare_dishwasher_option_silenceondemand`
`switch.012010***************_dishcare_dishwasher_option_variospeedplus`

I'm able to see the status of 'Brilliance Dry', and 'Intensiv Zone' but only as binary sensors.

**Available sensors, that should be switches:**
`binary_sensor.012010***************_dishcare_dishwasher_option_brilliancedry`
`binary_sensor.012010***************_dishcare_dishwasher_option_intensivzone`

I use the Brilliance Dry function on every wash, not having this available in HA, forces me to use the Home Connect app to start my  dishwasher.

Being able to turn these functions on/off, would also make it possible to use them in automations.

**Proposed Solution**
I would like to be able to turn on/off 'Brilliance Dry', and 'Intensiv Zone' with switch entities in the same way as Vario Speed Plus and Silence On Demand.

A solution would be to change the current binary sensors of 'Brilliance Dry' and 'Intensiv Zone' from _binary sensors_ to _switches_.

**Alternatives**
Only alternative is to use the Home Connect app to turn on the dishwasher, if I want to use the above mentioned functions.

**Comment by bulusomer** [comment]
i have the same kind of problem. For my case I can not set option variospeedplus, even if I can set it true with home connect app.

**Comment by carlhye** [comment]
It almost sounds more like a bug, then.

**Comment by bulusomer** [comment]
```
binary_sensor.261030387968001062_dishcare_dishwasher_option_silenceondemand
binary_sensor.261030387968001062_dishcare_dishwasher_option_variospeed
```

My automation exposes the binary sensors above. When the machine is running I am able to call set_program_option to activate silence on demand feature with the following command. And it is working.

```
service: home_connect_alt.set_program_option
data:
  device_id: 0bad73acfe8058d034ffd0b4103974bf
  key: "Dishcare.Dishwasher.Option.SilenceOnDemand"
  value: true
```

But when i try to activate the variospeed feature I am getting "Failed to call service home_connect_alt.set_program_option. The option isn't currently available.

I have checked the Home connect API website and seen that there is no option called "VarioSpeed", but "VarioSpeedPlus".
I have tried to set **Dishcare.Dishwasher.Option.VarioSpeedPlus** to true but it was also not possible.

I think my dishwasher causes this issue.

**Comment by bulusomer** [comment]
This error originated from a custom integration.

Logger: custom_components.home_connect_alt.button
Source: custom_components/home_connect_alt/button.py:267
Integration: Home Connect Alt (documentation, issues)
First occurred: 3:55:55 PM (3 occurrences)
Last logged: 8:17:20 PM

{ "appliances": { "261030387968001062": { "name": "Dishwasher", "brand": "Siemens", "vib": "SN61IX60MT", "connected": true, "type": "Dishwasher", "enumber": "SN61IX60MT/16", "haId": "261030387968001062", "uri": "/api/homeappliances/261030387968001062", "available_programs": { "Dishcare.Dishwasher.Program.Intensiv70": { "key": "Dishcare.Dishwasher.Program.Intensiv70", "name": "Yo\u011fun 70\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Auto2": { "key": "Dishcare.Dishwasher.Program.Auto2", "name": "Oto 45-65\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Eco50": { "key": "Dishcare.Dishwasher.Program.Eco50", "name": "Eko 50\u00b0", "options": { "BSH.Common.Option.StartInRelative": { "key": "BSH.Common.Option.StartInRelative", "value": null, "type": "Int", "name": "Ba\u015flang\u0131\u00e7 zaman\u0131", "unit": "seconds", "displayvalue": null, "min": 0, "max": 86400, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.ExtraDry": { "key": "Dishcare.Dishwasher.Option.ExtraDry", "value": null, "type": "Boolean", "name": "Ekstra kurutma", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": true, "access": null }, "Dishcare.Dishwasher.Option.HygienePlus": { "key": "Dishcare.Dishwasher.Option.HygienePlus", "value": null, "type": "Boolean", "name": "Hijyen +", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": true, "access": null } }, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Quick45": { "key": "Dishcare.Dishwasher.Program.Quick45", "name": "Speed 45\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Quick65": { "key": "Dishcare.Dishwasher.Program.Quick65", "name": "Speed 65\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.MachineCare": { "key": "Dishcare.Dishwasher.Program.MachineCare", "name": "Makine temizlik progra.", "options": null, "execution": "selectandstart", "active": false } }, "active_program": null, "selected_program": { "key": "Dishcare.Dishwasher.Program.Eco50", "name": "Eko 50\u00b0", "options": { "BSH.Common.Option.StartInRelative": { "key": "BSH.Common.Option.StartInRelative", "value": 0, "type": null, "name": "Ba\u015flang\u0131\u00e7 zaman\u0131", "unit": "seconds", "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.ExtraDry": { "key": "Dishcare.Dishwasher.Option.ExtraDry", "value": true, "type": null, "name": "Ekstra kurutma", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.HygienePlus": { "key": "Dishcare.Dishwasher.Option.HygienePlus", "value": true, "type": null, "name": "Hijyen +", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.SilenceOnDemand": { "key": "Dishcare.Dishwasher.Option.SilenceOnDemand", "value": true, "type": null, "name": "\u015eimdi sessiz", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.VarioSpeed": { "key": "Dishcare.Dishwasher.Option.VarioSpeed", "value": true, "type": null, "name": "VarioSpeed", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null } }, "execution": null, "active": false }, "status": { "BSH.Common.Status.RemoteControlStartAllowed": { "key": "BSH.Common.Status.RemoteControlStartAllowed", "value": true, "name": "Uzaktan ba\u015flatma", "displayvalue": null, "unit": null }, "BSH.Common.Status.RemoteControlActive": { "key": "BSH.Common.Status.RemoteControlActive", "value": true, "name": "Uzaktan Kumanda", "displayvalue": null, "unit": null }, "BSH.Common.Status.DoorState": { "key": "BSH.Common.Status.DoorState", "value": "BSH.Common.EnumType.DoorState.Closed", "name": "Kapak", "displayvalue": "Kapal\u0131", "unit": null }, "BSH.Common.Status.OperationState": { "key": "BSH.Common.Status.OperationState", "value": "BSH.Common.EnumType.OperationState.Ready", "name": "\u0130\u015flem durumu", "displayvalue": "Haz\u0131r", "unit": null } }, "settings": { "BSH.Common.Setting.PowerState": { "key": "BSH.Common.Setting.PowerState", "value": "BSH.Common.EnumType.PowerState.On", "type": "BSH.Common.EnumType.PowerState", "name": "G\u00fc\u00e7 durumu", "unit": null, "displayvalue": "A\u00e7\u0131k", "min": null, "max": null, "stepsize": null, "allowedvalues": [ "BSH.Common.EnumType.PowerState.Off", "BSH.Common.EnumType.PowerState.On" ], "execution": null, "liveupdate": null, "access": "readWrite" } }, "commands": {}, "startonly_options": null, "startonly_program": null, "_active_program_fail_count": 0 } } }
{ "appliances": { "261030387968001062": { "name": "Dishwasher", "brand": "Siemens", "vib": "SN61IX60MT", "connected": true, "type": "Dishwasher", "enumber": "SN61IX60MT/16", "haId": "261030387968001062", "uri": "/api/homeappliances/261030387968001062", "available_programs": { "Dishcare.Dishwasher.Program.Intensiv70": { "key": "Dishcare.Dishwasher.Program.Intensiv70", "name": "Yo\u011fun 70\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Auto2": { "key": "Dishcare.Dishwasher.Program.Auto2", "name": "Oto 45-65\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Eco50": { "key": "Dishcare.Dishwasher.Program.Eco50", "name": "Eko 50\u00b0", "options": {}, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Quick45": { "key": "Dishcare.Dishwasher.Program.Quick45", "name": "Speed 45\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Quick65": { "key": "Dishcare.Dishwasher.Program.Quick65", "name": "Speed 65\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.MachineCare": { "key": "Dishcare.Dishwasher.Program.MachineCare", "name": "Makine temizlik progra.", "options": null, "execution": "selectandstart", "active": false } }, "active_program": null, "selected_program": { "key": "Dishcare.Dishwasher.Program.Eco50", "name": "Eko 50\u00b0", "options": { "BSH.Common.Option.StartInRelative": { "key": "BSH.Common.Option.StartInRelative", "value": 0, "type": null, "name": "Ba\u015flang\u0131\u00e7 zaman\u0131", "unit": "seconds", "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.ExtraDry": { "key": "Dishcare.Dishwasher.Option.ExtraDry", "value": true, "type": null, "name": "Ekstra kurutma", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.HygienePlus": { "key": "Dishcare.Dishwasher.Option.HygienePlus", "value": true, "type": null, "name": "Hijyen +", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.SilenceOnDemand": { "key": "Dishcare.Dishwasher.Option.SilenceOnDemand", "value": true, "type": null, "name": "\u015eimdi sessiz", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.VarioSpeed": { "key": "Dishcare.Dishwasher.Option.VarioSpeed", "value": true, "type": null, "name": "VarioSpeed", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null } }, "execution": null, "active": false }, "status": { "BSH.Common.Status.RemoteControlStartAllowed": { "key": "BSH.Common.Status.RemoteControlStartAllowed", "value": true, "name": "Uzaktan ba\u015flatma", "displayvalue": null, "unit": null }, "BSH.Common.Status.RemoteControlActive": { "key": "BSH.Common.Status.RemoteControlActive", "value": true, "name": "Uzaktan Kumanda", "displayvalue": null, "unit": null }, "BSH.Common.Status.DoorState": { "key": "BSH.Common.Status.DoorState", "value": "BSH.Common.EnumType.DoorState.Closed", "name": "Kapak", "displayvalue": "Kapal\u0131", "unit": null }, "BSH.Common.Status.OperationState": { "key": "BSH.Common.Status.OperationState", "value": "BSH.Common.EnumType.OperationState.Inactive", "name": "\u0130\u015flem durumu", "displayvalue": "Devre d\u0131\u015f\u0131", "unit": null } }, "settings": { "BSH.Common.Setting.PowerState": { "key": "BSH.Common.Setting.PowerState", "value": "BSH.Common.EnumType.PowerState.Off", "type": "BSH.Common.EnumType.PowerState", "name": "G\u00fc\u00e7 durumu", "unit": null, "displayvalue": "Kapal\u0131", "min": null, "max": null, "stepsize": null, "allowedvalues": [ "BSH.Common.EnumType.PowerState.Off", "BSH.Common.EnumType.PowerState.On" ], "execution": null, "liveupdate": null, "access": "readWrite" } }, "commands": {}, "startonly_options": null, "startonly_program": null, "_active_program_fail_count": 0 } } }
{ "appliances": { "261030387968001062": { "name": "Dishwasher", "brand": "Siemens", "vib": "SN61IX60MT", "connected": true, "type": "Dishwasher", "enumber": "SN61IX60MT/16", "haId": "261030387968001062", "uri": "/api/homeappliances/261030387968001062", "available_programs": { "Dishcare.Dishwasher.Program.Intensiv70": { "key": "Dishcare.Dishwasher.Program.Intensiv70", "name": "Yo\u011fun 70\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Auto2": { "key": "Dishcare.Dishwasher.Program.Auto2", "name": "Oto 45-65\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Eco50": { "key": "Dishcare.Dishwasher.Program.Eco50", "name": "Eko 50\u00b0", "options": {}, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Quick45": { "key": "Dishcare.Dishwasher.Program.Quick45", "name": "Speed 45\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.Quick65": { "key": "Dishcare.Dishwasher.Program.Quick65", "name": "Speed 65\u00b0", "options": null, "execution": "selectandstart", "active": false }, "Dishcare.Dishwasher.Program.MachineCare": { "key": "Dishcare.Dishwasher.Program.MachineCare", "name": "Makine temizlik progra.", "options": null, "execution": "selectandstart", "active": false } }, "active_program": null, "selected_program": { "key": "Dishcare.Dishwasher.Program.Eco50", "name": "Eko 50\u00b0", "options": { "BSH.Common.Option.StartInRelative": { "key": "BSH.Common.Option.StartInRelative", "value": 0, "type": null, "name": "Ba\u015flang\u0131\u00e7 zaman\u0131", "unit": "seconds", "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.ExtraDry": { "key": "Dishcare.Dishwasher.Option.ExtraDry", "value": false, "type": null, "name": "Ekstra kurutma", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.HygienePlus": { "key": "Dishcare.Dishwasher.Option.HygienePlus", "value": false, "type": null, "name": "Hijyen +", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.SilenceOnDemand": { "key": "Dishcare.Dishwasher.Option.SilenceOnDemand", "value": false, "type": null, "name": "\u015eimdi sessiz", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null }, "Dishcare.Dishwasher.Option.VarioSpeed": { "key": "Dishcare.Dishwasher.Option.VarioSpeed", "value": false, "type": null, "name": "VarioSpeed", "unit": null, "displayvalue": null, "min": null, "max": null, "stepsize": null, "allowedvalues": null, "execution": null, "liveupdate": null, "access": null } }, "execution": null, "active": false }, "status": { "BSH.Common.Status.RemoteControlStartAllowed": { "key": "BSH.Common.Status.RemoteControlStartAllowed", "value": true, "name": "Uzaktan ba\u015flatma", "displayvalue": null, "unit": null }, "BSH.Common.Status.RemoteControlActive": { "key": "BSH.Common.Status.RemoteControlActive", "value": true, "name": "Uzaktan Kumanda", "displayvalue": null, "unit": null }, "BSH.Common.Status.DoorState": { "key": "BSH.Common.Status.DoorState", "value": "BSH.Common.EnumType.DoorState.Open", "name": "Kapak", "displayvalue": "A\u00e7\u0131k", "unit": null }, "BSH.Common.Status.OperationState": { "key": "BSH.Common.Status.OperationState", "value": "BSH.Common.EnumType.OperationState.Inactive", "name": "\u0130\u015flem durumu", "displayvalue": "Devre d\u0131\u015f\u0131", "unit": null } }, "settings": { "BSH.Common.Setting.PowerState": { "key": "BSH.Common.Setting.PowerState", "value": "BSH.Common.EnumType.PowerState.Off", "type": "BSH.Common.EnumType.PowerState", "name": "G\u00fc\u00e7 durumu", "unit": null, "displayvalue": "Kapal\u0131", "min": null, "max": null, "stepsize": null, "allowedvalues": [ "BSH.Common.EnumType.PowerState.Off", "BSH.Common.EnumType.PowerState.On" ], "execution": null, "liveupdate": null, "access": "readWrite" } }, "commands": {}, "startonly_options": null, "startonly_program": null, "_active_program_fail_count": 0 } } }

**Comment by ekutner** [comment]
According to this, VarioSpeed is not an option that can be set for your appliance through the API. The error you are getting is because the integration is validating the value and determines that it is not valid. 
You can bypass the validation by calling the *select_program* service with the VarioSpeed option and with *validate: false*. Doing that will send the request directly to the API, bypassing the local validation logic. I expect it to generate an API error, but if it doesn't that should prove interesting.

**Comment by carlhye** [comment]
Not trying to critizise the integration, @ekutner - far from it, it's great work! 

As someone that would like to use the Home Assistant UI to build the automation (product engineer, not a developer), going through the API I find the options for the four available functions to be the exact same.

1. [Intensive Zone Option](https://api-docs.home-connect.com/programs-and-options?#dishwasher_intensive-zone-option)
2. [Brilliance Dry Option](https://api-docs.home-connect.com/programs-and-options?#dishwasher_brilliance-dry-option)
3. [VarioSpeed Plus Option](https://api-docs.home-connect.com/programs-and-options?#dishwasher_variospeed-plus-option)
4. [Silence on Demand Option](https://api-docs.home-connect.com/programs-and-options?#dishwasher_silence-on-demand-option)

In the API, all of them are stated as

**Data type**
Boolean

**Possible values**
* true if enabled
* false otherwise

When I use the standard program eco50, in the app I have option 1-3 available, so by this logic I should be able to use those for that program.

What I don't understand is, that the properties for the functions are the same, but some of them are interpreted by the integration as switches, and some just as sensors.

**Comment by ekutner** [comment]
All properties available for the appliance are created as sensor entities in HA. Properties that the API allows to be are also created as settable entities in HA (like switches, numbers, select boxes etc). If some property is not created as settable in HA that's because it can't be set through the API. 
There are also cases where the settable entities will be greyed out, which can happen when they are allowed to be set only in specific cases, for example some properties can only be set for specific programs but not for others.

**Comment by carlhye** [comment]
Yeah, can confirm that the two settings that I have, is greyed when I choose certain programs.

What I don't understand though, is why the two other settings is listet as sensors, instead of switches, when they have the same properties in the API documentation? 

Where in the process is the validation of the field properties happening?

Can I test this somehow - don't think have a HAID for my dishwasher.
 
Am I missing something, or looking in the wrong documentation? 🤔

**Comment by ekutner** [comment]
I don't really understand the question.
Every appliance has a HAID, you can see it as part of the entity ID in HA.

**Comment by bulusomer** [comment]
Thanks for the help @ekutner.

I have tried the HomeConnect API at Postman application and seen that the problems are not caused by your integration. 

I would just like to add that setting "program options" for selected and active programs are only supported for ovens, but no other appliances.  Anyhow setting ExtraDry, HygienePlus and SilenceOnDemand works.

I think this is the reason for the troubles caused.

**Comment by carlhye** [comment]
Yes, you should absolutely not take any of this as negative critique on the integration, @ekutner - it's most likely me who don't understand the functions in the API completely (not a dev).

I did not realise that the number was the HAID - will try to play around with the API.

Anyways, thank you for working on this with me, @bulusomer and @ekutner :-)

**Comment by ekutner** [comment]
@bulusomer So just to confirm, you've verified with Postman that everything supported by the API is exposed by the integration as it should?

As for what options are supported, they vary by specific appliance, that is why the integration dynamically creates all the entities based on what the API exposes for every specific appliance.

**Comment by ekutner** [comment]
@carlhye if you're going to use the API then it has a call that gets you the haid which is what you should be using.

**Comment by bulusomer** [comment]
@ekutner Sorry for the late reply.

Your integration is working totally the same with the API.

**Comment by ekutner** [comment]
Thanks for verifying.
