### ISSUE TITLE
Only 3 entities exposed?

### ISSUE THREAD

**Issue by bommel947** [ekutner/home-connect-hass#136]
Version: 0.5.9

I have successfully installed the integration via HACS.

But I dont see any sensors from my bosch dishwasher.

Only 3 entities are exposed. I have no idea :-(

![image](https://user-images.githubusercontent.com/45903971/204105654-cf35fbc1-35a3-4a7a-bb0c-3819608ff694.png)

Any help is greatly appreciated!

Thank you for your support

regards
Manfred

**Comment by canedje** [comment]
Did you start your dishwasser already?

**Comment by bommel947** [comment]
yes, it is currently running 
![image](https://user-images.githubusercontent.com/45903971/204105949-6f237b26-55ff-4ab8-8840-dba469b713be.png)

**Comment by canedje** [comment]
In my situation all sensors where available after first run the machine

**Comment by ekutner** [comment]
Read the FAQ. Closing this issue now.

**Comment by ausfas** [comment]
I can't where is this explained in FAQ "Only 3 entities exposed", could you please explain ?

**Comment by ekutner** [comment]
"Some of my appliances are not showing up after I added the integration"
