### ISSUE TITLE
Progress state on dryer WTX7m50 is not updated

### ISSUE THREAD

**Issue by jjdave2002** [ekutner/home-connect-hass#138]
Realized that the program state for dryer WTX7m50 is not updated. It stays always on 0% althouh the driyer is working and updating the other sensors. What could be the reason?

sensor.bosch_wtxh7m50ch_68a40e92854c_bsh_common_option_programprogress

Thanks

**Comment by ekutner** [comment]
Updates are based on events received from the HC service. If they are not updating this metric the sensor will not update either.
You can upload a debug log if you want me to verify this but if the other sensors are updating then that is most likely the reason.

**Comment by jjdave2002** [comment]
Ok, thanks. Where and how to get the correct debug LOG? 

BTW: just saw my API is blocked. Any idea to unlock or see whats the reason for it? Best Regards

**Comment by ekutner** [comment]
see the README for answers to all these questions
