### ISSUE TITLE
Dishwasher missing/not loaded to Home Assistant

### ISSUE THREAD

**Issue by andictix** [ekutner/home-connect-hass#143]
Hello,
I have a dishwasher and an extractor hood and moved from the official home connect app to this one. In the official home connect app both devices are listed but in the "home connect alt" version I only have a device for the extractor hood and a Home Connect Service, the dishwasher is not listed as device.
Any ideas how to get the dishwasher integrated? It's an SMD6ECX57E

official Home Connect Integration:
![grafik](https://user-images.githubusercontent.com/76598461/209962403-4f76f2d8-7a0a-4348-b77b-778e16bfe3c6.png)

Home Connect Alt Integration:
![grafik](https://user-images.githubusercontent.com/76598461/209962475-90c1eb1a-93c3-43cc-8e37-78259c778739.png)

**Comment by ekutner** [comment]
Read the README

**Comment by andictix** [comment]
issues solved, a reset of the dishwasher solved the problem. However it is not necessary to check the connection over mobile phone without wifi. the important thing is that the connection to the device is established via cloud. this can be checked within in the home connect app in the settings of the device under the network section.
