### ISSUE TITLE
Can the API be tested using CURL ?

### ISSUE THREAD

**Issue by oywino** [ekutner/home-connect-hass#144]
**Is your feature request related to a problem? Please describe.**
This isn't exactly a feature request, and it isn't an issue. So, where do I put it?
I'm just wondering if it is possible to test the API using CURL (or any other API testing tool).

**Describe the solution you'd like**
I tried a GET to `https://api.home-connect.com/api/homeappliances/events` but of course that didn't work. I got a 401.
Can you please point me to where I can find information about the correct URI and the necessary missing headers, auth etc. in order to test the API?

**Describe alternatives you've considered**

**Additional context**

**Comment by ekutner** [comment]
You can use curl but you need to get an OAuth access token first, or you can use the api page on the home-connect developers website. Either way, this kind of question should be posted on the discussion board.

**Comment by oywino** [comment]
@ekutner - Excellent, and where is the discussion board?
