### ISSUE TITLE
Add diagnostics support

### ISSUE THREAD

**Issue by yuvalabou** [ekutner/home-connect-hass#15]
**Is your feature request related to a problem? Please describe.**
Add support for diagnostics to help further improve the integration

**Comment by ekutner** [comment]
What kind of diagnostics are you looking to get?

**Comment by yuvalabou** [comment]
My Siemens dishwasher seems to expose data that is unavailable, and what that is available is sometimes too late to create an automation out of.. so diagnostics support can help with that.

**Comment by ekutner** [comment]
The integration already writes quite an extensive log (see the README.md on how to enable that) and the *Home Connect Debug* button writes the memory model to the log. If there is additional diagnostics information you think is missing please open a new issue with details.
If you have a specific problem feel free to report that problem and provide the requested log file.

**Comment by Krocko** [comment]
@ekutner i think he is meaning this: https://www.home-assistant.io/integrations/diagnostics/

**Comment by yuvalabou** [comment]
Indeed, it can very much help identify the problem without the need to enable debug and wait for a problem to accure..

**Comment by ekutner** [comment]
I can add it but I'm not sure I see the point. It will dump the same information as the debug button, but that information reflects the memory state of the integration which is constantly changing and doesn't help with debugging if it comes without the context provided by the log.
