### ISSUE TITLE
Home Connect Status: BLOCKED

### ISSUE THREAD

**Issue by cristidobrescu** [ekutner/home-connect-hass#150]
I'm using this integration but after a while this integration stoped working and status shows BLOCKED
![0492B3AE-B67B-433C-953A-9C6556E5CDED](https://user-images.githubusercontent.com/99839121/212933207-4d2cab0f-a51f-45a6-9fbb-760fcd2f85e5.png)
![A01FF59C-ADAE-4316-BAF1-98E6E27B94B6](https://user-images.githubusercontent.com/99839121/212933614-d0d14029-378b-493a-8f60-38c6858d7686.png)

Any ideea why is happening this?

**Comment by cristidobrescu** [comment]
I`ve answered myself by reading FAQ

**Comment by ekutner** [comment]
> I`ve answered myself by reading FAQ

Yes, that's why the instructions for reporting an issue asks you to do that before opening it
