### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; 

### ISSUE THREAD

**Issue by Mitch73-2** [ekutner/home-connect-hass#154]
I running Home Assistant beta :
- core-2023.2.0b2
- supervisor-2023.01.1

After the last update I see the following warning in my logs about Home Connect Alt :
Can you take a look at this please.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 07:26:21 (2 occurrences)
Last logged: 07:26:24

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for home_connect_alt using this method at custom_components/home_connect_alt/__init__.py, line 152: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for hacs using this method at custom_components/hacs/__init__.py, line 177: hass.config_entries.async_setup_platforms(

**Comment by ekutner** [comment]
Thanks for reporting. Fixed in the latest version.
