### ISSUE TITLE
All my devices became unavailable after upgrading

### ISSUE THREAD

**Issue by oywino** [ekutner/home-connect-hass#159]
## Describe the bug
After upgrading the 'Home Connect Alt' integration today, all my appliances became unavailable.

## Version of the custom_component
 v0.5.10 (downloaded version 0.6.0-b1)
HA v2023.2.2

## Configuration

configuration.yaml

Add your configuration here.
home_connect_alt:
  client_id: 301C08ED8D8A494B5FCEC88B0B749DE37A4823324462D195E82XXXXXXXXX
  client_secret: 0B39561B9F8DD3346FCAAE16D115CAFBE9AA433E99CB62F290XXXXXXXXXXX
  name_template: $brand $appliance - $name

## Debug log

[home-assistant_2023-02-06T11-59-32.681Z.log](https://github.com/ekutner/home-connect-hass/files/10662751/home-assistant_2023-02-06T11-59-32.681Z.log)

```text
Paste the exception info here

```

**Comment by stockklauser** [comment]
i have the same problem

**Comment by ekutner** [comment]
This was a beta version for a specific issue. As a best practice it is best not to install beta version unless it fixes a specific issue you are having (just uncheck beta/pre-release versions in HACS). Anyway, it should now be fixed with 0.6.0-b2

**Comment by oywino** [comment]
0.6.0-b2 seems to solve the issue. Many thanks 👍
However, I do not know where in HACS to uncheck beta/pre-releases. Could you explain?

**Comment by ekutner** [comment]
@oywino Go to the integration page in HACS open the three dots menu and select "redownload" there is an option there whether or not to show beta versions. That option was also displayed when you first installed the integration.
