### ISSUE TITLE
Undefined message during integration setup

### ISSUE THREAD

**Issue by janlugt** [ekutner/home-connect-hass#16]
## Version of the custom_component
0.4.4

## Describe the bug
During integration setup, the key of a message is displayed, instead of the actual message. Maybe some lookup function needs to be used?

![home connect integration bug](https://user-images.githubusercontent.com/287141/163873803-c5150afc-575a-4863-9f19-917281b9e7e9.png)

**Comment by ekutner** [comment]
Try the latest version 0.4.5 it should fix this issue

**Comment by ekutner** [comment]
I'm going to close this issue, feel free t reopen if it still happens with the latest version.
