### ISSUE TITLE
Account linking rejected

### ISSUE THREAD

**Issue by kazir1** [ekutner/home-connect-hass#172]
Hi. everything is done according to the instructions, after the transfer to the site https://my.home-assistant.io/redirect/oauth / there is no confirmation only what is in the picture
![image](https://user-images.githubusercontent.com/82515303/220979822-6d8e2bf7-6850-49bf-8294-b0ff381b9e87.png)

**Comment by d0np3p3** [comment]
Do you have a capital letter in your mail?
Maybe the same problem like https://github.com/home-assistant/core/issues/86999 ?

**Comment by kazir1** [comment]
![image](https://user-images.githubusercontent.com/82515303/221114275-3e6efc5b-982e-4cc7-9768-a112a20c3c11.png)

**Comment by kazir1** [comment]
after clicking login gets this
![image](https://user-images.githubusercontent.com/82515303/221114391-0337b516-4e26-423e-8e35-4859b9c98e97.png)
can I show you some other settings?

**Comment by kazir1** [comment]
I have created a clean account in Home Connect 100% without capital letters. I get the same result.

**Comment by ekutner** [comment]
This kind of problem is always the result of a configuration issue, it is not an integration issue so I'll be closing this issue now. You can find some suggestions for solution here: https://community.home-assistant.io/t/home-connect-integration-error/440268

**Comment by kazir1** [comment]
ok thnk
