### ISSUE TITLE
2023.3.0 - failed to setup

### ISSUE THREAD

**Issue by Symbiot78** [ekutner/home-connect-hass#175]
after update to newest version integration fails to setup.
screenshot for details.

![image](https://user-images.githubusercontent.com/3314249/222274515-653aa12c-7f03-4229-a5a9-38c4932a830f.png)

**Comment by alexeiw123** [comment]
Same here for me
![image](https://user-images.githubusercontent.com/77809797/222276904-d29e4d3e-84e1-43b3-8742-a91d8dd79385.png)

**Comment by lcavalli** [comment]
Upgrading to 0.6.0-b6 beta version fixes the issue as reported in https://github.com/ekutner/home-connect-hass/issues/171

**Comment by alexeiw123** [comment]
Thanks - was just coming back to confirm that HACS update fixed this. It did cause a configuration check error so had to manually do a full hardware restart. All came up ok though.
