### ISSUE TITLE
Home Assistant 2023.3.0 - 0.6.0 Home Connect Alt issue with configuration

### ISSUE THREAD

**Issue by DimitriTeerink** [ekutner/home-connect-hass#176]
## Describe the bug
The new version of Home Assistant (2023.3.0) breaks Home Connect Alt integration (0.6.0). I got a configuration issue with it. 

## Debug log
When checking configuration trought Home Assistant -> Developers Tools -> Yaml i got an error with home-connect-async. 
```text
Integration error: home_connect_alt - Requirements for home_connect_alt not found: ['home-connect-async==0.7.5'].
```

**Comment by Sese-Schneider** [comment]
+1

**Comment by Sese-Schneider** [comment]
@DimitriTeerink @grego1981 are you sure you've updated to the latest version?
I also had this issue, but updating to `0.6.0` fixed it for me

**Comment by bertbaron** [comment]
Same for me, I think since the update to 0.6.0 while also updating HACS itself and some other integrations.. My HA now refuses to restart because of the validation error. I'm tempted to try to restart my server in the hope that that will magically solve any problem but I'm not sure what will happen then.

**Comment by grego1981** [comment]
Just updated, then disabled the integration from the config yaml and from integrations, restarted the HA and re enabled it in both places. Everything now works as before!

**Comment by bertbaron** [comment]
Everything ok here also after a reboot of my server.

**Comment by ekutner** [comment]
A manual restart of HA is required. The easiest way to do that is through the command line.
