### ISSUE TITLE
yaml failure

### ISSUE THREAD

**Issue by Ceel84** [ekutner/home-connect-hass#181]
Hallo
i have a yaml failure:
Konfiguration fehlerhaft!
Integration error: home_connect_alt - Requirements for home_connect_alt not found: ['home-connect-async==0.7.5'].

home_connect_alt:
  client_id: XXXXXXXXXXX
  client_secret: XXXXXXXXXXXX
  name_template: $brand $appliance - $name
  language: de
  sensor_value_translation: server

**Comment by ekutner** [comment]
you should update to version 0.6.0 of the integration and manually restart HA, not through the UI.

**Comment by Ceel84** [comment]
Oh sorry
Thank you
