### ISSUE TITLE
No more translation after Home Assistant version update

### ISSUE THREAD

**Issue by Rep-Hueman** [ekutner/home-connect-hass#200]
## Describe the bug
No more translation after Home Assistant version update: 2023.4.0 

## Version of the custom_component

version": "0.6.1-b4"

## Configuration

```yaml

  sensor_value_translation: local

```

<img width="247" alt="Schermafbeelding 2023-04-06 001110" src="https://user-images.githubusercontent.com/28707705/230223633-e98d32ff-62ab-4f4b-a73e-a6d7922915df.png">
<img width="389" alt="Schermafbeelding 2023-04-06 001150" src="https://user-images.githubusercontent.com/28707705/230223636-03d205b7-d7bb-45c8-b419-8bdb5ff22fa7.png">

**Comment by ekutner** [comment]
Works for me. Try removing the integration from HACS and adding it back again, maybe something got messed up when you upgraded.

**Comment by Rep-Hueman** [comment]
No it won`t work.. 
I've tried everything.

With and without the translation in the configuration

  language: en-GB
  sensor_value_translation: local

**Comment by Krocko** [comment]
I have the same problem.

**Comment by roelvdgun** [comment]
I've just installed the integration, but got a similar problem with the power and operation state of the dishwasher and washing machine

![Screenshot_20230406-184542](https://user-images.githubusercontent.com/42893095/230443506-df70f9ad-ef99-432e-ae01-14627c2e52a9.png)

**Comment by TWuerdemann** [comment]
Same here. I have set up the integration on the last March update. Then I updated the Docker and I have the same issues as the ones above. Thats why I didn't add any further infos.

**Comment by ekutner** [comment]
After changing my language and back I now have the same issue. However, I seem to have the same problem with every translation. For example, trying to add a new integration (any integration, not just this one) all the titles of the fields in the configuration UI are blank. For example, trying the add the AccuWeather integration looks like this:
![image](https://user-images.githubusercontent.com/5628151/230483587-e2ba3f49-0319-40fe-aaaf-872d896aa78e.png)

Can anyone confirm if they are seeing the same thing?
Do you see proper value translations in other **custom** integrations?

**Comment by TWuerdemann** [comment]
I don't have that many custom integrations. But those look okay.
But maybe one of the others has a similar problem. 
There was a change in the HASS component of Home Connect. But from the ticket I cannot see anything connected to this issue.
But if this is an issue for at least several custom integration we should wait for a fix by HASS.
Or someone with the appropriate knowledge could look deeper where that issues comes from and report that to the HASS guys.

**Comment by ekutner** [comment]
The issue with the missing integration config fields' translations seems to be only in the latest dev code, so I'm going to ignore it for now. Since nothing has changed in the integration and since there were a lot of changes related to translations in HA 2023.4, I'm going to report this a bug to the HA team. In the mean while you can roll back to 2023.3.3 but note that in order for it to work again I had to change my language to something else and then back again.

**Comment by ekutner** [comment]
Just for completeness. This issue was the result of a breaking change in the way translation files are used that was introduced in 2022.12 and enforced in 2023.4
