### ISSUE TITLE
Coffee program missing from the translator

### ISSUE THREAD

**Issue by Hyperion5088** [ekutner/home-connect-hass#204]
## Describe the bug
ConsumerProducts.CoffeeMaker.Program.Beverage.CaffeGrande is missing from the translator json files. Please can you add "ConsumerProducts.CoffeeMaker.Program.Beverage.CaffeGrande": "Caffe Grande"

## Configuration

```yaml

Add your configuration here.

```

## Debug log

```text
Paste the exception info here

```

**Comment by Phoenix-DH** [comment]
I have the same issue here.
I was wondering if there is a possibility in the GUI, but I did not get it.

**Comment by ekutner** [comment]
Added, will be included in the next release, whenever that happens.

**Comment by Phoenix-DH** [comment]
Thanks!
