### ISSUE TITLE
Tumble Dryer Sensor no longer working

### ISSUE THREAD

**Issue by ASAujla** [ekutner/home-connect-hass#205]
Firstly, thank you for creating a great integration!

I recently bought a Bosch Series 8 tumble dryer (model number WTX88RH9GB), and I have been using the "Program Process" sensor to fire an automation. Up until recently. This sensor l's value has been "0" while the dryer is running, and then "100" when the drying process has finished. These was never an in-between value, but 0 and 100 were good enough for my automation.

Recently, however, the sensor no longer changes to "100". It stays at "0" even after the drying programme has ended and the Home Connect app has notified me .

I'm not sure what has changed. My dryer has not had a recent firmware update.

Are you aware of anything that may have changed, and what I should do to get the sensor updating again?

Thanks

Amar

**Comment by ASAujla** [comment]
Yes, maybe an API change. What I've found is that the Operation State sensor is (or has recently become?) unreliable. It always shows"Run" while running, but when the drying programme has ended, it only sometimes shows "Finished", sometimes "Ready" and sunshine"Unavailable". I never use a different setting, so there doesn't seem to be any pattern.

**Comment by ekutner** [comment]
You can upload a debug log and I'll try to take a look, it's pretty consistent for me. If you do then please take not of the time when you start and finish the program and when you open the appliance door after it's finished, that will save me some time digging through the log.
