### ISSUE TITLE
Display remaining program time

### ISSUE THREAD

**Issue by kadiusone** [ekutner/home-connect-hass#21]
We got all information but seems the remaining program time is missing (as well as program progress)

The sensor should show how much time is left till the end of the program or a time that will be finished (then it can be recalculated) Also I use it for automation.

I'm using original integration which it serves remaining_program_time sensor the shows time in state "2022-05-25T15:56:45+00:00" that is used to recalculate remaining time
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/52676677/170264971-ba82cb7c-0f20-4683-91b1-4abf1021cb22.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/52676677/170265074-ce73ebd4-6a3e-4831-8696-22de3d74faa5.png">

**Comment by kadiusone** [comment]
Sorry was too quick all seems to be in place (Just reloaded the integration ad it showed up)

**Comment by ekutner** [comment]
In my integration sensors are created dynamically when they are published by the appliance, so when it is loaded for the first time it may not show all the sensor and as you use the appliance with different programs additional sensors will be created automatically, when they are discovered. This way you won't get a bunch of sensors that are not applicable to your appliance like in the built-in integration.

**Comment by kadiusone** [comment]
Perfect, thanks for the answer, working now smoothly.

Thanks for the hard work on this integration.
