### ISSUE TITLE
"error"generic after entering url in home assistant

### ISSUE THREAD

**Issue by Asdrubale1234** [ekutner/home-connect-hass#210]
## Debug log

```text
Paste the exception info here

``I set it correctly following the guide, in fact everything works and I'm also directed to the home connect site the only problem is the one in the picture, I can't show you anything else because the home assistant register doesn't report anything

**Comment by Asdrubale1234** [comment]
<img width="1440" alt="Screenshot 2023-04-27 alle 19 02 45" src="https://user-images.githubusercontent.com/124882577/234939512-ffa8aff3-8e65-4e81-bf33-d8f11740787a.png">
<img width="1440" alt="Screenshot 2023-04-27 alle 19 02 15" src="https://user-images.githubusercontent.com/124882577/234939544-46da3df9-2216-41cb-a6bd-1831d890b888.png">

**Comment by RubenHarms** [comment]
Same for me!

**Comment by RubenHarms** [comment]
The following error has shown in the log file:
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.home-connect.com/security/oauth/token')

**Comment by ekutner** [comment]
look here #207
