### ISSUE TITLE
Door state refrigerator switched (open = closed and vice versa)

### ISSUE THREAD

**Issue by swappie-d** [ekutner/home-connect-hass#214]
## Describe the bug
Door state shows as open, while door is closed and vice versa of my Siemens refrigerator (KI81FHDD0). All other devices I have show a correct door state.  

## Version of the custom_component
Latest.

**Comment by ekutner** [comment]
This is a known issue with the HC API, see a workaround here: #158

**Comment by swappie-d** [comment]
Ah, I didn’t found that issue when searching for it. Thanks.
