### ISSUE TITLE
Missing sensors for Cookit

### ISSUE THREAD

**Issue by tschoiss** [ekutner/home-connect-hass#216]
I currently miss some of the sensor stated here:

![grafik](https://user-images.githubusercontent.com/2073569/180454334-15c31516-9cd5-493e-a445-2d0f4a94bc09.png)

_Originally posted by @nanosonde in https://github.com/ekutner/home-connect-hass/discussions/79#discussioncomment-3206568_

Only "Bosch Cookit - Connected", "Bosch Cookit - Operation State" and "Bosch Cookit - Power State" are available. According to https://api-docs.home-connect.com/events?#availability-matrix there are also a few more available.

**Comment by ekutner** [comment]
See the README about (not) reporting missing sensors without showing that they should actually be there. Events are not related to sensors, sensors are either, program options, statuses or settings.

**Comment by tschoiss** [comment]
According the provided Link (README: "...show either in the logs or in the API documentation that the missing item is actually available...") this should be the data which is available for the Cook-Processor (Cookit)

BSH.Common.Appliance.Connected | CONNECTED |
BSH.Common.Appliance.Disconnected | DISCONNECTED |
BSH.Common.Appliance.Paired | PAIRED |
BSH.Common.Appliance.Depaired | DEPAIRED |
BSH.Common.Root.SelectedProgram | NOTIFY |
BSH.Common.Root.ActiveProgram | NOTIFY
BSH.Common.Option.RemainingProgramTime | NOTIFY |
BSH.Common.Option.ProgramProgress | NOTIFY |
BSH.Common.Setting.PowerState | NOTIFY |
BSH.Common.Status.OperationState | STATUS |
BSH.Common.Event.ProgramAborted | EVENT |
BSH.Common.Event.ProgramFinished | EVENT |

![image](https://user-images.githubusercontent.com/4056790/236297882-f4b61848-5e37-4f34-8c25-9eb10944f8eb.png)
![image](https://user-images.githubusercontent.com/4056790/236297951-d850e460-c512-4fae-ba92-68b79d90efd3.png)

As you can see in the picture, not everything is provided. In my initial post you can see that there were more.

**Comment by ekutner** [comment]
All the data you've shown here is in the sensors you already have. Some sensors are only created when they become available by the API.
