### ISSUE TITLE
Washing machine not recognised - WG56B2A7NL

### ISSUE THREAD

**Issue by 19jm81** [ekutner/home-connect-hass#224]
<img width="293" alt="Scherm­afbeelding 2023-05-14 om 14 39 20" src="https://github.com/ekutner/home-connect-hass/assets/48967897/0437c6e8-e83a-436b-b47b-f9d6e1fce8f4">

Bought a new washing machine, which is not recognised, the official Home Connect integration is recognising the machine, but gives no workable options and keeps being offline, so would like to use Home Connect Alt with my new machine.

Hope this can be fixed...

## Configuration

```yaml

Add your configuration here.

```

## Debug log

```text
Paste the exception info here

```

**Comment by ekutner** [comment]
Open a new issue and follow the submission instructions
