### ISSUE TITLE
Question: Connectivity to Homeassistant when using this integration?

### ISSUE THREAD

**Issue by edautz** [ekutner/home-connect-hass#228]
I got some new kitchen equipment from Siemens with Homeconnect capability and want to integrate this to Homeassistant.

My homeassistant setup is not exposed to the Internet and only reachable local or with an OpenVPN connection.

This integration seems to have more functionality then the offical one.

Is it possible to use this integration pure locally? And use local private IP addresses in the call back url in the Homeconnect dev portal? This would be my preferred solution.

Or have I to setup something like a NGINX reverse proxy to grant Internet access?

**Comment by d0np3p3** [comment]
Just put your local homeassistant IP in here: 
https://my.home-assistant.io/
It will work local, no need for any ngix or cloudflare or nabucase.

**Comment by edautz** [comment]
Ok. Thanks. Is it also possible to use http instead of https for the link in your answer?

**Comment by edautz** [comment]
Unfortunately, the above mentioned link doesn't work. I used http://192.168.2.x:8123/redirect/oauth as my redirect URI, and it worked at once.
