### ISSUE TITLE
Add service for issuing a Pause command for washers and driers.

### ISSUE THREAD

**Issue by nunomcruz** [ekutner/home-connect-hass#229]
Official support has a pause command that doesn't distinguish between appliance types. For certain appliances a pause command is available, for example for clothes washers and dryers.

I think it would be useful to provide such service also in your integration.

**Comment by ekutner** [comment]
Good idea. Added in version 0.6.3. Note that I can't test it on my appliance but it should work, assuming your appliance allows pausing and resuming through the API. If it doesn't work then press the "Home Connect Debug" button and upload the log file.
