### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by canedje** [ekutner/home-connect-hass#23]
Variables of for example: "selected program" is showing a long variable as answer. For example:
"Dishcare.Dishwasher.Program.Auto2"
I like to show the values in my automation. In this case Auto 2.
Now I need to do a string handling to achieve this
Is this possible to change in only the activity?
Or create an attribute with that value?

(By the way, nice integration, it looks like more reliable!!)

**Comment by ekutner** [comment]
All the drop down boxes are using the raw enum values and rely on local translations to display a friendly value. However, there are a lot of undocumented values that the service is using so if you see them please provide the exact value and a friendly name and I'll add them to the next release.

**Comment by canedje** [comment]
Thank you for your answer.
The most of the entities having a very long value, with several dots in it:
![image](https://user-images.githubusercontent.com/23150947/170888874-30927907-937b-4a96-9f29-2415e933f3a1.png)
The only value needed is in this case: Eco50
In the device overview teher are shown the right values, but I can not find these values back somehow:
![image](https://user-images.githubusercontent.com/23150947/170888921-9345bee8-936d-497e-8c2c-f911df3224b2.png)
If it is possible to find these values back somehow in the entity would be very nice

**Comment by ekutner** [comment]
I'm closing this issue in favor of #26 where this is discussed and explained.
