### ISSUE TITLE
Power Off Washing Machine, Dryer

### ISSUE THREAD

**Issue by romerod** [ekutner/home-connect-hass#230]
I've a dryer and washing machine which I can both Power off vía the official Home Connect app, but there is no such button in HASS.

Hope this is not a duplicate, tried to find a matching issue.

**Comment by ekutner** [comment]
Please read the README and instructions for reporting issues. The mobile app is using an internal API and can do things that are not supported in the public API. If you think this should be possible you need to indicate which API supports it but if there was one it would have been added automatically by the integration.
