### ISSUE TITLE
Device name and entity name should match

### ISSUE THREAD

**Issue by MichelFR** [ekutner/home-connect-hass#232]
As you can see below its the current state because in this case because the device is called "Kaffeevollautomat" and the entities are called "Siemens Kaffeevollautomat - ..." the string does not show the shorted version.

Currently:
<img width="868" alt="image" src="https://github.com/ekutner/home-connect-hass/assets/7061122/45d0a934-cefc-48da-9c68-aa807c21cf2a">

And how it would be with matching entity names:
<img width="860" alt="image" src="https://github.com/ekutner/home-connect-hass/assets/7061122/e9975970-4c6c-4f92-901c-33c0e40ee206">

**Comment by ekutner** [comment]
It's a matter of taste, I don't like this truncation. You can get that behavior by using the ```name_template``` config parameter.
