### ISSUE TITLE
how to uninstall this add-on?

### ISSUE THREAD

**Issue by iniciante** [ekutner/home-connect-hass#234]
I have installed after the other add-on, that doesn't work: "home-connect". 

I have cleaned credentials but no way, when I start the home-connect-alt it says configuration is not done -I have no option to introduce the configuration- I think the way to solve is uninstall and again install.
Thanks.

**Comment by ekutner** [comment]
To install and configure follow the instructions in the README.
You uninstall it like any other integration.
