### ISSUE TITLE
Remaining program time always shows "not available"

### ISSUE THREAD

**Issue by RetroButton** [ekutner/home-connect-hass#249]
I´m using Home Connect Alt for quiet a time now.
But it was never able to display the value "remaining program time".
This value always shows "not available".
Every other entity works fine.

## Version of the custom_component
Newest / 0.6.5

![Bosch](https://github.com/ekutner/home-connect-hass/assets/69696087/7737c9ee-38c2-432a-8f48-bd728cb4f887)

**Comment by ekutner** [comment]
Entities are created dynamically when their values are provided by the API. However, I've seen multiple cases in which values were provided for a while and then stopped. To verify, press the "Home Connect Debug Info" button while a program is running and upload the full log file.

**Comment by knuser666** [comment]
Hi
Got The same error

**Comment by knuser666** [comment]
Siemens Opvaskemaskine - Remaining Program Time  changed to September 22, 2023 at 20:11
16:14:45 - Now

Siemens Opvaskemaskine - Remaining Program Time  changed to September 22, 2023 at 20:11
16:13:46 - 1 minute ago

Siemens Opvaskemaskine - Remaining Program Time  changed to September 22, 2023 at 20:11
16:12:47 - 2 minutes ago

**Comment by RetroButton** [comment]
Installed the latest release these days, still not working.
Debug log attached. Should contain the start and some minutes running the dishwasher.
[home-assistant_home_connect_alt_2023-09-23T12-51-05.259Z.log](https://github.com/ekutner/home-connect-hass/files/12706466/home-assistant_home_connect_alt_2023-09-23T12-51-05.259Z.log)

**Comment by mario-pranjic** [comment]
Hi,
I noticed the same thing: very often I get "Program Progress" for washing machine unavailable, along with some other parameters. Can't  conclude any pattern when that happens. 
![home_conn_err](https://github.com/ekutner/home-connect-hass/assets/22792875/2fdee981-5f2d-4fe1-b8b7-112cc93c6182)

**Comment by RetroButton** [comment]
Same thing here. Will get back with a hopefully correct logifle when running the dishwasher next time.

**Comment by mario-pranjic** [comment]
Example of bright moments when things just work. Have no idea what triggers it (nor what brakes it)
![image](https://github.com/ekutner/home-connect-hass/assets/22792875/6bde0a55-47fa-482e-bcb8-097189082b84)

**Comment by RetroButton** [comment]
Crazy. Yesterday it displayed all data for my installation too. Waiting for the next dishwashing....

**Comment by RetroButton** [comment]
Back again, with the newest logfile.
Has happend again, no remaining time.
[home-assistant_home_connect_alt_2023-09-27T17-51-51.630Z.log](https://github.com/ekutner/home-connect-hass/files/12741874/home-assistant_home_connect_alt_2023-09-27T17-51-51.630Z.log)

**Comment by ekutner** [comment]
@RetroButton The program started at 19:21:45 and the log shows there were progress reports and updated to the remaining program time every minute until the end of the log at 10% progress and 17640 seconds remaining program time.

**Comment by RetroButton** [comment]
And here is what is display inside HA...
<img width="449" alt="2023-09-27 21_43_38-Übersicht – Home Assistant und 2 weitere Seiten - Persönlich – Microsoft​ Edge" src="https://github.com/ekutner/home-connect-hass/assets/69696087/50424997-e5b9-4db1-977f-757d60589dba">

**Comment by ekutner** [comment]
are you saying that these are the only entities you see? what do you see if you go to the states page under developer tools and filter by your appliance HAID (search the README if you don;t know how to find it).

**Comment by RetroButton** [comment]
Actually i have a programm running.
These are the entities i see in the dev options. (screenshot attached)
<img width="1224" alt="2023-10-02 12_59_58-Entwicklerwerkzeuge – Home Assistant und 2 weitere Seiten - Persönlich – Microso" src="https://github.com/ekutner/home-connect-hass/assets/69696087/a4295cc2-b6cc-41f9-8a01-b63145478cbe">

**Comment by ekutner** [comment]
Please install version 0.6.8
Then add ```log_mode: 7``` to the home_connect_alt section of your configuration.yaml file.
Then restart, run a program again and upload the full log file.

**Comment by jensrossbach** [comment]
I have the same problem for my Bosch dishwasher since a couple of days. Before it worked fine, but now, remaining program time as well as the selected program are shown as unavailable.

**Comment by RetroButton** [comment]
I´m not 100% sure, but it seems to work for one time after restarting Home Assistant.
Started our dishwasher today, and it magically works (after updating HA to the current release).
<img width="697" alt="2023-10-04 22_35_23-Übersicht – Home Assistant und 1 weitere Seite - Persönlich – Microsoft​ Edge" src="https://github.com/ekutner/home-connect-hass/assets/69696087/93289ec8-88f6-4ddf-850f-da47bcc6018f">

**Comment by ekutner** [comment]
Configure the logging as instructed and upload the log when it happens again.

**Comment by RetroButton** [comment]
Today it has happend again.
Strange enough, the last 2 runs were working, and the remaining time was displayed.
![Auswahl_004](https://github.com/ekutner/home-connect-hass/assets/69696087/138b96c4-7540-4117-99d9-4aa115ba52db)
[home-assistant_home_connect_alt_2023-10-15T14-04-46.396Z.log](https://github.com/ekutner/home-connect-hass/files/12909859/home-assistant_home_connect_alt_2023-10-15T14-04-46.396Z.log)

**Comment by ekutner** [comment]
@RetroButton This doesn't seem to use the latest version as I don't see some debug messages I expected to see. From the log I can't say why this issue is happening. The log shows the "RemainingProgramTime" event being received until the log ends with 7620 seconds remaining. So at least according to the log it should have worked...

**Comment by RetroButton** [comment]
I absolutely have the latest version.
HACS does not show me a newer version than 0.6.8. This is the version i run actually.

**Comment by ekutner** [comment]
> I absolutely have the latest version. HACS does not show me a newer version than 0.6.8. This is the version i run actually.

You're right, I missed it with all the clutter in the log. Please add ```log_mode: 7``` to the home_connect_alt section in configuration.yaml then restart and wait for the issue to happen again. When it does happen press the "Home Connect Debug" button (created by the integration in the HA UI). And upload the log again.

**Comment by reentier** [comment]
Hello,
 i do have the same problem with the dishwasher and the oven. I figured out that the entitys are available when the devices are running during the start of the add-on. If i start the devices after starting the add-on/HA a simple reload of the add-on helps to get the entitys back.

Now i only have to figure out how to automaticly restart the add on after the start of one of the devices.

**Comment by ekutner** [comment]
This is very helpful and helps me confirm and issue I suspected already and wanted to confirm with the logs. I'll have a fix soon.

**Comment by ashwin2101** [comment]
> Hello, i do have the same problem with the dishwasher and the oven. I figured out that the entitys are available when the devices are running during the start of the add-on. If i start the devices after starting the add-on/HA a simple reload of the add-on helps to get the entitys back.
> 
> Now i only have to figure out how to automaticly restart the add on after the start of one of the devices.

Thank you that solved also my problem :)

**Comment by ekutner** [comment]
Please try version 0.7.0-b1 and let me know if it fixes the issue. Note that it is a beta release with some other changes and may have issues.

**Comment by reentier** [comment]
What is expected behaviour in this version? After installation all the requested entities are unavailable. But at the moment all the devices are in standby. Should the entities become available if one of the devices are started?

regards

**Comment by reentier** [comment]
Hi,

i can confirm that the entities are getting available when the dishwasher is started. There was no time to test the behaviour of the oven, but the dishwasher is fine now.

Thanks for the adjustment.

**Comment by reentier** [comment]
Hi again,

The issue is still existing for the remaining time of the oven. 

<img width="363" alt="image" src="https://github.com/ekutner/home-connect-hass/assets/77726631/b6a0e672-2394-4778-a402-c41e5d4c45ea">

I can see the progress, but not the remaining time.

**Comment by reentier** [comment]
> Hi again,
> 
> The issue is still existing for the remaining time of the oven.
> 
> <img alt="image" width="363" src="https://user-images.githubusercontent.com/77726631/278615427-b6a0e672-2394-4778-a402-c41e5d4c45ea.png">
> I can see the progress, but not the remaining time.

The Problem is that the Program Timer appears later then the rest of the entities. This entity is not available during pre-heating. If i reload the add-on after starting the timer on the device the entity becomes visible. I think it will be helpful if the add-on reloads the api after the progress jumps from 100% to 1 %.

regards

**Comment by ekutner** [comment]
@reentier Please try the latest build (b4).

**Comment by reentier** [comment]
I can confirm that it is working with this version.

**Comment by ekutner** [comment]
Great, thanks for the update.
