### ISSUE TITLE
Many entities lost after update to 0.6.5

### ISSUE THREAD

**Issue by davidepanato** [ekutner/home-connect-hass#256]
## Describe the bug
Many entities have been lost when I switched from 0.6.3 to 0.6.5.
As an example I lost the "program progress progress" for my dishwasher and oven (running perfectly on 0.6.3)
Before the update total entities --> 59
After update --> 35

## Version of the custom_component
0.6.5

## Configuration

home_connect_alt:
  client_id: !secret HC_CLIENT_ID
  client_secret: !secret HC_CLIENT_SECRET

## Debug log
[home-assistant_home_connect_alt_2023-09-18T12-32-27.827Z.log](https://github.com/ekutner/home-connect-hass/files/12647737/home-assistant_home_connect_alt_2023-09-18T12-32-27.827Z.log)

**Comment by ekutner** [comment]
The integration doesn't remove entities. Did you uninstall and reinstalled it? If you did, those entities will be added gradually, when they have some data to report. So the progress entity will show after you use the dishwasher once. If you didn't remove the integration then please explain what you means when you say that entities have been lost. Are they disabled on something else?

**Comment by davidepanato** [comment]
After installing 0.6.5 many entities appeared as unavailable and "no more provided by the integration". Even by using the dishwasher they did not appear. I noticed it since one automation that uses the program progress entity failed to execute.
Today i tried to completely remove and reinstall the integration and only 35 entities were available.

**Comment by ekutner** [comment]
If you restart HA then some entities will show up as unavailable until they have data to show. Are you that is not what happened?
If you are sure then I'm going to need you to do the following:
1. Enable debug logging (see how in the README)
2. Add ```log_mode: 7``` to the home_connect_alt configuration
3. Run a program on the dishwasher and while it is running press the "Home Connect Debug Info" button.
4. Upload the full log file.
5. Roll back to ver, 6.0.3 and repeat the above steps.

**Comment by davidepanato** [comment]
After a week sensors appeared again and now they're working. Don't know what happened but now it seems fixed, thanks for your support!
