### ISSUE TITLE
Blank screen after Link account. When refreshing the page a 500 error shows up faded in the background.

### ISSUE THREAD

**Issue by morton027** [ekutner/home-connect-hass#267]
Upon linking of account to the integration, after following all instructions to the letter, all I get is a blank page after attempting to link the account.

I currently have the 'main' Homeconnect integration installed, but that is needed unless this one works better for me. I have tried temporarily disabling it while installing this one, to no avail.

Any suggestions for a fix, or reason that it won't install correctly?

**Comment by Rogi1997** [comment]
That's because it' wants to open the accept link in the home-assistant mobile App.

I've disabled the app, then linked the account and then enabled the android app again

**Comment by morton027** [comment]
> That's because it' wants to open the accept link in the home-assistant mobile App.
> 
> 
> 
> I've disabled the app, then linked the account and then enabled the android app again

Mind if I ask how you disabled the app? Just tried signing out and that didn't work, do I have to delete it from my device?

**Comment by morton027** [comment]
I've tried deleting the app, it just comes up with an error in Safari then. Hmm not promising.
