### ISSUE TITLE
Changing to use local connection rather than Cloud API

### ISSUE THREAD

**Issue by ouchkilljoys** [ekutner/home-connect-hass#271]
**Is your feature request related to a problem? Please describe.**
Using the local API will overcome a limitation [ekutner](https://github.com/ekutner) has described
- API Rate limit 1000 per 24 hours

**Describe the solution you'd like**
The ability to use either the Cloud or Local API to control devices, it seems some work has already been done on a python library that can do that, but I guess integrating it into Home Assistant would be the next thing. 

https://github.com/osresearch/hcpy

**Additional context**
The other repo does mention is still in beta but it might provide some insight into do local requests rather than cloud api requests

**Comment by ekutner** [comment]
That library is far from complete and obviously not supported. I have no plan to use it in the foreseeable future.

**Comment by ann0see** [comment]
Also interested in a local integration. Very positive that it could in theory work.

**Comment by wachino** [comment]
Any news on this?

**Comment by andyearnshaw** [comment]
> That library is far from complete and obviously not supported. I have no plan to use it in the foreseeable future.

There's a newer fork which is receiving regular updates, most recently last week.

https://github.com/hcpy2-0/hcpy
