### ISSUE TITLE
LaundryCare.Washer.EnumType.Temperature.GC40

### ISSUE THREAD

**Issue by jatty** [ekutner/home-connect-hass#273]
together with my old Bosch washing machine form 2016 i get a specific field:

bosch_wayh2890_68a40e011dc4_laundrycare_washer_option_temperature

the following value into Home Assistant:

LaundryCare.Washer.EnumType.Temperature.GC40

From my point of view this is a bug. I would expect only a value like 40.

**Comment by ekutner** [comment]
Where exactly do you get that value?

**Comment by jatty** [comment]
It's not reproducable now. This was an effect right after installation of the module.
Now there are normal temperature values at the same place.

**Comment by ekutner** [comment]
sounds like a HA issue since it relies on the built-in translation mechanism. I'm going to close this now.
