### ISSUE TITLE
No appliances found

### ISSUE THREAD

**Issue by kellyatkinson** [ekutner/home-connect-hass#282]
## Describe the bug
I installed this custom component a couple of weeks ago after getting tired of all the spurious entities in the original Home Connect integration. I have the Home Connect developer information working correctly; I know it works because I had the original Home Connect integration working fine. My devices all correctly connect to Home Connect as tested on my phone with no wifi. However, this custom component hasn't found any of my devices. It looks like it is correctly configured so I'm not sure what to try next. 

## Version of the custom_component
0.7.0

## Configuration

```yaml
home_connect_alt:
  client_id: !secret hcclientid
  client_secret: !secret hcclientsecret
```

## Debug log
No exceptions found AFAIK. Attached.
[home-assistant_home_connect_alt_2023-11-06T06-42-43.372Z.log](https://github.com/ekutner/home-connect-hass/files/13263379/home-assistant_home_connect_alt_2023-11-06T06-42-43.372Z.log)

**Comment by ekutner** [comment]
The API doesn't return any appliances.
Are you sure you configured the same test user account in the Home Connect developer app as the one you are using in you mobile app?
If you are sure then please:
1. attach a screenshot of the developer app settings.
2. add ```log_mode: 7``` to the home_connect_alt section in the configuration.yaml file.
3. remove and re-add the integration and upload a new log.

**Comment by kellyatkinson** [comment]
I signed out of my Home Connect account (now Single-key, not confusing at all) and signed in very carefully. I also created a new HC Developer application and connected to that. Now all my appliances are found correctly! Thank you!
