### ISSUE TITLE
stuck in installing with a bad client id/secret in conf

### ISSUE THREAD

**Issue by gsemet** [ekutner/home-connect-hass#292]
Hello

i did a mistake during the installation and removed the application on the bosch server during the install. now, i cannot reexecte the complete integration setup assistant, even when i restart home assistant or remove/add your integration. it directly opens to the dialog "Link Home Connect Account" and then open a tab with this error:
```
{
  "error": "unauthorized_client",
  "error_description": "request rejected by client authorization authority (developer portal)",
  "state": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbG93X2lkIjoiNDNlZGU3MjlmZjUyZWY2MTU1ZWM2MjBiMjEzYzM5NzMiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL215LmhvbWUtYXNzaXN0YW50LmlvL3JlZGlyZWN0L29hdXRoIn0.uh85KHBzNhnrVXHA0XL9aKlf54mQyY1m28CfwQVRYPc"
}
```
i simply need to clear somehow the client id/server that are wrong, but i don't know where HA stores it

thanks

**Comment by ekutner** [comment]
It's actually the first item in the FAQ

**Comment by gsemet** [comment]
indeed sorry !
