### ISSUE TITLE
0.7 automation

### ISSUE THREAD

**Issue by razzietheman** [ekutner/home-connect-hass#297]
from 0.7 to 1.0.0 I have an automation that sends out amessage when the washmachine is finish it looks like this
  id: Tvattnotis
  alias: Tvättnotis
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bosch_wau28pehsn_68a40e5d595e_bsh_common_status_operationstate
    from: Running
    to: Completed
  condition: []
  action:
  - service: tts.speak
    data:
      media_player_entity_id: media_player.hemgrupp_2
      message: Hej! Vill bara meddela att tvätten är färdig och det är nu dags att hänga upp den på tork
    target:
      entity_id: tts.google_sv_se
  mode: single

but now in 1.0.0 it won't work anymore so whats the new From & to?

**Comment by ekutner** [comment]
You probably had server translation enable in the config.  In v. 1.0.0 you need to select that translation mode in the integration configuration options in the UI.

**Comment by razzietheman** [comment]
> You probably had server translation enable in the config. In v. 1.0.0 you need to select that translation mode in the integration configuration options in the UI.

yes I have that in configuration.yaml with the client ID & client secret , so just remove the other and fix it in the UI? but keep client ID & client secret?
