### ISSUE TITLE
Which breaking changes in 1.0.0?

### ISSUE THREAD

**Issue by emufan** [ekutner/home-connect-hass#298]
I'm afraid to do the update now, because I saw "This is a major release with breaking changes".

But perhaps I missed the thing, but I do not see breaking changes listed in the notes.

Which breaking changes are in 1.0.0? So what is breaking, needs manual rework or whatever else?

**Comment by ekutner** [comment]
The breaking changes are related to the configuration. You may have to configure it in the UI. See the README for how to do that.

**Comment by ekutner** [comment]
"May" as in it should work but wasn't tested so you can try and see.
