### ISSUE TITLE
no way to complete the Oauth flow

### ISSUE THREAD

**Issue by kpm4** [ekutner/home-connect-hass#300]
## Describe the bug

I just got a bosch induction hob, registered on Home Connect and all is working on the app, so I am trying to integrate with HA, then I created a developer account on HC, created a new application and tried to install the HC integration on HA.
I still get the "error": "unauthorized_client", I tried to logout from developer portal, tried with another browser, disabled default_config, but without any luck, I am using duckdns to access my HA from internet and used my public domain as URI on Home Connect.
the redirect URI configured is: https://<mydomain>.duckdns.org:<myport>/auth/external/callback , also tried with http://my.home-assistant.io/auth/external/callback , but still no luck.

What I noticed from the error, decoding the jwt token I still see the call to /redirect/oauth instead of /auth/external/callback ,

## Version of the custom_component

1.0.0

## Debug log

```text
Paste the exception info here or attach the full log file

```

**Comment by dennypage** [comment]
Just one quick thing I saw... the host name in your duckdns.org URL starts with a period, which is invalid.

**Comment by ekutner** [comment]
Apologies but I don't have the capacity to help with authentication issues. Those issues are ALWAYS the result of not following the setup instructions. If you can't figure it out yourself you can try asking in the discussion forum. One thing I can say with a quick look is that you should use the exact redirect URI as specified in the instruction.

**Comment by ns-gcutolo** [comment]
sorry, it was a typo in the issue text, I am using as URI https://MYDOMAIN.duckdns.org:MYPORT/auth/external/callback , 
I can understand that the auth issue is not something that you would like to fix, but just a question, is it normal that in the JWT token there is always the url  http://my.home-assistant.io/redirect/oauth even if I configure my own domain in the URI?

**Comment by kpm4** [comment]
sorry, it was a typo in the issue text, I am using as URI https://MYDOMAIN.duckdns.org:MYPORT/auth/external/callback ,
I can understand that the auth issue is not something that you would like to fix, but just a question, is it normal that in the JWT token there is always the url http://my.home-assistant.io/redirect/oauth even if I configure my own domain in the URI?
