### ISSUE TITLE
Dishwasher NEFF S157ZBX01D via App downloaded Programms unknown in Integration

### ISSUE THREAD

**Issue by nireins** [ekutner/home-connect-hass#303]
Hi,
my dishwasher supports downloading programs via the HOME CONNECT APP. Some of these programs cannot be translated or displayed.

Would it be possible to maintain/correct these?

Here are the programs:

- Dishcare.Dishwasher.Program.MixedLoad -> (in HOME CONNECT show as in German: Mischbeladung)

- Dishcare.Dishwasher.Program.QuickD -> (in HOME CONNECT show as in German: Quick Wash&Dry)

- Dishcare.Dishwasher.EnumType.LearningDishwasher.DurationLevel.Level0 -> (in HOME CONNECT show as in German: Intelligent)

Thanks.

**Comment by ekutner** [comment]
In general, if you know how to submit a PR it's better to do that.
I added the two programs, although the second one seems to have a partial value (are you sure it really ends with "QuickD" ?).
For the last one it's not clear what category it belongs to so I didn't add it. It, also looks like there should be other values of the same group (other than "DurationLevel" and other levels except Level0 within the DurationLevel).

**Comment by nireins** [comment]
> In general, if you know how to submit a PR it's better to do that.
Unfortunately I don't know what you mean by that exactly?

> I added the two programs, although the second one seems to have a partial value (are you sure it really ends with "QuickD" ?).
<img width="1182" alt="Bildschirmfoto 2023-12-22 um 06 41 22" src="https://github.com/ekutner/home-connect-hass/assets/69728116/023e5032-8d9c-4fd2-86ef-048ab5b1e039">
<img width="1182" alt="Bildschirmfoto 2023-12-22 um 06 43 55" src="https://github.com/ekutner/home-connect-hass/assets/69728116/1d63b533-74e5-47ff-84b3-bc72d15cf4db">


> For the last one it's not clear what category it belongs to so I didn't add it. It, also looks like there should be other values of the same group (other than "DurationLevel" and other levels except Level0 within the DurationLevel).
<img width="1182" alt="Bildschirmfoto 2023-12-22 um 06 44 37" src="https://github.com/ekutner/home-connect-hass/assets/69728116/b3f10a70-cdd2-48a0-80f3-9c538fa18a6b">

> For the last one it's not clear what category it belongs to so I didn't add it. It, also looks like there should be other values of the same group (other than "DurationLevel" and other levels except Level0 within the DurationLevel).
In fact, unfortunately I don't know either. I'll just show you what values ​​the sensor shows.

The last picture shows the selection in the HOME CONNECT APP.
![IMG_1129](https://github.com/ekutner/home-connect-hass/assets/69728116/44ca01fe-af0e-4084-95c6-7cb86afa3250)

I hope this helps you further.

**Comment by ekutner** [comment]
So this confirms the two program keys are correct but doesn't help with the third value.
Where do you see this one: Dishcare.Dishwasher.EnumType.LearningDishwasher.DurationLevel.Level0

**Comment by nireins** [comment]
> Where do you see this one: Dishcare.Dishwasher.EnumType.LearningDishwasher.DurationLevel.Level0

here:

<img width="2133" alt="Bildschirmfoto 2023-12-23 um 10 28 16" src="https://github.com/ekutner/home-connect-hass/assets/69728116/52c5a94f-07f7-44f6-9a0d-4deec1cee75c">
<img width="2133" alt="Bildschirmfoto 2023-12-23 um 10 29 11" src="https://github.com/ekutner/home-connect-hass/assets/69728116/670b51d9-58c9-4e09-9bf5-a0ff4e091493">
<img width="2133" alt="Bildschirmfoto 2023-12-23 um 10 29 46" src="https://github.com/ekutner/home-connect-hass/assets/69728116/c67cc248-03ff-43d5-9d3a-ea1925bd44da">

**Comment by ekutner** [comment]
ok, so these values belong to program options (because the sensor ID has "option" in it). I assume there must be other levels beyond Level0, can you change these options either on the dishwasher itself or in the HC app so they get other values? Then for each value indicate what is it's English and German display value. 

P.S. Note that these three are not the same. In your original issue report you only noted one of them (DurationLevel).

**Comment by nireins** [comment]
In fact, I can't make any settings on the device or in the HC app to get from Level0 to Level1, for example.

According to the operating instructions, I as a user can evaluate the dishwasher results after each washing program using the “Intiligent” button.

However, I haven't tested it yet to see exactly how it behaves.

I observe and report.

Yes, I saw that it involves multiple sensors.
In my original post I actually specified a sensor "option" instead of the sensor "selected".

**Comment by wuast94** [comment]
I would also like to add the intelligent program.

Explanation, the learning (displayed as Intelligent) program is a program of dishwasher that is mainly sensor controlled (i guess). so it runs once, then you can rate 3 categories (Dry,Clean,Time), based on the rating it tunes the program. 

This is the main program: `Bosch Geschirrspüler - Selected Program changed to Dishcare.Dishwasher.Program.LearningDishwasher` 

And this are the 3 categories you can rate after a dishwascher program (in app with stars from 1-5) and based on this it sets these levels i guess:
```
Bosch Geschirrspüler - Duration Level changed to Dishcare.Dishwasher.EnumType.LearningDishwasher.DurationLevel.Level0
Bosch Geschirrspüler - Drying Level changed to Dishcare.Dishwasher.EnumType.LearningDishwasher.DryingLevel.Level2
Bosch Geschirrspüler - Cleaning Level changed to Dishcare.Dishwasher.EnumType.LearningDishwasher.CleaningLevel.Level3
```

hope i could make this topic a bit more understandable 😊

**Comment by ekutner** [comment]
OK, I've added these translation in English. It will be included in the next release but obviously I can't test them so can't say for sure if they work or not.

**Comment by wuast94** [comment]
> OK, I've added these translation in English. It will be included in the next release but obviously I can't test them so can't say for sure if they work or not.

I will give Feedback 😊 BTW im open if you want to test with my installation 😊

**Comment by sweti3** [comment]
Will there also be a german language? Or how to change that? Thanks!

**Comment by ekutner** [comment]
someone who speaks German should update the translation files. Or you can try changing the settings to use Server Translation.

**Comment by wuast94** [comment]
@ekutner sry for late reply, the three sensor are working fine. But i cant select the program. if i select it in the app i see `Bosch Geschirrspüler - Programs became unknown`

`sensor.*numbers*__selected_program` is Dishcare.Dishwasher.Program.LearningDishwasher

**Comment by ekutner** [comment]
That means the program can't be selected using the API. There is nothing I can do about that but you can try to submit a request to HC support and ask them to add it to the API. 
Since the translation is working I'll go ahead and close this issue now.
