### ISSUE TITLE
Proces fase shows : LaundryCare.Common.EnumType.ProcessPhase.FillingDetergent

### ISSUE THREAD

**Issue by Mitch73-2** [ekutner/home-connect-hass#305]
Hello Ekutner,

Yesterday I saw the following log of the process phase:
- LaundryCare.Common.EnumType.ProcessPhase.FillingDetergent

So I was wondering if this is something new?
I have included a photo for more clarity
<img width="453" alt="Scherm­afbeelding 2023-12-28 om 15 25 52" src="https://github.com/ekutner/home-connect-hass/assets/76648341/25b59f0b-5a38-406f-a835-d09e4a1f4b1d">

Thank you in advance for your hard work in improving and maintaining this integration

**Comment by ekutner** [comment]
Sorry but I don't understand what is the issue

**Comment by Mitch73-2** [comment]
It's not a problem but rather a question, sorry if I wasn't clear.

When I look at the translation, I don't see "LaundryCare.Common.EnumType.ProcessPhase.FillingDetergent" there, but I do see it in HA.

My question was actually, is this a new ProcessPhase that might need to be added to translation?

**Comment by ekutner** [comment]
Probably. The integration creates HA entities automatically when they are exposed by the HC API, I don't know in advance which entities are exposed by every appliance out there. The bottom line is that if the translation is missing then it should be added.

**Comment by Mitch73-2** [comment]
I'll keep an eye on what other entities are exposed in the washer process phase.
This week I am also getting a new Bosch dryer which also has Home Connect, so I will also keep an eye on that.

Would it perhaps be useful if I then create a Feature request with the entities found?

**Comment by ekutner** [comment]
Feature request is good, pull request is even better
