### ISSUE TITLE
AutomationActionType and AutomationTriggerInfo are deprecated

### ISSUE THREAD

**Issue by ErikvO** [ekutner/home-connect-hass#309]
Home assistant shows warning messages in the log (presumably since 2024.1.0):

- AutomationActionType was used from home_connect_alt, this is a deprecated constant which will be removed in HA Core 2025.1. Use TriggerActionType instead, please create a bug report at https://github.com/ekutner/home-connect-hass/issues
- AutomationTriggerInfo was used from home_connect_alt, this is a deprecated constant which will be removed in HA Core 2025.1. Use TriggerInfo instead, please create a bug report at https://github.com/ekutner/home-connect-hass/issues

I used the latest version (as of now) of Home Connect Alt: 1.0.1

**Comment by ekutner** [comment]
@ErikvO Should be okay now. Thank you for reporting!

**Comment by ErikvO** [comment]
Thanks! It seems to work fine indeed: no more warnings in the log.
