### ISSUE TITLE
Coffeemaker TQ907DF5 new Entities // Time remaining for Clean&Calc, cleaning, water filter

### ISSUE THREAD

**Issue by nireins** [ekutner/home-connect-hass#310]
Hi, my new Coffeemaker Siemens TQ907DF5 shows some Entities which not translate in German:

sensor.712090391305001508_consumerproducts_coffeemaker_option_coarsness
This Sensor shows these state:
ConsumerProducts.CoffeeMaker.EnumType.CoarsnessExtended.Coarsness3
(Coarsness3 -> Coarsness1-6) in German -> "Mahlgrad" from "Stufe 1" to "Stufe 5"

sensor.712090391305001508_consumerproducts_coffeemaker_option_coffeestrength
This Sensor shows:
ConsumerProducts.CoffeeMaker.EnumType.CoffeeStrength.Strength5
(Strength5 -> Strength1-9) in German -> "Stärke" from "1" to "9"

Can you please include these entries in your integration?

In the Home Connect app I can see how many cups can still be brewed before the water filter needs to be changed. Among other things, until a cleaning is due and when Clean&Calc is due. See screenshot.

![IMG_1164](https://github.com/ekutner/home-connect-hass/assets/69728116/c1e9a9fc-3108-4210-b631-12c0bcd4c6c8)

Can you somehow incorporate this into the integration? That would be super helpful. thx

**Comment by nireins** [comment]
Hi, thank your for that. 

Here are the 2 Files with my changes. (worked in my Home Assistant.)

[de.json](https://github.com/ekutner/home-connect-hass/files/13945934/de.json)
[en.json](https://github.com/ekutner/home-connect-hass/files/13945936/en.json)


> And there is nothing I can do about the other missing entities. The integration automatically exposes all the information which is available through the HC API as sensors or events so if it's not already there it means that the API doesn't expose that information. The mobile app is using an internal API which is not available to external application so it may show information that the integration doesn't have access to.

Ok, i understand. Thank yout for your comment.

**Comment by ekutner** [comment]
Thanks. I've merged the new options but you duplicated existing program keys in the wrong place so removed those.
These changes will be included in the 1.0.3 release so when you see that available (could take some time), please verify that it is still working. I will keep this issue open until then.

**Comment by ekutner** [comment]
Please update to 1.1.0-b3 or later (if it will be available) and verify that the translation works as expected.

**Comment by ekutner** [comment]
I'm going to assume the translation is fine and close this issue. Feel free to open a new one if it's not working as expected.
