### ISSUE TITLE
Microwave functions

### ISSUE THREAD

**Issue by tgilis** [ekutner/home-connect-hass#313]
First of all, thanks for creating add-on.

I have a combination Microwave and Oven from NEFF. While I get to select all the Oven options through the add-on none of the Microwave functions are available. This is basic functions (Wattage, Duration) but they are not there. Is that something you could add ? I can control them through the normal app (see screenshot)

![IMG_0275](https://github.com/ekutner/home-connect-hass/assets/24375231/5802f319-3f71-4d9b-a686-a81e36991b97)

**Comment by ekutner** [comment]
Nothing I can do about it. The integration automatically exposes in HC all the programs and options that are made available by the API. If it's not there then the API doesn't give access to it. It might be a good idea to report this to Home Connect and hopefully they will add support for it.

**Comment by tgilis** [comment]
Fingers crossed - 
![image](https://github.com/ekutner/home-connect-hass/assets/24375231/134c0e69-c630-44f3-9b91-62d45ee4bce1)
