### ISSUE TITLE
Energy consumption dishwasher forecast

### ISSUE THREAD

**Issue by cyberoner1** [ekutner/home-connect-hass#316]
Hi, it is not really a request, more a question.

I have a siemens dishwasher and saw the point energy consumption forecast and water consumption forcast with % values in. Can you tell me to which sensor the % are refering, too? I am interested to find out how much energy and water my dishawasher is using so I thought I can calculate this when I know the fields

Thanks a lot

**Comment by ekutner** [comment]
Sorry I don't understand the question but even if I did I will probably not be able to help you. I don't know which sensors are available for your appliance, the integration creates all the sensors (and everything else) automatically based on information it gets from the HC for your specific appliance. So every appliance out there may have different sensors, programs, etc. You can find out all the available sensors by looking at the "States" tab in the Developer Tools.
