### ISSUE TITLE
New config value sensor_value_translation is not accepted as valid

### ISSUE THREAD

**Issue by mastermc0** [ekutner/home-connect-hass#32]
## Version of the custom_component
0.4.7

## Configuration

home_connect_alt:
  client_id: !secret HOME_CONNECT_CLIENT
  client_secret: !secret HOME_CONNECT_SECRET
  language: en-GB
  sensor_value_translation: server

## Describe the bug
If you add sensor_value_translation Home Assistant refuses to restart or does not set up the addon as the sensor_value_translation is reported as invalid.

Invalid config for [home_connect_alt]: [sensor_value_translation] is an invalid option for [home_connect_alt]. Check: home_connect_alt->home_connect_alt->sensor_value_translation. (See /config/configuration.yaml, line 110). 

## Debug log

I can enable debug logs if required.

**Comment by mastermc0** [comment]
Ignore this apparently some strange special characters were causing this.

**Comment by alsFC** [comment]
I still have this issue even if I type it manually.

**Comment by ekutner** [comment]
You're right, I had a type in the configuration and no matter how many times I looked at it I didn't see it :)
v0.4.8 fixes it
