### ISSUE TITLE
Favorites in select program (coffee)

### ISSUE THREAD

**Issue by boergegrunicke** [ekutner/home-connect-hass#327]
First, thanks for this integration, it is really much better, then the core integrated one. It might seem a little bit confusing to sometimes have the "translated" strings and sometimes the raw ones from the API, but with all this additional information, I can realize my automations (this would not be possible with the core version).

**Is your feature request related to a problem? Please describe.**
 I would like to start the coffee making process by different triggered automations, not only the pre-selected ones, but also the custom favorites. They are called something like: `BSH.Common.Program.Favorite.003`. Do you think this could be integrated somehow in the integration as well?

**Describe the solution you'd like**
Not quite sure, if the API exposes, which favorites are actually set. If not, there could be commands to just trigger the different favorite numbers

**Additional context**
_No additional context_

**Comment by ekutner** [comment]
Thank you for the kind words, I'm glad you like it and find it useful.
As for these programs, if they were exposed by the API they would have already showed up in the programs select box. You can see more details here #311 but there is nothing I can do about it so I'm closing this issue.
