### ISSUE TITLE
Getting useful info from dishwasher

### ISSUE THREAD

**Issue by mario-pranjic** [ekutner/home-connect-hass#328]
I am missing information from my dishwasher when it requires cleaning cycle, low/no dishwasher shining liquid, etc... I get them in Home Connect (under: "alerts", the same as for  washing cycle start/finish), but can't seem to have in in HA via this integration.

**Describe the solution you'd like**

An alert in logbook or any other type of alert device to enable me to see informatrion about need for dishwasher clean cycle, adding shining liquid, etc...

**Describe alternatives you've considered**

For now I have to use Bosch app in parallel to get this type of information.

**Additional context**

**Comment by ekutner** [comment]
If this information is available in the API for your device it would be exposed as an event in HA. You can use the developer tools to listen to events generated by the integration to see if anything shows up. If it's not exposed by the API then there is nothing I can do about it.
