### ISSUE TITLE
Missing Unit Option in Start Program Service

### ISSUE THREAD

**Issue by crhammock** [ekutner/home-connect-hass#33]
## Version of the custom_component 0.4.7

I believe the integration is missing a handler for the unit option of the data.

For example if I use the following value in the service options box

[{"key":"Cooking.Oven.Option.SetpointTemperature","value":"230","unit": "°C"},
{"key":"BSH.Common.Option.Duration","value":1200},"unit": "seconds"]

I get the following error and log

2022-06-02 18:31:38 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140564796667744] Error handling message: extra keys not allowed @ data['options'][0]['unit']. Got None (invalid_format)

This format is outlined in the below section of the home connect API documentation
https://apiclient.home-connect.com/#/programs/start_program

**Comment by ekutner** [comment]
While the unit parameter exists in the API it seems to be ignored and all the options are set correctly without passing it. It is indeed not supported by the integration and unless I see a demonstration of how it affects the API call I have no plans to add support for it.
