### ISSUE TITLE
Keep hitting API limits with 10 appliances

### ISSUE THREAD

**Issue by cregeland** [ekutner/home-connect-hass#331]
First of all - thank you for this great integration!

I’m using it in a house with 10 appliances hooked up to Home Connect.

I believe I have issues with the API limits. Quite often all the entities will have an unknown state. The following day it will work again for a few hours.

Would it be possible to reduce the number of API hits somehow?

Thanks:)

**Comment by Rep-Hueman** [comment]
Maybe a workaround...

Make a copy of the Home connect alt and edit it in two or more new integrations and change domain etc. 
Home connect one, 
Home connect two,
etc..

create an application per integration in the Home Connect developers website!

**Comment by cregeland** [comment]
Thanks for the reply and suggestion. I'll give it a shot with multiple integrations. I guess I will have to filter out a couple of appliances in each integration in order to reduce the number of active appliances on each application?

**Comment by cregeland** [comment]
@Rep-Hueman - how would I duplicate the integration? I have copied the folder under custom components, renamed the folder (home_connect_alt_2) and renamed the domain and name in manifest.json.

When attempting to add the integration (Home Connect Alt 2) i get this message:

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by ekutner** [comment]
It's an interesting idea but I'm not sure it's really going to work. Try also changing the DOMAIN variable in const.py and see if that gets it to work. Note that if it does work you'll have to do this process every time the integration is updated. You should also use the disabling configuration I suggested above to split the appliances between the two instances of the integrations or they'll just both get rate limited together.

**Comment by cregeland** [comment]
thanks @ekutner, I've updated the domain variable in const.py as well. still same error. Here's the top section of the const.py:

"""Constants for the Home Connect Alt integration."""


DOMAIN = "home_connect_alt_2"
NAME = "Home Connect Alt 2"
DEFAULT_API_HOST = "https://api.home-connect.com"

ENDPOINT_AUTHORIZE = "/security/oauth/authorize"
ENDPOINT_TOKEN = "/security/oauth/token"
SCOPES = "IdentifyAppliance Monitor Control Settings"
CONF_API_HOST = "api_host"
CONF_API_HOST_OPTIONS = [ "https://api.home-connect.com", "https://api.home-connect.cn" ]
# CONF_API_HOST_OPTIONS = [
#     {"label": "default", "value": "https://api.home-connect.com"},
#     {"label": "china", "value": "https://api.home-connect.cn"}
# ]

It is still throwing the same error. Looks like the icon is white when adding the integration:
![homeconnect](https://github.com/ekutner/home-connect-hass/assets/61166644/3c1f0a91-dc53-49e7-9b2b-d39f8c79e556)
![configflow](https://github.com/ekutner/home-connect-hass/assets/61166644/365273f8-2d1b-46a1-b910-9e6a1ee0e9d0)

**Comment by ekutner** [comment]
Check out version 1.1.0-b1 and the "dealing with API rate limit" in the README.

**Comment by Rep-Hueman** [comment]
Nice how can i test this?  
I have 5 appliances hooked up to Home Connect.
Can you now add multiple integrations of Home connect alt and create an app per device in the def portal?

Would like to test it for you.
I have a washing machine, steam oven, combi oven, espresso machine and extractor hood

**Comment by ekutner** [comment]
> Nice how can i test this? 
Follow the instructions in the README

**Comment by cregeland** [comment]
Thank you for your effort.

I have added a second set of credentials and installed the second version of the integration. Devices are found, but unable to click "configure" due to error message:

![image](https://github.com/ekutner/home-connect-hass/assets/61166644/444f9a72-7378-4c48-b74b-b9b09870a34b)

**Comment by ekutner** [comment]
@cregeland
Make sure that you removed the home_connect_alt section from configuration.yaml then enable debug logging, restart home assistant and if still have issues attach the full log file here.

**Comment by zufivan** [comment]
Hi @ekutner, I configured a second developer app and setup "Home Connect Alt", everything is working.
Unfortunately with beta version 1.1.0-b1 and 1.1.0-b2 I got the same problem (500 Internal Error)  when I try use the "CONFIGURE" button, 
I see in the log following error:
`AttributeError: 'NoneType' object has no attribute 'update'`
[home-assistant_home_connect_alt_2024-02-13T00-39-48.870Z.log](https://github.com/ekutner/home-connect-hass/files/14254319/home-assistant_home_connect_alt_2024-02-13T00-39-48.870Z.log)

**Comment by ekutner** [comment]
Try b3

**Comment by cregeland** [comment]
Great job @ekutner - «configure» is now working😁👍 I’ll give it a shot running two instances while dividing appliances between them.

**Comment by ekutner** [comment]
Closing as done
