### ISSUE TITLE
Doesn‘t update latest oauth website

### ISSUE THREAD

**Issue by superpower10** [ekutner/home-connect-hass#334]
Entered a wrong Redirect URIs in at the Home Connect Developer Progamm Application. 

So I changed it, but the integration doesn‘t pulls the new one.

Deinstalled the HACS Integration. Rebooted. Reinstalled HACS Integration. 

Tried to add the integration in the build in integration but it **doesn‘t ask me for the App-Name and credentials** anymore. It directly brings this: 
![IMG_0894](https://github.com/ekutner/home-connect-hass/assets/20533966/fac34dad-fb34-4ce7-bba7-b2d2a06ced2b)

But this bring me to the old URL.

How can I delete it completely and restart installation?

**Comment by JaySea77** [comment]
@superpower10 how did you fix it?

**Comment by ekutner** [comment]
It's the first item in the FAQ
