### ISSUE TITLE
Missing entity to regulate fan for integrated ventilation in hob

### ISSUE THREAD

**Issue by chrannen** [ekutner/home-connect-hass#335]
Hi

Thanks a lot for this great integration.

I actually use the **iQ700 Induction hob with integrated ventilation** (art. no. **EX807LX67E**). It's this device: [https://www.siemens-home.bsh-group.com/uk/productlist/EX807LX67E](https://www.siemens-home.bsh-group.com/uk/productlist/EX807LX67E).

For me it is clear that for security reasons it is not possible to operate the hob remotely. However, for automation I would like to be able to control the integrated ventilation system via Home Assistant. This function is actually available in the Android Home Connect app (see print screen...).

**Can the API be extended accordingly with this entity (I think a numer-input)?**

![image](https://github.com/ekutner/home-connect-hass/assets/97344789/5c414d66-4812-4fd5-a077-a62acc9254a3)

Thank you very much for the review.

Best regards,
Christian

**Comment by ekutner** [comment]
Please read the FAQ about missing entities. If it was supported by the API it would have already been there, so unfortunately it can't be added until HC will support it in the API.
