### ISSUE TITLE
No Reset Filter option extractor hood

### ISSUE THREAD

**Issue by Ricks88** [ekutner/home-connect-hass#337]
Not sure if tis counts as an issue, but i am missing the "reset filter" option in the integration. I do have this in the HomeConnect App. 
Was hoping on not needed that app anymore but find no way to reset the filter notification from my siemens extractor hood,
![resethc](https://github.com/ekutner/home-connect-hass/assets/91467918/5a0a413b-f813-4430-a5cf-6debb6d94dc4)

**Comment by ekutner** [comment]
The mobile app is using a private API and can do more things than the integration. To check if this is even possible please press the "Home Connect Debug Info" button in the HA UI and upload your log file here.

**Comment by Ricks88** [comment]
> To check if this is even possible please press the "Home Connect Debug Info" button in the HA UI and upload your log file here.

Thank you for the information.
Is this what you mean?
[home-assistant_home_connect_alt_2024-02-21T11-28-50.149Z.log](https://github.com/ekutner/home-connect-hass/files/14358756/home-assistant_home_connect_alt_2024-02-21T11-28-50.149Z.log)

**Comment by Ricks88** [comment]
Found it :) 

Is this one correct?
[home-assistant_home_connect_alt_2024-02-21T19-05-09.508Z.log](https://github.com/ekutner/home-connect-hass/files/14363918/home-assistant_home_connect_alt_2024-02-21T19-05-09.508Z.log)

**Comment by ekutner** [comment]
Yes, that's right.
I see you have several appliances but you didn't specify which one you're trying to reset. I'm guessing it's the hood.
The hood doesn't seem to offer a direct why to do what you want. It may (not sure at all) be possible to do it using the BSH.Common.Command.AcknowledgeEvent command, however, you will have to know the name of the event that indicates a dirty filter. In the log I don't see that you are getting that event. If you really want to try this you'll have to listen to events published by the integration, or scan through your logs when debug logging is enabled for the integration and look for an event that indicates the filter needs to be clean/replaced. If you actually find such an event then let me know and I'll explain what you need to do with it.

**Comment by dennypage** [comment]
I believe the relevant events are:
`Cooking.Common.Event.Hood.GreaseFilterMaxSaturationNearlyReached`
and
`Cooking.Common.Event.Hood.GreaseFilterMaxSaturationReached`

However, I do not know how to perform the reset.

**Comment by ekutner** [comment]
You can try using the Run Command service, use "BSH.Common.Command.AcknowledgeEvent" as the command key and either of those event keys as the value.

**Comment by Ricks88** [comment]
Thank's for the explanation,
I never worked with evets jet, tbh i do not know what to do/try now 🙈 

Do you meen the events like discribed here?
https://www.home-assistant.io/docs/configuration/events/

**Comment by ekutner** [comment]
You said you already know the names of the events, so you can just go ahead and try calling the service, as I explained above, and see if that works.

**Comment by Ricks88** [comment]
> You said you already know the names of the events, so you can just go ahead and try calling the service, as I explained above, and see if that works.

No that was not me :P  but i will try in when i am home :)

**Comment by dennypage** [comment]
It was me, just chiming in.

The available events for Home Connect are documented [here](https://api-docs.home-connect.com/events/#home-appliance-events). The ones of interest in this discussion can be found by searching for "GreaseFilter". I have not found any documentation on resetting the filter. AcknowledgeEvent would be my only guess.

FWIW, a good resource for undocumented Home Connect features is the Homebridge implementation located [here](https://github.com/thoukydides/homebridge-homeconnect). I don't believe he has a reset for the hood filter either.

**Comment by Ricks88** [comment]
I tried this command, not sure if it is the correct way to use?
![runcommand](https://github.com/ekutner/home-connect-hass/assets/91467918/6d9901ed-b9f8-4168-8921-ac625ee79ec6)

But gives an error.
I do not have a "saturated" hood atm. So will try when it is 100% again.

**Comment by ekutner** [comment]
Please try version 1.1.3, it should fix this bug. That still doesn't mean the command will actually work but if it fails the error should come from the Home Connect API saying it's not supported or something like that.

**Comment by dennypage** [comment]
As you expected:

`
2024-02-24 08:22:57.711 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139779413723072] Error handling message: Command value: Cooking.Common.Event.Hood.GreaseFilterMaxSaturationReached not supported (home_assistant_error) Denny Page from 192.168.1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15)
`

If I come across the undocumented command that resets the filter, I will let you know.

**Comment by ekutner** [comment]
Yeah, unfortunately their public API is limited compared to the internal API used by their mobile app.
I'm going to close this issue now as it doesn't seem possible.
