### ISSUE TITLE
After removing my credentials from the configuration.yaml and reinstalling I cant authorised anymore

### ISSUE THREAD

**Issue by diedvdyk** [ekutner/home-connect-hass#341]
After removing my credentials from the configuration.yaml and reinstalling I cant authorised anymore

I get this 

{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": <removed>
}

So I checked on the developer website of Home Connect and saw that my redirecting url was wrong and corrected it.

But now everytime I try to add the integration again I directly get the unauthorized_client message.
I dont get the dialog , that I got the first time, to enter my credentials .
I tried removing the integration, then restarting HA, the installing the integration again but the error stays and I dont get the dialog for my credentials.

In the url that is called

https://api.home-connect.com/security/oauth/authorize?response_type=code&client_id=<removed>&redirect_uri=https://my.home-assistant.io/redirect/oauth&state=<removed>&scope=IdentifyAppliance+Monitor+Control+Settings

there is redirect_uri=https://my.home-assistant.io/redirect/oauth

this isnt my HA uri and not the uri I authorised on the developer Home Connect website

**Comment by idominiki** [comment]
For me it helps to remove yaml config and restart HA

I only got internal server error while I want to configure the integration as mentioned in #340

**Comment by diedvdyk** [comment]
> For me it helps to remove yaml config and restart HA
> 
> I only got internal server error while I want to configure the integration as mentioned in #340

I saw this and thought I had to re-auth again and decided to reinstall the integration.

**Comment by diedvdyk** [comment]
> But now everytime I try to add the integration again I directly get the unauthorized_client message. I dont get the dialog , that I got the first time, to enter my credentials . I tried removing the integration, then restarting HA, the installing the integration again but the error stays and I dont get the dialog for my credentials.
> 

I managed to solve this.
In the integration menu there is a "hamburger" choice for application credentials.
There you can delete the account details for Home Connect ALT
After deleting and readded the integration I get the credentials dialog again.

Unfortunately I still get the same "unauthorized_client" .

**Comment by diedvdyk** [comment]
I have solved my problem. 
The redirect url has to be https://my.home-assistant.io/redirect/oauth in the api configuration of the developer Home Connect website.
Then the authentication process works, but it's complex ...
You have the login in at the Home Connect website first , then grant access, then https://my.home-assistant.io , type your real internal HA uri press save ....
