### ISSUE TITLE
home connect status sensor lost

### ISSUE THREAD

**Issue by bkbartk** [ekutner/home-connect-hass#342]
this sensor
`sensor.home_connect_status`
doesn't work for me anymore
it's described here
https://github.com/ekutner/home-connect-hass?tab=readme-ov-file#integration-state
but doesn't exists anymore.

I know about the missing sensor issue from the API, but this one is not from one of my devices but the integration itself.

If it's not needed anymore, it's ok for me. but I use this one to keep track, and fix the 'BLOCKED' status.

**Comment by ekutner** [comment]
1. Please update to build 1.1.1
2. If the issue still exists please follow to issue submission instructions and provide all the required information

**Comment by bkbartk** [comment]
sorry for not following the instructions, I was a little in a hurry while typing.
however with a small name change the issue is fixed
![image](https://github.com/ekutner/home-connect-hass/assets/17070805/625aa1d1-dc75-483b-802c-75d1873b771e)
also I see now the additional attributes which can be really helpfull for me

**Comment by ekutner** [comment]
I have no idea why the name has changed, I have two HA instances and it only changed on one, something in the way HA handles the translations I think. That's why it's always better to use the entity ID amd not the name.

**Comment by bkbartk** [comment]
I would assume it might depend on if you initially installed the integration before or after some ha update,
and it changed for me as I recently reinstalled the integration.

but it works, that's the important thing, entity ID's are hard to read, that's why I try to avoid them.
