### ISSUE TITLE
Not able to connect home connect alt integration after update to 1.1.1

### ISSUE THREAD

**Issue by canedje** [ekutner/home-connect-hass#346]
## Describe the bug
After updating HACS to 1.1.1 I'm not able to pair the integration to Home Connect anymore.
I do use the integration already several years.
I tried every thing I can imagin.
I used the old credentials. Did create a new application with new credentials. Tried default and China as server.
The only thing I'm not sure about is what to enter at "Name". I did try the name used at the home connect app, the e-mail and the name of the application for credentials.
I come thrue all steps including going to home connect and back.
The result is: see log area

## Configuration

I'm Running HA as a docker under Unraid
HA version 2024.2.2
Unraid version: 6.12.6

## Debug log

In the HA log it says:
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 21 februari 2024 om 22:21:20 (1 occurrences)
Last logged: 21 februari 2024 om 22:21:20

Setup failed for custom integration 'home_connect_alt': Invalid config.
If the bug results in an exception paste it below, in all other cases please attach the entire log file. Without the log I will not be able to understand the issue.
![image](https://github.com/ekutner/home-connect-hass/assets/23150947/229149b7-b89a-45aa-87d6-a2c8ad65fc0d)
![image](https://github.com/ekutner/home-connect-hass/assets/23150947/8c6c30be-bbd7-4eec-903f-ee6e2bd78b49)
In the Unraid HA log:
```
2024-02-22 08:08:44.764 ERROR (MainThread) [homeassistant.config] Invalid config for 'home_connect_alt' at configuration.yaml, line 303: 'client_id' is an invalid option for 'home_connect_alt', check: home_connect_alt->client_id, please check the docs at https://github.com/ekutner/home-connect-hass
Invalid config for 'home_connect_alt' at configuration.yaml, line 304: 'client_secret' is an invalid option for 'home_connect_alt', check: home_connect_alt->client_secret, please check the docs at https://github.com/ekutner/home-connect-hass
2024-02-22 08:08:44.764 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'home_connect_alt': Invalid config.
```

```text
Paste the exception info here or attach the full log file

```

**Comment by ekutner** [comment]
It's the first thing in the release notes for this version. You need to remove the entire home_connect_alt section from the configuration.yaml file.

**Comment by canedje** [comment]
That did the trick. Thanks!
