### ISSUE TITLE
Failed to apply the setting: HomeAppliance did not respond in time. (409)

### ISSUE THREAD

**Issue by razzietheman** [ekutner/home-connect-hass#348]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:12:10 (1 occurrences)
Last logged: 11:12:10

[140492981606080] Failed to apply the setting: HomeAppliance did not respond in time. (409)
Traceback (most recent call last):
  File "/config/custom_components/home_connect_alt/select.py", line 271, in async_select_option
    await self._appliance.async_apply_setting(self._key, option)
  File "/usr/local/lib/python3.12/site-packages/home_connect_async/appliance.py", line 397, in async_apply_setting
    return await self._async_set_service_value("settings", setting_key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/home_connect_async/appliance.py", line 424, in _async_set_service_value
    raise HomeConnectError(response.error_description, response=response)
home_connect_async.common.HomeConnectError: ('HomeAppliance did not respond in time.', None, 'SDK.Error.HomeAppliance.Connection.Initialization.Failed', 'HomeAppliance did not respond in time.', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 195, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/home_connect_alt/select.py", line 274, in async_select_option
    raise HomeAssistantError(f"Failed to apply the setting: {ex.error_description} ({ex.code})")
homeassistant.exceptions.HomeAssistantError: Failed to apply the setting: HomeAppliance did not respond in time. (409)

**Comment by ekutner** [comment]
The error is pretty self explanatory, the appliance didn't respond to the command. Either there is/was a network problem or there is something wrong with the appliance. Try in order of complexity:
1. Reset your router.
2. Disconnect the appliance from mains power and reconnect.
3. Remove the appliance from Home Connect and add it back again.

**Comment by razzietheman** [comment]
> The error is pretty self explanatory, the appliance didn't respond to the command. Either there is/was a network problem or there is something wrong with the appliance. Try in order of complexity:
> 
> 1. Reset your router.
> 2. Disconnect the appliance from mains power and reconnect.
> 3. Remove the appliance from Home Connect and add it back again.

well the script I have turns the washing maschine off but HA keeps getting this error message! so somewhere is a problem that keeps getting error message when the maschine turns off!

here is the script that turns it off everytime

stang_av_tvattmaskin:
  icon: mdi:washing-machine-off
  alias: Stäng av tvättmaskin
  sequence:
  - service: select.select_option
    metadata: {}
    data:
      option: BSH.Common.EnumType.PowerState.MainsOff
    target:
      entity_id: select.bosch_wau28pehsn_68a40e5d595e_bsh_common_setting_powerstate
  mode: single

**Comment by ekutner** [comment]
sorry, I don't understand what you're trying to do. Did you try what I suggested above?

**Comment by razzietheman** [comment]
> sorry, I don't understand what you're trying to do. Did you try what I suggested above?

well I have a script that turn off the washing maschine ,
3. Remove the appliance from Home Connect and add it back again. - do you mean from the integration in HA or from HC on the phone?

**Comment by ekutner** [comment]
I meant remove from HC. Before automating with a script you should first make sure you can actually do this manually in the UI. In general, as I noted in my first response, this error means your appliance didn't respond to the command. It is an issue between your appliance and HC and doesn't really have anything to do with the integration.

**Comment by razzietheman** [comment]
> I meant remove from HC. Before automating with a script you should first make sure you can actually do this manually in the UI. In general, as I noted in my first response, this error means your appliance didn't respond to the command. It is an issue between your appliance and HC and doesn't really have anything to do with the integration.

yeah I will try that, but both the script & in GUI the washer turns off and so fine but keep getting the error message after in HA
