### ISSUE TITLE
Dishwasher SPV6HMX2MR add switch extra rinse

### ISSUE THREAD

**Issue by mrartifact** [ekutner/home-connect-hass#349]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I can't enable extra rinse when installing the SPV6HMX2MR dishwasher program.

**Describe the solution you'd like**
Please add an extra rinse option switch like dishcare_dishwasher_option_extradry.

**Describe alternatives you've considered**
I tried searching for the API key on https://api-docs.home-connect.com/programs-and-options , and couldn't find it, maybe I didn't search well(. 
If the key exists, please post it.

**Comment by ekutner** [comment]
As noted in the FAQ, if this was supported by the API a relevant control would have been added automatically by the integration. It can't be done without support from the API.
