### ISSUE TITLE
unable to load home_connect_alt

### ISSUE THREAD

**Issue by multinet33** [ekutner/home-connect-hass#352]
Config Home Assistant
Core
2024.2.5
Supervisor
2024.02.0
Operating System
12.0
Interface utilisateur
20240207.1

Message "not loaded"
->rebooting HA does not loed the component
-> reconfiguting the home_connect_alt does not make it loaded

after reconfiguring the home connect alt i have this message:
```
Succès!
Successfully authenticated

Configuration créée pour Home Connect Alt.

Cette intégration ne peut être chargée, essayez de redémarrer Home Assistant

```

but after restarting HA the home connect alt is still not loaded

Any idea ?

**Comment by Claus77777** [comment]
i have the same Problem

Konfigurationswarnungen
Invalid config for 'home_connect_alt' at configuration.yaml, line 68: 'client_id' is an invalid option for 'home_connect_alt', check: home_connect_alt->client_id
Invalid config for 'home_connect_alt' at configuration.yaml, line 69: 'client_secret' is an invalid option for 'home_connect_alt', check: home_connect_alt->client_secret

**Comment by multinet33** [comment]
Thank you it is the solution !

**Comment by Claus77777** [comment]
thanks
