### ISSUE TITLE
Cut off BSH cloud 

### ISSUE THREAD

**Issue by moskovskiy82** [ekutner/home-connect-hass#353]
I have stumbled upon this article 
https://trmm.net/homeconnect/

Leading to this github repo https://github.com/osresearch/hcpy

Seems like the project was abandoned but cutting off the Bosch cloud from the Home connect alt will be a precious gem allowing a fully local control over appliances

**Comment by ekutner** [comment]
This was suggested multiple times. I have no intention to complete the work on that library.

**Comment by bkbartk** [comment]
I saw your comment,
Also on the other 2 issues created about this.
and I noticed there is a fork(clone/cutoff)
https://github.com/hcpy2-0/hcpy
which is actively developed at the moment.

If I check the docker file I think it might even will run as an HA addon, writing values to MQTT.

I know it's a totally different project and going this route probably means starting from scretch.  But I just wanted you to be aware that there is progress.
