### ISSUE TITLE
No Devices get added

### ISSUE THREAD

**Issue by mr-gosh** [ekutner/home-connect-hass#354]
## Describe the bug

When I add the home-connect Account according to the Readme - the link is successfull - but only 1 device and 3 entitites get created. thats it.

- the app has a working connection to the 2 devices without wlan
- the stock integration was working before with both devices
- there are errors in the debug log
- there are no custom entries in the config.yaml

## Version of the custom_component
- I am using Version 1.1.3
- HASS-OS on a RPi - fully patched

## Configuration
- no special configs

## Debug log

```debug
2024-02-29 14:49:46.244 DEBUG (MainThread) [home_connect_async.api] 
HTTP GET /api/homeappliances (try=1 count=2)

2024-02-29 14:49:46.380 DEBUG (MainThread) [home_connect_async.api] HTTP GET /api/homeappliances (try=1 count=2) [200]
2024-02-29 14:49:49.867 ERROR (MainThread) [custom_components.home_connect_alt.button] {
  "global": {
    "api_host": "https://api.home-connect.com"
  },
  "7712c61cd5fc41306fffb147931c9b01": {
    "name_template": "$brand $appliance - $name",
    "delayed_ops": "default",
    "log_mode": 0,
    "appliance_settings": {},
    "sse_timeout": 15,
    "language": "en-GB",
    "translation_mode": "local",
    "entity_settings": {
      "BSH.Common.Option.FinishInRelative": {
        "type": "DelayedOperation",
        "unit": null,
        "class": "home_connect_alt__timespan"
      },
      "BSH.Common.Option.StartInRelative": {
        "type": "DelayedOperation",
        "unit": null,
        "class": "home_connect_alt__timespan"
      },
      "BSH.Common.Option.ElapsedProgramTime": {
        "unit": null,
        "class": "home_connect_alt__timespan"
      },
      "BSH.Common.Option.EstimatedTotalProgramTime": {
        "unit": null,
        "class": "home_connect_alt__timespan"
      },
      "BSH.Common.Option.RemainingProgramTime": {
        "unit": null,
        "class": "timestamp"
      },
      "BSH.Common.Status.DoorState": {
        "type": "Boolean",
        "class": "door",
        "icon": null,
        "on_state": "BSH.Common.EnumType.DoorState.Open"
      },
      "Refrigeration.Common.Status.Door.Freezer": {
        "type": "Boolean",
        "class": "door",
        "icon": null,
        "on_state": "Refrigeration.Common.EnumType.Door.States.Open"
      },
      "Refrigeration.Common.Status.Door.Refrigerator": {
        "type": "Boolean",
        "class": "door",
        "icon": null,
        "on_state": "Refrigeration.Common.EnumType.Door.States.Open"
      },
      "Connected": {
        "class": "connectivity"
      }
    },
    "primary_config_entry": true,
    "homeconnect": "<not serializable>",
    "services": "<not serializable>",
    "auth": "<not serializable>"
  }
}
2024-02-29 14:49:49.869 ERROR (MainThread) [custom_components.home_connect_alt.button] {
  "appliances": {},
  "_disabled_appliances": [],
  "_sse_timeout": 15
}
2024-02-29 14:49:57.352 DEBUG (MainThread) [home_connect_async.homeconnect] Received event from SSE stream: MessageEvent(type='KEEP-ALIVE', message='KEEP-ALIVE', data='', origin='https://api.home-connect.com', last_event_id='')
2024-02-29 14:50:52.352 DEBUG (MainThread) [home_connect_async.homeconnect] Received event from SSE stream: MessageEvent(type='KEEP-ALIVE', message='KEEP-ALIVE', data='', origin='https://api.home-connect.com', last_event_id='')
2024-02-29 14:51:18.273 DEBUG (MainThread) [home_connect_async.homeconnect] Received event from SSE stream: MessageEvent(type='KEEP-ALIVE', message='KEEP-ALIVE', data='', origin='https://api.home-connect.com', last_event_id='')
```

**Comment by ekutner** [comment]
The API didn't return any appliances. Please see troubleshooting suggestions in the FAQ in the README.

**Comment by mr-gosh** [comment]
Ok - my fault.
The mqtt server IP changed and the addon didn't mention any problems to mee - found a log entry mentioning "server not found" than I found the problem.

Strange that the Mqtt client doesn't show the connection problem in the devices view...

Thanks for your help.

Now it works

**Comment by ekutner** [comment]
Not sure what the mqtt server has to do with it 🦋 as long as it's working that's good.

**Comment by mr-gosh** [comment]
>  Not sure what the mqtt server has to do with it 🦋 as long as it's working that's good. 

Commented the wrong bug - this one is still open. But I will walk through the troubleshooting guide once more and comment with the results here.

**Comment by mr-gosh** [comment]
Please re-open the bug.
I walked through all troubleshooting steps and also tried a lot of the suggested steps here https://community.home-assistant.io/t/home-connect-integration-error/440268/60

I can definitely see both appliances in the app without wlan
I tried another browser, without ad-blocking software in a private browsing  mode
There are no errors in the interface

**Comment by mr-gosh** [comment]
Ok - i found the error. Siemens switched to the new login mechanism and I had the old integration in another account than the new singlekeyid - there I needed to create a new developer account.

So it worked on the other account just because it was created before the singlekeyid was deployed... - sorry but that was difficult to identify!
