### ISSUE TITLE
Just upgraded and configuration is broken

### ISSUE THREAD

**Issue by plattze** [ekutner/home-connect-hass#355]
Had a previously working system.  Only change was to upgrade to 1.1.3 in the HACS UI.  UI showed 4.x to 5.x something, but now that it's broken I cant see the exact version sorry.

I can't see any documentation which is suggesting the configuration.yaml config has changed?

```
Logger: homeassistant.config
Source: config.py:1293
First occurred: 5:03:43 PM (1 occurrences)
Last logged: 5:03:43 PM

Invalid config for 'home_connect_alt' at configuration.yaml, line 34: 'client_id' is an invalid option for 'home_connect_alt', check: home_connect_alt->client_id, please check the docs at https://github.com/ekutner/home-connect-hass Invalid config for 'home_connect_alt' at configuration.yaml, line 35: 'client_secret' is an invalid option for 'home_connect_alt', check: home_connect_alt->client_secret, please check the docs at https://github.com/ekutner/home-connect-hass
```

Configuration.yaml (which hasnt changed):

```
home_connect_alt:
  client_id: C8XXXXXXXXXXXXX
  client_secret: D8XXXXXXXXXXXXXXX
```

**Comment by moerpel** [comment]
Same here.

**Comment by ekutner** [comment]
As @moerpel  said, there was a breaking change which was noted in the release notes. You should just remove the home_connect_alt section from configuration.yaml. Everything is not configurable in the UI. In procedure @moerpel  mentions should not be necessary, the integration will ask for the credentials if they don't exist.

**Comment by ekutner** [comment]
Delete any credentials associated with the home connect alt integration then delete the integration (which actually means you need to delete the config entry) and then add the integration back again.

**Comment by LucasHokerberg** [comment]
> Delete any credentials associated with the home connect alt integration then delete the integration (which actually means you need to delete the config entry) and then add the integration back again.

Yepp, that did the trick. Thanks!

**Comment by jatty** [comment]
> Same here. Just check the release notes. There was a breaking change that affects configuration in configuration.yaml.

Thank you, I had the same problem and solved it this way by reading the release notes.
