### ISSUE TITLE
Custom class doesn't seem to work anymore

### ISSUE THREAD

**Issue by seidler2547** [ekutner/home-connect-hass#356]
After updating to the latest version, it seems like customizing the class doesn't work anymore, at least not like it did before.

Config snippet in "Advanced Entity Settings (YAML)":
```
BSH.Common.Option.RemainingProgramTime:
  class: "{DOMAIN}__timespan"
```

Expected result: remaining program time is a timespan

Actual result: remaining program time is a timestamp

**Comment by Tipmanfrank** [comment]
After updating to Core 2024.3 I can't read in the integration. So yes there is a problem now.

**Comment by ekutner** [comment]
@seidler2547 please enable debug logging, restart HA and upload the log file.

**Comment by ekutner** [comment]
I was able to reproduce the issue, no need for logs. Fixed in 1.1.5.

**Comment by Jack77777777** [comment]
@seidler2547 @ekutner Can you post a complete yaml section to convert timestamp to timespan please ?

**Comment by Jack77777777** [comment]
Nevermind. I think i got it. It‘s at the bottom of the integration configuration 🙈.

**Comment by denis1994** [comment]
@Jack77777777 How you did it for have a timespan instead of timestamp? I don't really know how and where to change it.

**Comment by Jack77777777** [comment]
@denis1994 
![image](https://github.com/user-attachments/assets/3d99fe11-d589-4037-a986-e9d71df0d0bd)

My Code:
BSH.Common.Option.RemainingProgramTime:
  class: "{DOMAIN}__timespan"

**Comment by denis1994** [comment]
Ah there, perfect it worked. Thank you very much
