### ISSUE TITLE
unable to get rid of it

### ISSUE THREAD

**Issue by commentsonly** [ekutner/home-connect-hass#357]
despite the fact that it resulted in way to many issues with my bosch dishwasher which works perfectly using the official integration it would be nice to know about HOW TO get rid of this alternative integration.

I think I did wipe everything to do with this one, but nevertheless it pesters me about an update ready to be installed.
Even a reboot didn't cure that to there might be something left over, perhaps deeply hidden in a docker container somehow?

**Comment by ekutner** [comment]
The integration is removed like any other. You have to delete the integration entry from the Devices & Services screen and then delete it from HACS.
