### ISSUE TITLE
How to enable washing machine settings

### ISSUE THREAD

**Issue by obiphi** [ekutner/home-connect-hass#361]
Hi,

The integration works brilliantly, thank you for your hard work!

The issue I'm having is that I want to enable a few additional (washing machine) settings after selecting a program, but I can't see how to do it. The component adds the following entities:
binary_sensor.bosch_wdu8h541gb_{redacted}_laundrycare_washer_option_prewash
sensor.bosch_wdu8h541gb_{redacted}_laundrycare_washer_option_rinseplus
binary_sensor.bosch_wdu8h541gb_{redacted}_laundrycare_common_option_silentmode
binary_sensor.bosch_wdu8h541gb_{redacted}_laundrycare_washer_option_waterplus

And I can see these entities are being set correctly when I enable the options using the physical panel on the machine. I'd like to be able to set those parameters via your plugin. I've searched through the [API documentation](https://api-docs.home-connect.com/programs-and-options/#washer) but the search function doesn't even find mention of them. How can I achieve this?

Thanks again,
Phil

**Comment by ekutner** [comment]
Thank you. 
Unfortunately most options are read only, that's why they exist only as sensors. There is nothing that can be done about it and that's why I asked not to open such issues unless it can be shown that the API does exist and the integration is not handling it correctly.
