### ISSUE TITLE
Select option powerstate not working correctly

### ISSUE THREAD

**Issue by Palmdale95** [ekutner/home-connect-hass#362]
Hello,

I have an issue for an automation to start my Siemens coffee maker on a select option. Every morning it is giving the error call. If I do the select option manually over the button it is working correctly.

hier ist what the log tells me:

Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:239
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 08:30:08 (4 Vorkommnisse)
Zuletzt protokolliert: 08:41:33

[139771908630976] Failed to apply the setting: HomeAppliance connection initialization failed (409)
[139771908630976] Failed to apply the setting: BSH.Common.Setting.PowerState currently not available or writable (409)
Traceback (most recent call last):
  File "/config/custom_components/home_connect_alt/select.py", line 273, in async_select_option
    await self._appliance.async_apply_setting(self._key, option)
  File "/usr/local/lib/python3.12/site-packages/home_connect_async/appliance.py", line 397, in async_apply_setting
    return await self._async_set_service_value("settings", setting_key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/home_connect_async/appliance.py", line 424, in _async_set_service_value
    raise HomeConnectError(response.error_description, response=response)
home_connect_async.common.HomeConnectError: ('HomeAppliance connection initialization failed', None, 'SDK.Error.HomeAppliance.Connection.Initialization.Failed', 'HomeAppliance connection initialization failed', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 195, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/home_connect_alt/select.py", line 276, in async_select_option
    raise HomeAssistantError(f"Failed to apply the setting: {ex.error_description} ({ex.code})")
homeassistant.exceptions.HomeAssistantError: Failed to apply the setting: HomeAppliance connection initialization failed (409)

looks like the integration is some what offline?
If I trigger this manually after running the Maschine this error does not occur.

Thanks for help.

**Comment by ekutner** [comment]
It's not the integration that is offline, it's your appliance. The integration is getting this error from the HC cloud and it indicates that HC was unable to communicate with the appliance. The appliance is probably getting disconnected from the wifi network or is in some kind of sleep mode. If you are using NAT in your outgoing network connections that this might also happen if the NAT entry expired in your gateway's NAT table. Either way, it's not an issue with the integration.

**Comment by Palmdale95** [comment]
Thanks for pointing me in this direction. 
Anyway it is strange behaviour since 2 days and I did not change the setup (HAOS on a VM with NGINX as Proxy).
I just installed the original home connect integration to use the switch inside instead of the select option command and check if this has an implication.
If the disconnect ist happening there as well it must be something else. Actually I am aspecting to do so. :-) 

On the other hand there was the OS update these days and a fritz.box update would have caused that right?

**Comment by ekutner** [comment]
I had to look up what a fritz!box is but yes, that might cause it, it has nothing to do with HAOS or the integration because it is successfully making the call to the HC cloud and getting this error. The integration is talking to the HC servers in the cloud, not directly to your appliance and that is working fine, so it's not offline. When the command is sent to the HC cloud it then tries to contact the appliance to run the command but can't reach it, which generates the error. The problem is between your appliance and the HC cloud. If it was always happening I would have guessed that the appliance is in some sort of sleep mode and doesn't respond until you wake it up by pressing a button, however, since it used to work it's more likely to be a network issue.

**Comment by Palmdale95** [comment]
Thanks. I will have a look on it as explained. So the not issue can be closed ;-)
