### ISSUE TITLE
Add Rinse and Salt sensor

### ISSUE THREAD

**Issue by jeezy51** [ekutner/home-connect-hass#365]
Hello, first of all thank you for this wonderful integration. Before using Home Assistant, I used other home automation software, and throughout Home Connect there were sensors for salt and rinse aid. It was convenient to be notified by Alexa in the morning when going to the kitchen if salt or rinse aid was missing. Is it possible to integrate these sensors? 
I specify that the salt and rinse aid sensors are perfectly integrated into my other home automation software by API HC, and they have values of On or Off. They have these names
GET::Dishcare.Dishwasher.Event.RinseAidNearlyEmpty
GET::Dishcare.Dishwasher.Event.SaltAidNearlyEmpty
BSH.Common.EnumType.EventPresentState.Off
BSH.Common.EnumType.EventPresentState.Off

**Comment by ekutner** [comment]
Happy you like it.
Sensors represent states, these are events, and as such they are published as events in HA. It's also been asked several times before and you can see the discussion here #81 and here #153
