### ISSUE TITLE
Switch missing after update "dishcare_dishwasher_option_silenceondemand" 

### ISSUE THREAD

**Issue by msandvold** [ekutner/home-connect-hass#366]
Before update there was a switch to choose "silent mode" for dishwasher.
"switch.xxxxxx_dishcare_dishwasher_option_silenceondemand" There is now only "binary_sensor.xxxxxx_dishcare_dishwasher_option_silenceondemand" 

Easy fix to get the switch back?

**Comment by ekutner** [comment]
If it's gone then it's no longer available through the API.

**Comment by msandvold** [comment]
How about theese:
- switch.xxxxxx_dishcare_dishwasher_option_extradry
- switch.xxxxxx_dishcare_dishwasher_option_variospeedplus 
- switch.xxxxxx_dishcare_dishwasher_option_halfload

**Comment by ekutner** [comment]
same thing. by the way, the integration doesn't delete entities so I'm not even sure what you mean when you say it's not there.

**Comment by msandvold** [comment]
These 4 switches has been available before update and a re-install.
If they no longer are available, that is the answer :)

**Comment by ekutner** [comment]
Entities are created dynamically. An upgrade doesn't delete entities but if you reinstalled then all the previous entities were removed when you removed the integration. They will be back when you actually use the appliance in a way that gets them back (i.e. select a program that supports them), assuming they are still available through the API.

**Comment by msandvold** [comment]
Sounds nice, will give it a testrun.
