### ISSUE TITLE
Unable To Use In China

### ISSUE THREAD

**Issue by wqhqq1** [ekutner/home-connect-hass#368]
## Describe the bug

Though chosing CN as server in config UI, it still calls for api.homeconnect.com which won't be able to access data from api.homeconnect.cn

## Version of the custom_component

Latest `1.0.0` to `1.1.6`

**Comment by xrh0905** [comment]
Can confirm the issue.
The API Host should be change to `api.home-connect.cn`

**Comment by wqhqq1** [comment]
Actually I manually replace all .com with .cn，which works well.

**Comment by ekutner** [comment]
Please provide the debug log.

**Comment by ryangu** [comment]
i have the same problem even after reboot my home assistant, api.home-connect.cn in configuration.yaml doesn't work
