### ISSUE TITLE
Program now visible in integration

### ISSUE THREAD

**Issue by wookash** [ekutner/home-connect-hass#371]
I'm using latest version of integration, downloaded custom program to dishwasher (quick wash and dry), when I select the program in the Home Connect app, in Homeassistant I see the value: 'Dishcare.Dishwasher.Program.QuickD' under selected program entity. However, when I try to make that selection using 'Home Connect Alt: Select program' service, I get an error:

`This service requires field device_id, please enter a valid value for device_id`

I'd like to be able to select Dishcare.Dishwasher.Program.QuickD program via automation

**Comment by ekutner** [comment]
The error is pretty self explanatory, you need to specify the device ID on which the service should operate. Please review the HA documentation on how to use services or consult other users in the discussion forum. Anyway, I'm not even sure if the API supports custom programs, but you;ll know when you get the service call correctly.

**Comment by wookash** [comment]
I pasted the wrong error message. I know I need to select the device and I am successfully running automation including via Siri. For some reason this new program I downloaded is not possible to be called by service call. My ask is to understand why and if it’s possible to use this program. I was able to download a different program called quick45 and it worked. Actual error message when device and program are selected below:

`home_connect_alt.select_program. The selected program key is not available`

I know it’s not the question is why..

**Comment by ekutner** [comment]
As I expected, it's not supported by the API, you can bypass the local validation by setting validate: false on the service call but most likely you'll just get the error from the HC server.

**Comment by wookash** [comment]
Yup that’s what’s happening. So it’s on the manufacturer's side then to add this program to API?

**Comment by ekutner** [comment]
yes. good luck with that :)
