### ISSUE TITLE
Dishwasher Intelligent program not recognized

### ISSUE THREAD

**Issue by z-vrba** [ekutner/home-connect-hass#373]
Hi,

I have Bosh Dishwasher SMV6ZCX16E and started Intelligent program (from mobile APP) for the first time recently. I recognized this program has not proper name in integration.

Sensors "sensor.XXXXXXXXXXXXXX_active_program" and "sensor.XXXXXXXXXXXXXX_selected_program" say: Dishcare.Dishwasher.Program.LearningDishwasher

It should be friendly name program "Intelligent".

Thank you for your consideration.

**Comment by ekutner** [comment]
It will be great if you can submit a PR which adds this to the translation files.

**Comment by z-vrba** [comment]
Never did it before, but I'll try :-)

**Comment by ekutner** [comment]
Then never mind, I'll add when I have some time, it's just a few minutes.

**Comment by ekutner** [comment]
I see you already submitted the PR, great, I'll review when I have some time :) and continue the discussion there if there is any problem with it.
