### ISSUE TITLE
bsh_common_option_estimatedtotalprogramtime for washing machine not reported

### ISSUE THREAD

**Issue by xxLeoxx93** [ekutner/home-connect-hass#374]
## Describe the bug
Sensor "bsh_common_option_estimatedtotalprogramtime" was working until today - not it's unavailable.
However now the sme information is put in "bsh_common_option_finishinrelative" ?
It's the second time that I use this integration maybe that behaviour is normal? in the first run i didn't get other sensors with data.

## Version of the custom_component
1.1.6

## Configuration
Default

**Comment by ekutner** [comment]
Sensors are available when the API makes them available. The estimated program time sensor is available when a program is running.

**Comment by xxLeoxx93** [comment]
> Sensors are available when the API makes them available. The estimated program time sensor is available when a program is running.

It was running, but the remaining time was missing.

**Comment by ekutner** [comment]
Well, it's still the same answer, sensors are available when Home Connect makes them available. If you believe this is a bug then open a new issue and include all the required information, including a debug log.
