### ISSUE TITLE
Cannot authenticate with SingleKey ID

### ISSUE THREAD

**Issue by ljilekor** [ekutner/home-connect-hass#377]
Problem :
Unable to enter Credentials with my SingleKey ID

Also refer to [this ](https://community.home-assistant.io/t/home-connect-is-singlekey-id-supported/485607/4)post

SingleKey ID only works with

- email
- password

So I do not have the required OAuth stuff when I try to install the Home-Connect-Alt Integration…
image
[image489×506 11.8 KB](https://community-assets.home-assistant.io/original/4X/d/c/1/dc1c980377b6b5215c8142e2181841c0100cc4e7.png)

- Name
- OAuth Client ID
- OAuth Client Secret

I really want to integrate my Siemens Dishwasher and Fridge.
… What now ???

**Comment by ekutner** [comment]
Follow the installation instructions in the README, I did write them for a reason.
