### ISSUE TITLE
Home Connect Smart Start

### ISSUE THREAD

**Issue by stephanlarsson** [ekutner/home-connect-hass#379]
Homeconnect has added an official smart start functionality based on emissions or, crucially, tariff price. It would be amazing by if this could be assed to the home connect alt integration. Allowing it to be toggled on and off as needed by the user (sometimes you just want the machine to run immediately, regardless of price).

thanks in advance.

**Comment by ekutner** [comment]
People have been using the integration to do exactly that, using automation, for a very long time, so in that regard it's already possible. 
When you say they added official support for it, what do you mean and where do you see it? I took a quick look at the API documentation and didn't see any new APIs to configure tariffs, so it might be just logic they added to the mobile app which does the same thing the above mentioned automations do.

**Comment by stephanlarsson** [comment]
![IMG_1520](https://github.com/ekutner/home-connect-hass/assets/120938592/5851f0ac-da08-4853-8107-c3e3e74174ec)
![IMG_1521](https://github.com/ekutner/home-connect-hass/assets/120938592/d7eb7c2d-5a48-400d-ba30-e75ca9f208da)

**Comment by ekutner** [comment]
I guess it's logic in the app itself. As I mentioned a lot of people are doing it with the integration using HA automations. You can search the issue and forum for some examples. Since you don't have to implement a generic system but just something that works for your specific low tariff it's pretty straight forward to do.

**Comment by ekutner** [comment]
Closing because this is not going to be implemented directly by the integration but can be done using automation.
