### ISSUE TITLE
Start time changing by itself

### ISSUE THREAD

**Issue by Coysh** [ekutner/home-connect-hass#380]
## Describe the bug
I believe this is a unique error and not user error.
I am setting the start time of my Dishwasher to 12:35 AM.
I am pressing "Start".

The Dishwasher Start Time automatically changes to 12:40AM, and then 7:00.
Then the app says the start time will be 19:40?!

Video below:

https://github.com/ekutner/home-connect-hass/assets/5764356/70634488-7242-47ca-82a9-5e68abcd92fe

## Version of the custom_component
Latest - fresh install

## Configuration
N/A

## Debug log

```text
Paste the exception info here or attach the full log file

```

**Comment by Coysh** [comment]
As an update, my slight workaround has been to work out the relative time according to the current time, but it's not perfect as the options are only to the 30 minute.

```
- service: select.select_option
    target:
      entity_id: select.013030526737000584_bsh_common_option_startinrelative
    data:
      option: >
        {% set now = now() %}
        {% set target_time = now.replace(hour=0, minute=30, second=0, microsecond=0) %}
        {% if now.hour > 0 or now.minute >= 30 %}
          {% set target_time = target_time + timedelta(days=1) %}
        {% endif %}
        {% set delta = target_time - now %}
        {% set total_minutes = ((delta.total_seconds() // 60) // 30) * 30 %}
        {% set hours = (total_minutes // 60) %}
        {% set minutes = (total_minutes % 60) %}
        {{ '{:02}:{:02}'.format(hours|int, minutes|int) }}
```

**Comment by ekutner** [comment]
please include the debug log.
