### ISSUE TITLE
Oven Cook Timer - Unable to set to 0 (Disabled)

### ISSUE THREAD

**Issue by RAW297** [ekutner/home-connect-hass#381]
## Describe the bug
When setting the "Adjust the duration" for a Neff Oven, trying to set this to 0 to disable the timer causes an error as described below.
It is possible to set the duration between 1-86400, but it seems seetting this to 0 (zero) would disbale the duration timer which is the most common way of operating an oven as I would like to manually control the cooking time.

In my automation to start the oven I am currently setting the duration to 86400 to ensure a long cooking time,b ut being able to set it to 0 would be more convenient.

## Version of the custom_component
Latest version available is being used

## Configuration
Configuration is default as per the installation instructions

## Debug log
[home-assistant_home_connect_alt_2024-05-08T08-32-46.793Z.log](https://github.com/ekutner/home-connect-hass/files/15246065/home-assistant_home_connect_alt_2024-05-08T08-32-46.793Z.log)

## Error shown when trying to set value to 0 (Zero)
Failed to call service number/set_value. Value 0.0 for number.303080426619000114_001_bsh_common_option_duration is outside valid range 1 - 86400

**Comment by ekutner** [comment]
As the error says, the API doesn't allow setting it to 0, the valid values are 1-86400. Nothing the integration can do about this.
