### ISSUE TITLE
Oauth fails "invalid request"

### ISSUE THREAD

**Issue by philoxio** [ekutner/home-connect-hass#385]
Hi,

I am 99% sure that I followed every step of the readme meticulously. 😉

But I always get the error below.

Retried several times.

{
  "error": "invalid_request",
  "error_description": "missing or invalid request parameters"
}

Any help is appreciated!

Thanks!

**Comment by ekutner** [comment]
I'm afraid it's 99.9% certain you missed something along the way. If you search the history you see such issues come up quite a lot and there wasn't a single cse it wasn't a configuration issue. You can start by posting your app configuration but usually setting it up again solves it.
