### ISSUE TITLE
The Translation for „Hygienic Wash“ in DE is wrong

### ISSUE THREAD

**Issue by osulivanDE** [ekutner/home-connect-hass#386]
In the german translation the „Hygienic wash“ program is incorrectly translated into „Empfindliches“ which is quite the opposite.

The corresponding translation for „Hygienic Wash“ would be „Hygienewäsche“ in german.

I started the program on the machine and HC-integration got the wrong translation for the program code.

![IMG_0592](https://github.com/ekutner/home-connect-hass/assets/44095221/c89121cb-61bc-462e-8487-7e43906e5443)

-Latest version of integration

**Comment by ekutner** [comment]
This translation is only used for *LaundryCare.Washer.Program.Sensitive*, not for hygienic wash.

**Comment by Pawlde** [comment]
The washing machine is definetly set to "Hygienic wash" wenn "empfindliches" is shown in the Home Assistant UI.
For the dryer of the same generation that I also own the translation is shown correct.

The only other reason that I can think of is that the washer is giving the wrong status. This would be an issue with the appliances firmware itself.

**Comment by ekutner** [comment]
Please set the machine to the hygienic wash mode, verify that you see the wrong translation and then press the *Home Connect Debug Info* button in the HA dashboard. Then upload the log file here.
You can also try switching to **Server Translation** mode and check what translation you see there.
