### ISSUE TITLE
Time settings for Oven HN678G4S6 by Siemens

### ISSUE THREAD

**Issue by mykm203** [ekutner/home-connect-hass#389]
Oven HN678G4S6 has inner clock, but not any buil-in battery. Due to any problem with power supply clock reset to default time and any program will not start. It will increase functionality, if Home Assistant could control this settings

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ekutner** [comment]
It's not possible to set this clock with the API
