### ISSUE TITLE
Remaining program duration, total program duration and delayed start is mixed up

### ISSUE THREAD

**Issue by Pawlde** [ekutner/home-connect-hass#391]
I'm using the partially localized german version.
Appliance is a washing mashine WGB2440

It looks like "Delayed operation" is showing the total estimated time for the current program, not a delay for a delayed start.

"Estimated total programme duration" shows the remaining time on the currently active program

"Estimated remaining time" just says "ON"

**Comment by ekutner** [comment]
I don't believe they are mixed up but rather your expectation doesn't match how Home Connect calls these data points. The integration follows the names provided by the API.

**Comment by Pawlde** [comment]
This might be the case, but in the home connect Android app the values are shown in the expected combination.

Either Bosch has this incorrectly labeled within their own firmware (and not decided to correct it there but the app development team did a work-around), or something else is mixed up.

Sorry to say that, but I think my expectation is that the meaning of the written label matches up with the shown value in the HA HMI. As described above, this is not the case right now.
The usability and clarity would be much improved if this could be switched (maybe at least until Bosch decides to clean up the problem on their side)

**Comment by ekutner** [comment]
The key approach of the integration is that it is generic. It doesn't know anything about any specific appliance or any specific operation, everything is dynamically created based on the input received from the API. If Home Connect provides the wrong information or has a bad naming convention for certain entities there is nothing the integration can do about it but you always have the option to rename entities in the HA UI.
