### ISSUE TITLE
Energy meter

### ISSUE THREAD

**Issue by Dominic-070** [ekutner/home-connect-hass#392]
I would like to have a energy meter (kWh) entity, there is in the home connect app a energy meter and water meter for the dishwasher.

![Screenshot_20240616_204904_Home Connect](https://github.com/ekutner/home-connect-hass/assets/62623885/07f88a96-b411-49f3-a356-f302c1ca00d5)

**Comment by ekutner** [comment]
This has been discussed in #379. The integration only shows information exposed by the Home Connect API. This energy information is not made available by the API so not going to be made available by the integration.
