### ISSUE TITLE
Deleting/Refreshing a device

### ISSUE THREAD

**Issue by mirakels** [ekutner/home-connect-hass#399]
I have this washing machine connected to home connect and it is visible in the home connect app.
Home connect app has an entry for the device but all entities show 'unavailable'.
Tried to press refresh in  the special home connect device, or reload the integration but nothing changes for the washing machine.

A few weeks ago the machine was offline for a while and I had to remove it from the home connect app and reconnect it which apparently succeded. But somehow home connect alt does not properly see it. Maybe it received an new home-connect-internal new object id or that is not picked up by home connect alt???

When clicking on an entity with 'unavailable' data it suggest to delete the entity so I did for all entities attached to the device. Now home connect alt still shows the device but without any fields/entities.

I wanted to explicitely delete the device from the integration hoping it would rediscover it, but there seems to be no way to delete it. Homeassisant docs say there should be a 3-dots menu with a delete option on the device-info card, but those dots are not in any of the home connect alt  device-info cards.

So what can I do to get the washing machine back in the intgration...

Version 1.1.7

**Comment by ekutner** [comment]
You can't delete an appliance, you can delete the whole integration but I doubt it will solve your problem.
When reporting an issue please follow the instructions and attach the log file.

**Comment by mirakels** [comment]
Thanks for your comment ekutner. 
I figured what was the issue. I even removed the devices from the .storage/config_entries so it was totally gone in homeassistatn and home_connect_alt.

 The device was visible in the home connect app so I new it was defined. I also saw it in the debug info of the /api/homeappliances call, but could not understand why it did not show up as new device. 

By adding some additional debug calls in home_connect_async I found the issue. The device was basically switched off and hence 'not connected'. After being sure it was connected and showed as 'on' in home connect app, home_connect_alt was able to get all the device info again.
 
Maybe this additonal debug code may be usefull:

```
diff --git a/home_connect_async/homeconnect.py b/home_connect_async/homeconnect.py
index bc76bc1..ff3a1b9 100644
--- a/home_connect_async/homeconnect.py
+++ b/home_connect_async/homeconnect.py
@@ -157,6 +157,7 @@ class HomeConnect(DataClassJsonMixin):
                 if 'homeappliances' in data:
                     for ha in data['homeappliances']:
                         haid = ha['haId']
+                        _LOGGER.warning("Home connect processing: %s %s", ha['name'], haid)
                         if  haid in self._disabled_appliances or haid.lower().replace('-','_') in self._disabled_appliances:
                             continue

@@ -177,6 +178,8 @@ class HomeConnect(DataClassJsonMixin):
                         elif haid in self.appliances:
                             _LOGGER.warning("The appliance (%s) is disconnected when loading for the first time", haid)
                             await self.appliances[haid].async_set_connection_state(False)
+                        else:
+                            _LOGGER.warning("The appliance (%s) is disconnected and not in appliance list yet. Wait for connected state.", haid)

                 # clear appliances that are no longer paired with the service
                 for haId in self.appliances.keys():
```
