### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by pvillanyi** [ekutner/home-connect-hass#40]
This integration also doesn't refresh while the home connect app can show the state of the Bosch device.
It worked well for a few days.

Ver. 0.4.9

## Configuration

Standard made by the integration

Add your logs here.
{ "appliances": {} }
11:50:54 – (ERROR) Home Connect Alt (custom integration)

I've found nothing in the logs regarding the integration

Edit 07.06.

Logger: custom_components.home_connect_alt.button
Source: custom_components/home_connect_alt/button.py:237
Integration: Home Connect Alt ([documentation](https://github.com/ekutner/home-connect-hass), [issues](https://github.com/ekutner/home-connect-hass/issues))
First occurred: 19:25:30 (1 occurrences)
Last logged: 19:25:30

{ "appliances": {} }

**Comment by ekutner** [comment]
The integration should update in real time if it doesn't you need to provide the debug log. See the README for instructions on how to do that.

**Comment by pvillanyi** [comment]
I've added the config for debug and pressed the debug button.
But wehere can I find the debug log?
In HA Core log I've only found the one entry added to issue description...

**Comment by ekutner** [comment]
You need to restart HA after adding the debug configuration.
The dubug information will be in the regular HA log.

**Comment by ekutner** [comment]
By the way, before you do any of this, I suggest you remove the integration from HA then add it back again.

**Comment by pvillanyi** [comment]
After removing the integration and adding it again, it only installs the home connect service the dishwasher not. The dishwasher is still connected in the mobile app. It's getting worse

**Comment by ekutner** [comment]
Make sure the mobile app sees the dishwasher as active when it is NOT connected to your home wifi (turn off the wifi on your phone so it connected through your mobile carrier). If the app doesn't see it as active then you need to reconnect it to the HC service.

**Comment by pvillanyi** [comment]
As I wrote: the Home Connect mobile app still sees the dishwasher and can still show and controll its functions.
The HOme Connect Alt integration did show it at first try and worked exelently for a few days. But on the weekend, without any changes in HA (really nothing was changed), it stopped working. After your advice to delete the integration and add it again, it just adds the Home Connec Service with its 3 entities but douesn't connect to the dishwasher....
I have no idea what could I do...

**Comment by ekutner** [comment]
Please upload the debug log

**Comment by ekutner** [comment]
The README explains how to enable debug mode.

**Comment by pvillanyi** [comment]
I know, but I can't get it working, neither the integration...
I've deleted it all.
I could reinstall the oroginal home connect, but it's still not refreshing.
Your alternative only creates its 3 entities, but not the dishwasher it self.

**Comment by ekutner** [comment]
I can't really help without the log but my best guess is that your appliances are not connected to the HC service.

**Comment by pvillanyi** [comment]
The funny thing is, The device is communicating with the HC app.
The official HC integration creates the entities for the device but dont refreshes.
Your alternative was working fantastic for 2 days and since then it's not even crerating the entities.

**Comment by ekutner** [comment]
The HC mobile app connects directly to the appliance when they are on the same network, it doesn't use the official API. You have to test it with WiFi turned off on your phone.

**Comment by pvillanyi** [comment]
It connects also without wifi.
The funny thing is, after I've started dishwasher and connected without wifi, I could add the integration :-D
I'll have a look on the sensors on next use....
I'm missing the program percentage, but lets see when it runs...

**Comment by pvillanyi** [comment]
In the logs I've found:
Logger: aiohttp_sse_client.client
Source: /usr/local/lib/python3.9/site-packages/aiohttp_sse_client/client.py:238
First occurred: 06:53:26 (9 occurrences)
Last logged: 09:56:29

fetch https://api.home-connect.com/api/homeappliances/events failed: 429

**Comment by ekutner** [comment]
429 is a rate limit error. Only the debug log has enough information to figure out what is the source of the problem.

**Comment by pvillanyi** [comment]
The next day it stopped working...
Really how can I present you the debug log?

**Comment by ekutner** [comment]
it's called home-assistant.log and located in the config folder

**Comment by pvillanyi** [comment]
[home-assistant.log](https://github.com/ekutner/home-connect-hass/files/8966450/home-assistant.log)

**Comment by ekutner** [comment]
The log indicates that you are getting blocked because of rate limits on the HC API. If you installed version 0.5.0 of the integration the Home Connect Status sensor should be in BLOCKED state and report how long until the block is lifted. Once it is no longer blocked this will start working again, however it is likely that you will be blocked again. When that happens send me the log again and I'll try to see why you ar getting blocked and if there is anything that can be done about it. Please note that if you have more than 3 appliances it is almost impossible to avoid getting blocked because the API call limit is very low.

**Comment by pvillanyi** [comment]
All sensors are unavailable
[home-assistant.log](https://github.com/ekutner/home-connect-hass/files/8969000/home-assistant.log)

**Comment by ekutner** [comment]
Please add the following line to the home_connect_alt section config of your configuration.yaml file:
log_mode: 7

Then restart HA, wait until the integration status goes to READY and then upload the new log.

**Comment by pvillanyi** [comment]
There it is
[home-assistant.log](https://github.com/ekutner/home-connect-hass/files/8969596/home-assistant.log)

**Comment by ekutner** [comment]
Your dishwasher is either powered off or completely disconnected from the HC service. It has to be connected and powered on for the integration to see it.

This is the response being received from HC:
```
{
  "data": {
    "homeappliances": [{
      "name": "Mosogatógép",
      "brand": "Bosch",
      "vib": "SMS4HVW31E",
      "connected": false,
      "type": "Dishwasher",
      "enumber": "SMS4HVW31E/34",
      "haId": "401020519687003338"
    }]
  }
}
```

The relevant part is the connected property have a value of false. At this state the integration can't get any information about it from the HC API so all the sensors will have a a value of "unavailable"

**Comment by pvillanyi** [comment]
Its on a normal standby
It looks in Home Connect also disconnected.... :-(
If I start it (in theory, because I'm working) it changes to connected and shows any info in Home Connect. But HA integration can't get the infos. I don't know what went wrong or what Bosch has changed, but this worked with the original integration for months... after that crashed with your alternative for a week and since then I'm strugling with it...
I think the best solution would be a vibration or power sensor....

**Comment by ekutner** [comment]
I'm afraid I can't really help with why it's happening but either it is loosing connectivity with the HC servers (not connected to wifi or maybe other internet issue) or there is some problem with its registration in HC so I would try to remove it from the service completely and reconnect it again.

**Comment by pvillanyi** [comment]
After reseting the wifi it worked for a day and now its unavailable again...
Despite that in the HC app I can see the status although I'm at work and not in the home wifi.
I have also installed the actual version...
Reloading the integration didn't work

**Comment by ekutner** [comment]
Sorry, I don't know why it's happening but if the API reports the appliance as disconnected there is nothing I can do about it in the integration. You may want to open a support ticket about it in the HC web site.
Since there is nothing I can do about it I'm going to close this issue now. If you open a ticket and get new information you are welcome to reopen it.
