### ISSUE TITLE
Reset Bosch dishwasher from the integration (Simulate pressing power button for 4 seconds)

### ISSUE THREAD

**Issue by ahmadyusuf** [ekutner/home-connect-hass#401]
**Is your feature request related to a problem? Please describe.**
In my Bosch dishwasher, I can reset the current program by pressing the power button continuously for 4 seconds, this allows me to change the program attributes after starting it.

**Describe the solution you'd like**
I would like to be able to do the same thing (reset) through the integration so that I can programmatically change the program to eco program for example if the dishwasher was started at night

**Describe alternatives you've considered**
Unfortunately, I have no alternatives

Dishwasher Model: SMS6HCB01A by Bosch
Integration version: 1.1.6

**Comment by ekutner** [comment]
You can use the stop_program service to stop the current program, assuming that is supported by your appliance.

**Comment by ahmadyusuf** [comment]
Yes, stop_program service works for the same purpose, thanks for your help
