### ISSUE TITLE
Add more info from the latest Home Connect update.

### ISSUE THREAD

**Issue by yuvalabou** [ekutner/home-connect-hass#403]
The last app update introduced new information regarding devices such as number of cycles, average power and water usage.
U do not actually know if this info is available from the API but this can be a nice addition.

Attached an image for a better clarification.
![Screenshot_2024-07-26-10-50-03-33_9f7c1d68ad2a6fad3b248f3ec2a58ba4.jpg](https://github.com/user-attachments/assets/2ffcfc78-a7cf-4e1d-b214-e88cd014a25f)

**Comment by ekutner** [comment]
The integration is automatically creating entities that are exposed by the API, so if it was available in the API it would have been automatically added by the integration. This feature request should first be directed to Home Connect, so I'm going to close it for now.
