### ISSUE TITLE
Select up to two functions for the Favourite button on your hob.

### ISSUE THREAD

**Issue by cgilis** [ekutner/home-connect-hass#407]
**Is your feature request related to a problem? Please describe.**
There is an option on my hob to use a favourite button, could be nice if you are cooking and you want to turn on an automation. 

But if i press the buttons there is nothing visible in the log of HA. 

Any chance you can look into this? :) Thx!!

![IMG_3CB1C60F7837-1](https://github.com/user-attachments/assets/b1fec4b3-606f-4ee4-b664-9e29f2e6d716)

**Comment by ekutner** [comment]
If you enable debug logging and don't see anything coming through when you press those buttons then they don't publish any events and the integration can't know they were pressed.

**Comment by cgilis** [comment]
I meant in the device log. Maybe there is an event in the logs of HA. 

Will export the logs when I’m back.
