### ISSUE TITLE
Camera Support for Oven

### ISSUE THREAD

**Issue by DarkByteZero** [ekutner/home-connect-hass#408]
**Is your feature request related to a problem? Please describe.**
I see no mention of camera support in de docs.

**Describe the solution you'd like**
Add Support for Camera of the new Ovens.

**Additional context**
Example Oven that has a camera: [HN978GQB1](https://www.siemens-home.bsh-group.com/de/de/product/studioline-backoefen/HN978GQB1)

**Comment by ekutner** [comment]
Cameras are not supported for ovens by the API

**Comment by joeblack2k** [comment]
GET /api/homeappliances/{haId}/images only with a token that has: "IdentifyAppliance Oven"
