### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by stefanhintermayr** [ekutner/home-connect-hass#410]
In fact, I always thought that 'Alt' means old and I always thought why this integration is being continued. The fact that this is all called "alternative" is a thousand times better than the original. It should be given more recognition. So maybe "HomeConnect alternative" after all. :-)

**Comment by christianreiss** [comment]
In english alt is short for alternate/alternative.
I think you might get confused with the german word "alt" as in "old".

I think on some level each word might be something else in some language, so let's stick to pure english here.

**Comment by ekutner** [comment]
Indeed.
It seems people manage to find it and renaming the integration will create a huge mess, so I think we'll have to stick with the current name.
