### ISSUE TITLE
Missing SetPoint Temperature for ovens

### ISSUE THREAD

**Issue by Sascha-L** [ekutner/home-connect-hass#413]
Hi,

the Home Connect API offers a SetPoint Temperature for an oven. Could you please add this value? Currently your integration only shows the current cavity temperature. Previously I used openHAB where both temperature values are available, so it would be nice, if you could add this value too. With both values you are e.g. able to send a notification that the oven is preheated.

**Comment by ekutner** [comment]
The integration adds all the entities exposed by the API automatically. If it is available by the API it would have already be exposed as an entity in HA, make sure you didn't miss it. If it's not there and you believe it is exposed by the API then it could be a bug (very unlikely) but for that I'm going to need to see a log or documentation that shows it exists + the debug logs of the integration.

**Comment by Sascha-L** [comment]
Hi, thanks! I found the entity! The automatic naming was wrong, the entities name was "Cavity Temperature" and not "SetPoint Temperature" that's why I didn't recognized it. So everything is ok.

**Comment by ekutner** [comment]
The name comes from the API, to be honest, I'm not even sure what they mean by it.
Anyway, I'm happy to hear it's there and will be closing the issue now.
