### ISSUE TITLE
Dishwasher Progress Percentage

### ISSUE THREAD

**Issue by Mwalton4uk** [ekutner/home-connect-hass#417]
**Is your feature request related to a problem? Please describe.**
I am creating a progress bar for my Dishwasher but when the programme is complete, the "Bosch Dishwasher - Current programme progress" entity is set to unavailable and no longer provided.

**Describe the solution you'd like**
Have the entity revert back to 0% or stay at 100%

**Describe alternatives you've considered**
an automation to manually set it or using a helper

**Comment by ekutner** [comment]
Entities become unavailable when they are no longer provided by the API and therefor their state becomes undetermined. This behavior is not going to change. You can check for this state in your automation or create a custom sensor with a template that would return whatever value you want when the entity is unavailable.
