### ISSUE TITLE
Support connecting to simulator endpoint

### ISSUE THREAD

**Issue by victpork** [ekutner/home-connect-hass#418]
**Is your feature request related to a problem? Please describe.**
It would be nice if I could connect to the simulator endpoint so I don't need to wait for another laundry cycle to debug my cards

**Describe the solution you'd like**
A switch that allow user to change endpoint to simulator.home-connect.com

**Describe alternatives you've considered**
Create entities linked to simulator appliances with a switch in UI

**Additional context**
N/A

Thanks for reading

**Comment by ekutner** [comment]
Nice idea. It's now supported in version 1.1.8, but read the README for caveats.
