### ISSUE TITLE
Failed to get a valid response from Home Connect server

### ISSUE THREAD

**Issue by bobbinz** [ekutner/home-connect-hass#426]
Now I'm not suggesting this is an issue with the code but am reaching out to see if anybody has the same issue!

I'm on Core 2024.10.2 with 1.1.9 of Home Connect Alt.  It has worked since the updates so I'm confident it's nor that.

Anyway - I restarted for some other reason today and when it came back the Home Connect Appliances were all busted:

> Failed to load data from Home Connect (('Failed to get a valid response from Home Connect server', 902, None, None, None))
> Traceback (most recent call last):
> ```
>   File "/usr/local/lib/python3.12/site-packages/home_connect_async/homeconnect.py", line 150, in async_load_data
>     response = await self._api.async_get('/api/homeappliances')
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/home_connect_async/api.py", line 119, in async_get
>     return await self._async_request('GET', endpoint)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/home_connect_async/api.py", line 114, in _async_request
>     raise HomeConnectError("Failed to get a valid response from Home Connect server", 902)
> home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)
> ```

Their status pages all say everything is fine and the app works (as well as it ever has).  Maybe it'll just come back in time.

I just wanted to reach out and see if anybody else had this issue and apologise if there is a better forum for it than here!

**Comment by bobbinz** [comment]
The "Home Connect Service Home Connect Status" entity shows LOADING_FAILED by the way after INIT, which is entirely true and seems to be working correctly :)

**Comment by Pd66** [comment]
the same here

**Comment by geoced** [comment]
yep same here!

**Comment by AndiTails** [comment]
+1
Home Connect app is working. HA is not.

**Comment by N3rdix** [comment]
I would rate this as a temporary server issue, but an integration error...

![image](https://github.com/user-attachments/assets/65bda851-8488-47c7-a264-c54d8cf5b785)

**Comment by BeJaHome** [comment]
Is there a way to communicate directly with my appliance? The dishwasher is in my home, so is my HA. So don’t need the cloud….

**Comment by ekutner** [comment]
Since nothing has changed in the integration it is indeed most likely a server issue. You should check the app while NOT connected to wifi, which forces it to use the cloud. See the README for details. If it works while disconnected from wifi the please upload a full debug log with Log Mode=7 (see the README for details on that as well).

**Comment by MaximumFish** [comment]
Can confirm there's a message in the app saying:

>Appliance connections will be working again shortly. Sorry.

**Comment by BeJaHome** [comment]
Still nothing in Home Assistant. Restart HA or even reboot HassOS doesn’t work, Home Connect app works fine. How to get my appliance back in HA?

![IMG_9294](https://github.com/user-attachments/assets/c2c71f80-a849-49d5-956e-440b084b264e)

**Comment by N3rdix** [comment]
It's working again, services back online.
Just had to reload the integration once

**Comment by BeJaHome** [comment]
Perfect, it works again indeed

Groet,
John Janken

(sent from mobile)

On 17 Oct 2024, at 06:30, Nerdix ***@***.***> wrote:

﻿

It's working again, services back online.
Just had to reload the integration once

**Comment by SBerg1980** [comment]
I still have the problem, reboot, reload stil the message: LOADING_FAILED

**Comment by BeJaHome** [comment]
Same here. It worked again earlier today (like I mentioned in the thread), but now problem returned.

Online in Home Connect app.
Offline in Home Assistant integration. Reboot / restart doesn’t help.

Groet,
John Janken

(sent from mobile)

On 17 Oct 2024, at 18:10, SBerg1980 ***@***.***> wrote:

﻿

I still have the problem, reboot, reload stil the message: LOADING_FAILED

**Comment by N3rdix** [comment]
But the app as well reports t
That they have issues, so just be patient. 
Not an error of the integration as long as the don't change the APIs 😉

**Comment by bobbinz** [comment]
Service is back, dishwasher working, oven(s) less so!

**Comment by idominiki** [comment]
Still have problem. Status for me is Loaded but no device is available.

**Comment by canedje** [comment]
I do have the same problem
LOADING_Failed

**Comment by pmrosa-classes** [comment]
I just added my first Home Connect Appliance (Dishwasher) and had lots of problems to add the appliance to my account, it failed for 5 or 6 times with http errors. Just my luck to use Home Connect the first time when they're having problems :-D .. I had already configured this integration and reached this issue because the integration is giving me LOADING_ERROR... thanks guys for the pointer to the problem (yes, I have it on the app also).

**Comment by BeJaHome** [comment]
This week the remote control has become totally unreliable and unusable and they don’t seem able to resolve. I use the api to control my dishwasher based on cheap electricity hours and a few other things. All my Miele devices run smoothly, but Siemens is really crap since this week.

Really hope that they solve these issues fast, otherwise the next appliance I buy will certainly not be a Home Connect based device like Siemens or Bosch.

Groet,
John Janken

(sent from mobile)

On 18 Oct 2024, at 19:18, pmrosa-classes ***@***.***> wrote:

﻿

I just added my first Home Connect Appliance (Dishwasher) and had lots of problems to add the appliance to my account, it failed for 5 or 6 times with http errors. Just my luck to use Home Connect the first time when they're having problems :-D .. I had already configured this integration and reached this issue because the integration is giving me LOADING_ERROR... thanks guys for the pointer to the problem (yes, I have it on the app also).

**Comment by oywino** [comment]
It was working fine until I restarted Home Assistant today for the 2024.10.3 update. 
Now all connections to Home_Connect_Alt is broken.

**Comment by kpoppel** [comment]
Still an issue here too, but reassuring others see the same thing.  It would seem some instability on the Siemens side is affecting this.  The mobile app lost the appliance, then it reappears some time later, and Home Assistant also has sporadic lapses at least for the past two days.
![image](https://github.com/user-attachments/assets/5c7ef44b-2a15-4bc4-a5b9-ec272963fe5d)

A fully off-line control would be truly great for Home Assistant.

**Comment by bobbinz** [comment]
I wonder if anyone at home connect has noticed yet. Their status page still
thinks everything is fine.
Adam
Sent on the go!

**Comment by oywino** [comment]
Siemens clearly has trouble today:
![image](https://github.com/user-attachments/assets/2007e0aa-b213-46a3-8eaf-a2f0b31d3836)

It's so sad that a big company like Siemens isn't able to perform better. Question is; Can we trust them anymore?

**Comment by mike4001** [comment]
Same here.

Basically it happened after the HA 2024.10.3 update .... but don't know if this has something to do with it. Maybe a coincidence.

Official app still works but has the system outage message at the top.

Now I get the 429 error of rate limit but I reinitialised the integration a couple of times. Probably the API servers also did not like that ;-)

**Comment by deluxestyle** [comment]
I‘m still on 2024.10.2 and have the same issue

**Comment by oywino** [comment]
> Now I get the 429 error of rate limit but I reinitialised the integration a couple of times.

Where did you see the 429 wire code?  And where do you reset the rate limit?

**Comment by von-Chaps** [comment]
My Home Connect app is configured to _only_ use the cloud connection (not local) due to VLAN config. I can tell you that the app is experiencing all the same connectivity issues that Home Assistant is. The fault certainly appears to be with the Home Connect back-end and not with this integration. It's been on/off (but mainly off) for a few days now. It is not working right now. I sent a support enquiry last night, but have not had any kind of reply. To be honest, these days, I don't expect to ever hear back from them, but I'll post here if I do.

**Comment by BeJaHome** [comment]
Also the cloud isn’t working: can’t reach my Siemens appliance in the HC app while my phone is on the mobile network. It’s only accessible in the HC app while connected via local wifi (i.e. same wifi as the Siemens). With that, also the HAss integration (Homey users most likely suffer as well) is dead while depending on the HC cloud. And now it’s weekend, so most likely no-one is available to solve the problem. I hate cloud based integrations, so hopefully a one skilled HAss integration developer succeeds in making a good (HACS) integration that works locally: both my HA and Siemens appliance are on the same local wifi network, so cloud is redundant.

**Comment by BeJaHome** [comment]
in reply to @von-Chaps: 

Anyone who is in doubt to buy Siemens, Bosch or Miele: my advice is to go for Miele. I never had these issues with my 3 wifi connected appliances.

> My Home Connect app is configured to _only_ use the cloud connection (not local) due to VLAN config. I can tell you that the app is experiencing all the same connectivity issues that Home Assistant is. The fault certainly appears to be with the Home Connect back-end and not with this integration. It's been on/off (but mainly off) for a few days now. It is not working right now. I sent a support enquiry last night, but have not had any kind of reply. To be honest, these days, I don't expect to ever hear back from them, but I'll post here if I do.

**Comment by julian4646** [comment]
Same issue as everyone else (in Canada) - my iphone Home Connect app shows a notification saying "Connection Outages" - Oct 19 at 73-am" - "Appliance connections will be working again shortly, Sorry" - so it looks like their end not ours.

**Comment by rmkew377** [comment]
Still Error 502-Bad Gateway.
Android App & Integration still don't work. 
Status-Website says. "System is up and running!"
The "Contact"-Web-Page shows variables of the fields like [cso.contact.form.lbl.email] instead of "Email".
and doesn't work too (sending request leads to error..)
Seems to be a bigger problem....wondering if they are working on it ... at weekend.

**Comment by BeJaHome** [comment]
I’m in Europe (NL), same issue. Seems global.
Groet,
John Janken

(sent from mobile)

On 19 Oct 2024, at 13:33, julian4646 ***@***.***> wrote:

﻿

Same issue as everyone else (in Canada) - my iphone Home Connect app shows a notification saying "Connection Outages" - Oct 19 at 73-am" - "Appliance connections will be working again shortly, Sorry" - so it looks like their end not ours.

**Comment by multinet33** [comment]
Same in France. App on IS is KO too

**Comment by gatogatogato** [comment]
Same in Switzrerland, joining this thread for updates in case anyone finds anything. Siemens seems to have messed it up big time.

**Comment by canedje** [comment]
Mine is working again

**Comment by deluxestyle** [comment]
Mine is still Not working

**Comment by canedje** [comment]
> Mine is still Not working

I did have to sign in in de app again and reload de home connect integration

**Comment by BeJaHome** [comment]
HA integration and HC app (outside lan) work again. So apparently the HC cloud server also.

HA integration must be reloaded and HC app must be restarted to connect to the appliances.

Groet,
John Janken

(sent from mobile)

On 19 Oct 2024, at 22:30, canedje ***@***.***> wrote:

﻿

Mine is still Not working

I did have to sign in in de app again and reload de home connect integration

**Comment by deluxestyle** [comment]
Mine is now working also.

**Comment by deluxestyle** [comment]
It is working but still in my logs I see following error

`
fetch https://api.home-connect.com/api/homeappliances/events failed: 503
`

**Comment by BeJaHome** [comment]
Have you restarted the app or the integration from the system that you use (HA, Homey or whatever system you use)?

**Comment by oywino** [comment]
> It is working but still in my logs I see following error
> `fetch https://api.home-connect.com/api/homeappliances/events failed: 503`

Same here. Is there anyway possible to understand these "cryptic" error messages coming from HA?

**Comment by C0rish** [comment]
503 is a default Apache "service not available" error code. It's not an error / bug with this integration. The service API from Bosch / Siemens seems to be not 100% healthy yet, although it is working a lot better the last hours.

**Comment by BeJaHome** [comment]
And the connection is broken again….

Groet,
John Janken

(sent from mobile)

On 20 Oct 2024, at 11:34, C0rish ***@***.***> wrote:

﻿

503 is a default Apache "service not available" error code. It's not an error / bug with this integration. The service API from Bosch / Siemens seems to be not 100% healthy yet, although it is working a lot better the last hours.

**Comment by osulivanDE** [comment]
Not sure if it is a coinsidence but from the time i re-logged into my Home Connect App (was logged out for no forseable reason) my Home Connect integration could pull Data again from my devices.

**Comment by sroebert** [comment]
> Not sure if it is a coinsidence but from the time i re-logged into my Home Connect App (was logged out for no forseable reason) my Home Connect integration could pull Data again from my devices.

That's just confirming the unreliable state the service is in at the moment. It is incredibly flaky, working from time to time, but mostly it is not. I am not using this plugin, but my own implementation, and also having the same issues with the service.

**Comment by lauris-nl** [comment]
Hi all,  

Today I told my wife NOT to order a Siemens tumble dryer. Until this problem is resolved and the remote API server behaves bravely.  (for a weer or two) 
And not like an ape!

**Comment by von-Chaps** [comment]
Seems like the service is back in the room now. Coincidentally, the Home Connect app prompted me to give feedback in Google Play during the outage, so I left a scathing review. Someone was on it pretty quick to apologize and state that the service was down over the weekend (duh). No explanation as to why.

I said before that I raised a support issue in the app too. I did actually get a response from them;

> Thank you for contacting the Home Connect Team.
> 
> I'm afraid we have had some issues over the last few days affecting the connection to appliances.
> 
> I apologise about any inconvenience caused by this.
> 
> The issues have now been resolved.
> 
> If you require any further assistance, please do not hesitate to contact us back.
> 
> Kind regards
>
> Mark Fortescue
> Customer Service Advisor

Again, no explanation of what happened, but I didn't expect that. However, it does seem that plenty of people were aware that the service was badly broken, so there's that I suppose.

As others have said, it'll be a while before I consider another Home Connect appliance (Bosch, Siemens...)

**Comment by oywino** [comment]
> Seems like the service is back in the room now. 
> As others have said, it'll be a while before I consider another Home Connect appliance (Bosch, Siemens...)

Thank you for posting this info.
Regretfully, SIEMENS is nether worse nor better that anyone else.  The fact that service do run into trouble from time to time, is understandable and acceptable. What is NOT acceptable, is that they fail to post correct info on the opening page of their app (and elsewhere). We should have had a "Service status" page we could visit.
All I had in my app was a note claiming that there had been an outage on my side!  I interpret this as an attempt to blame me for my problems.  This is where SIEMENS fail and becomes inferior.

**Comment by rmkew377** [comment]
Additional info:
In my case, when contact with the server was restored, the app requested an update to the dishwasher firmware.
This could only be started via Bluetooth with the cell phone with app was right next to the dishwasher. 
The door status is now reported again, but I can't say yet whether the functionality has been completely restored.
What's really sad is that Siemens could inform registered users via email if they have major adjustments or outages. I'm now also considering whether another Siemens product with Homeconnect would be an option for me.

**Comment by von-Chaps** [comment]
> Thank you for posting this info. Regretfully, SIEMENS is nether worse nor better that anyone else. The fact that services do run into trouble from time to time, is understandable and acceptable. What is NOT acceptable, is that they fail to post correct info on the opening page of their app (and elsewhere). We should have had a "Service status" page we could visit. All I had in my app was a note claiming that there had been an outage on my side! I interpret this as an attempt to blame me for my problems. This is where SIEMENS fail and becomes inferior.

Of course, you are absolutely right. Goes without saying really, cloud services are unreliable andd unpredictable

I would use the local connection, but my oven is on a different VLAN to Home Assistant, so I don't think they can communicate.

**Comment by C0rish** [comment]
> Of course, you are absolutely right. Goes without saying really, cloud services are unreliable andd unpredictable
> 
> I would use the local connection, but my oven is on a different VLAN to Home Assistant, so I don't think they can communicate.

The, or better say an open, local connection would be awesome. The current implementation is lacking this feature for anything other than the original app.

But I think time will tell... Remember my words: One day we will control those additional smart features (which of course almost all of them are also controllable directly on the device itself - without an app). Where Siemens/ Bosch will help us to do so... Or not. 

But to your question: You CAN use the local mode in the original app, although your devices are on different VLANs. You simply have to add an per device IP specific route from VLAN A (where your app is in) to VLAN B (where your device is in). I think the app will try to contact the devices locally via IP and uses it, in case the cloud is not available.

Try it out :)

**Comment by BeJaHome** [comment]
This is what Home Connect support responded on my complaint. So everybody on the globe is wrong, and they are right. Well, well…

Message ID: ***@***.***>

Your dishwasher is connected stably to our server and should therefore also be temporarily available.
There are no green devices connected to our server.
This often occurs because your router blocks this signal.
The Home Connect device cannot establish a correct connection to our Home Connect servers.

This can be a surprising door for your Home Connect devices by activating “independent port sharing” or “UPNP” in your router, opening the correct port forwarding rules in your router to set to your home connect device.
It is also important to enable the Multicast function in your router so that Wi-Fi devices can make separate contact with each other.

The correct port forwarding rules are:

Port: 443TCP
Port: 80 TCP
Port: 8080TCP
Port 123UDP

You can then check the connection status of your device with our Home Connect servers under the device settings in the app and then under the heading network connection. Both lines to the cloud should be green in color here

**Comment by BeJaHome** [comment]
Problem returned. Anyone else who has issues too?

**Comment by lauris-nl** [comment]
Yes for 9 hours now

**Comment by deluxestyle** [comment]
mine is working fine

**Comment by BeJaHome** [comment]
@deluxestyle also remotely, i.e. when NOT connected to the same home network as the appliance, like via HC app over 3G/4G/5G or when using a home automation system like Home Assistant or Homey?

**Comment by deluxestyle** [comment]
yes, as I'm controlling it direct via home assistant. also the HC app works outside of my Wifi

**Comment by deluxestyle** [comment]
I had a strange issue last week. my dishwasher lost the connection to my wifi. I have a fritzbox and I had to change my encryption to only WPA2 and not as before WPA2/WPA3.

**Comment by ekutner** [comment]
It seems that the HC service has been stable for a while now so I'm going to close this issue
