### ISSUE TITLE
404 Not Found???

### ISSUE THREAD

**Issue by vapury** [ekutner/home-connect-hass#427]
404 Not Found: Requested route ('hca-reu-production.hcf-bshg.com') does not exist.

Is this problem with homeconnect server?

**Comment by sthomsen1** [comment]
Yes, there seem to be problems with the Home Connect backend service at the moment. I also get the error sometimes, sometimes it works, but then the next error comes until it tries to redirect me back to my Home Assistant instance with the error code “Backend service (HCA) currently not available”

**Comment by disruptivepatternmaterial** [comment]
I just keep wondering if all us hackers and smart people of the internet can figure out how to create a proxy that makes all these things local. I have been sniffing and hacking the traffic from these appliances and it is nothing overly special. There is no reason we cannot communicate with them locally if we can PITM well enough...if we could create a framework based on nginx or something it is all just http/json...so many of these stupid things need a solid solution that is local only...

**Comment by EnricoBettella** [comment]
Can confirm Home Connect services are down, and the official app won't load too.

**Comment by C0rish** [comment]
> I just keep wondering if all us hackers and smart people of the internet can figure out how to create a proxy that makes all these things local. I have been sniffing and hacking the traffic from these appliances and it is nothing overly special. There is no reason we cannot communicate with them locally if we can PITM well enough...if we could create a framework based on nginx or something it is all just http/json...so many of these stupid things need a solid solution that is local only...

There is something going on... https://github.com/hcpy2-0/hcpy

But it's not "production ready" yet. But maybe this lovely home assistant application can implement such a mechanism?

**Comment by edstrinova** [comment]
> Can confirm Home Connect services are down, and the official app won't load too.

The App is back online - home-connect-hass unfortunately not
