### ISSUE TITLE
Local communication with appliances like mobile app does

### ISSUE THREAD

**Issue by michalk-k** [ekutner/home-connect-hass#430]
**Is your feature request related to a problem? Please describe.**
Bosch mobile app can connect the appliances both ways: through cloud and locally. 

**Describe the solution you'd like**
Is it in your roadmap to make use of direct communication with appliances?

Here is a GitHub project being an exploration of this possibility:
https://github.com/hcpy2-0/hcpy

**Comment by ekutner** [comment]
This has been discussed many times and not on the roadmap currently
