### ISSUE TITLE
No program phase available

### ISSUE THREAD

**Issue by michalk-k** [ekutner/home-connect-hass#431]
## Describe the bug
not sure if is it a bug or just a limitation.

I have Washer Gen8 (WGB244A0BY)
I cannot find a sensor providing information about the program phase
I found `laundrycare_common_option_processphase` but the only values it get assigned are `DetectingLoad` or unavailable.
I would expect here rising, spinning etc.

On the other hand mobile app shows those phases as expected.

Thank you for your work
With regards

**Comment by ekutner** [comment]
The values are based on what's coming from the API. If it's not getting updated there is nothing the integration can do about it.

**Comment by michalk-k** [comment]
Thank for the answer. 
I thought it might be a code shortcoming.
Otherwise we can close the issue.

**Comment by ekutner** [comment]
The integration doesn't do local communication, it only uses the API
