### ISSUE TITLE
Missing Operation State from History

### ISSUE THREAD

**Issue by michalk-k** [ekutner/home-connect-hass#432]
hello
I found that Operation State is missing from the history graphs.

I would like however to clarify some findings.

The value of Operation State found in Developer Tools has form of: BSH.Common.EnumType.OperationState.Inactive 
I understand it's raw value coming from Bosch API.

On various places in HA it's shown just as Inactive.
Is it because of the provided translation or HA shorten those values?

Then I found, that those values are completely missing from history (see the last raw in history on screenshot below):

![image](https://github.com/user-attachments/assets/ac070303-1266-49be-a8a5-15b73cbce103)

In fact, I saw one, the most recent value when was active at that time. But not previous ones. 

The question is: is this something the integration component is responsible for? Or it might be a bug in the recorder/history?

**Comment by ekutner** [comment]
TBH I have no idea what HA decides to store and what not. The long term history (older than 10 days) is only for numeric values but I couldn't find any mention in the documentation for other values. In my own HA I do see previous values of this entity:
![image](https://github.com/user-attachments/assets/1b2e1d9a-0e13-46c6-8582-f086bd145360)

**Comment by michalk-k** [comment]
What version of HA do you use? I have 2024.10.4
It seems like history shows the state only if it's currently active. Otherwise, it doesn't show it.

The interesting thing is, that the `history-explorer-card` doesn't show it at all

![image](https://github.com/user-attachments/assets/7f966b34-31dc-46f6-81fa-12d5cef67ad3)

**Comment by michalk-k** [comment]
I've looked into sqlite tables... and seems this sensor is not registered at all. this could be the answer on why it shows only just active value

![image](https://github.com/user-attachments/assets/e8ce2158-ca65-4cdf-bc23-5431c549e823)

Do you have idea why this sensor isn't registered? 
I found no error in HA logs.
