### ISSUE TITLE
Entities default naming pattern and issues with Device renaming

### ISSUE THREAD

**Issue by michalk-k** [ekutner/home-connect-hass#433]
Currently, the default pattern for entity names  is prefixed by `$brand $appliance - `
It prevents HA from automatically shortening names on Device View. Making their names unreadable

![image](https://github.com/user-attachments/assets/8e0aae4e-40c0-454b-86d2-53d191a1a257)

If the beginning of entity name equals Device name, the prefix is stripped out.

Now question: what part of the system is responsible for renaming entities while renaming the device? I though that by renaming the device to match entity prefixes, I will clean up the Device page. Unfortunatelly it ended up with even bigger mess:

1. During renaming of the device from `Susicka` to `Bosch Susicka`, HA informed me, that no (out of 49 or so) entities will be renamed
2. Something opposite happened
3. All (most) entities have been renamed
a). Some some remained untouched (seems a few unavailable ones)
4. After some few forth-back attempts of device renaming I ended up with more prefixes of those entities: `Bosch Bosch Susicka`, `Bosch Susicka`, `Bosch Susicka Bosch`

Just wonder if should I raise an issue to HA Core, or if the renaming is done by the component, with the issue in applying the predefined pattern.

**Comment by z-vrba** [comment]
I see. It is a quite long time I have renamed it, but I think I have reinstalled the integration.

**Comment by michalk-k** [comment]
Thank you. 
Good to know that it's enough to wait.
I have an impression that Reload didn't make the job (to any of the entities).

**Comment by michalk-k** [comment]
Neither reloading nor restart helped.
I had to remove the integrated devices/entities (see screenshot) and re-add it afterwards
![image](https://github.com/user-attachments/assets/c1f965f3-e142-4050-b8cb-daa07aac8c99)


The problem with such approach is, that a user has no option to select the entity naming pattern before adding entities. And tbh at that step the new user has no idea about how device and entity names and their relationship.

BTW I found that user may want to change device name - the integration doesn't provide such option during adding the device. It uses name provided by API.

Fortunatelly (for me), after adding devices (thus their entities too) I changed the pattern, and it did work this time, renaming already existing entities. So I'm happy right now I achieved cleaner view.

Now I'm really confused, why changing had effect on entity names this time, just after adding them, while it wasn't working before. (btw hyphen in name pattern prevents HA from automatic prefix removal)

And let me ask again for device renaming process. If a user uses a device rename option, is it HA core code which renames entities, or it's integration code? Why changing a device name results in renaming entities leading to the mess described in the OP?  I just wanted to change device name to match prefix of already existing entity names.
The message which pops up, that no entity will be renamed is even more confusing. 

with regards

**Comment by ekutner** [comment]
As I mentioned, once you rename entities using the HA UI it takes over the names and they will be managed by HA, which will most likely create the kind of mess you experienced. Changing the name template through the integration's "configure" UI will take effect without requiring removing and re-adding the integration.

**Comment by michalk-k** [comment]
I didn't rename any entity using HA GUI. I tried to change either the device name, or the template.
It gave messy results. 

I don't know if the integration or HA is responsible for what happened. Maybe using non-ascii characters in the appliance name was causing the problem?

On top of that I suppose that the initial template should not contain a hyphen character, which might prevent the HA from shortening prefixes. 

Since I managed to resolve that by removing and re-adding the appliance and renaming with use ascii-only names it works to me as expected.

**Comment by ekutner** [comment]
How did you change the device name if not through the GUI?
Non-ascii is not a problem, everything is Unicode anyway.

Bottom line is that this feature exists for a very long time and I didn't get reports about problems with it, unless the names were changed manually in the GUI, in which case HA will override the name offered by the integration. 
Since it's working for you and as you suggested I'll close the issue now and reopen if I get additional complaints about it.

**Comment by ekutner** [comment]
The name template is indeed, as it's name suggest, for the entity name and not for its ID. I will not implement ID changes because I have a strong belief that IDs should be consistent and predictable, and HA requires them to be unique. The benefit of that is that you can remove and reinstall the integration and the IDs will remain consistent. The will also be consistent regardless of your choice of language. If you really want to, you should be able to change the IDs in the HA UI (I didn't test it but it should work).
