### ISSUE TITLE
misleading status "LOADING"

### ISSUE THREAD

**Issue by pswid** [ekutner/home-connect-hass#45]
I'm usung the latest integration version (v0.5.0-b1) with default config. I've noticed that `sensor.home_connect_status` can return value "LOADING" for many **hours** (of course, during this phase HomeConnect devices can not be used in HA). The problem is releated to API call limit, because official HomeConnect integration shows something like this in the log:
`homeconnect.api.HomeConnectError: {'key': '429', 'description': 'The rate limit "1000 calls in 1 day" was reached. Requests are blocked during the remaining period of 11914 seconds.'}`

Could you return more suitable status value in such cases (e.g. "BLOCKED'")?  Besides (as seen above) the API returns the reason and the time when the lock will be released. It would be great if the information about the reason (in this case the limit of 1000 queries per day was exceeded) and the date+time when the blockade will end was also returned. Such additional information could be returned via additional entities or even as "properties" of  `home_connect_status` sensor. What do you think?

**Comment by ekutner** [comment]
It makes sense.
I've added the blocked status + the block time as text to the sensor.  The exact reason it less important so I didn't add it.
If you are getting this error frequently please upload a full debug log with at least the 24h before the issue started. I'm trying to understand exactly when this happens and if there is anything I can do to reduce the number of calls the integration is making.

**Comment by pswid** [comment]
Great. BTW, today after update to v0.5.0-b2 (and new blockade, unfortunately) I noticed that `home_connect_status` sensor value is "None". Is this status reported by integration or HA itself?

![image](https://user-images.githubusercontent.com/78219494/172830505-33290ffe-c754-4894-989e-b28be965a812.png)

**Comment by pswid** [comment]
Status "none" might be related to another blockade, because in debug log I see many entries like this (more in attached file):

`[home_connect_async.api] HTTP Error 429 - Too Many Requests. Sleeping for 38 seconds and will retry`

[log1.txt](https://github.com/ekutner/home-connect-hass/files/8876606/log1.txt)

**Comment by ekutner** [comment]
This should be fixed in beta version 0.5.0-b4

**Comment by pswid** [comment]
Yes, it works! In case of blockade, `sensor.home_connect_status` shows e.g. `Blocked for 23:23`. But, wouldn't be better to calculate time when the blockade ends and just display "`Blocked until 14:50`"? Or even better - simply BLOCKED (in analogy to INIT, LOADING, LOADED, READY) but add an extra attribute `Blockade until` to the `sensor.home_connect_status` and return the time (or `none` if there is no blockade) via this attribute?

**Comment by ekutner** [comment]
Blocked until, will require dealing with days as well, so no, it's not better.
I'm not aware of any way to add additional attributes to a sensor, as far as I know it has just one value, so the way it is now is the simplest.
