### ISSUE TITLE
Missing features after update to 2.14

### ISSUE THREAD

**Issue by plaiddk** [ekutner/home-connect-hass#450]
Am I the only one that has noticed that a lot of sensor doesnt work anymore?

FinishInRelative, IdosActive1 etc is not functioning anymore after update of HACS to 2.14

Any solutions?

**Comment by plaiddk** [comment]
![fejls](https://github.com/user-attachments/assets/07b45e64-dc21-496b-874a-ab05df26d493)
As you can see here. Really many in unavailable state.

**Comment by seppi91** [comment]
Why this has been closed without any resolution? I actually face the same issue

**Comment by plaiddk** [comment]
I closed it because I read the FAQ which stated that if you have too many API calls or reach the rate limit you can get blocked for 24 hours. 

However I do still face the issue that the services are unavailable but as soon as I start my devices they become available. The strange part about that is that for some weeks ago the entities were available even though the device was off. So something has changed.
