### ISSUE TITLE
Diswasher gone after update to1.1.12

### ISSUE THREAD

**Issue by igita** [ekutner/home-connect-hass#455]
Hi,
after upgrading to 1.1.12 my dishwasher is gone.
I completely disabled the whole integration and set it up new - but only my washing machine and the home connect service is detected during the new setup.
in my home connect app from bosch both devices are visible.

After a downgrade to 1.1.11 - the dishwasher is back :-)

best regards

**Comment by ekutner** [comment]
It is extremely unlikely that it's related to the release as the only differences between 1.1.11 and 1.1.12 are related to translations. Feel free to upgrade back to 1.1.12 and following the bug submission instructions if you still have an issue. For now I'll be closing this one.
