### ISSUE TITLE
'Milk Container Removed?' blocking remote operation

### ISSUE THREAD

**Issue by ChadH360** [ekutner/home-connect-hass#457]
## Describe the bug

Occasionally, when I remotely turn off my Coffee Machine, it is displayed with 'Milk Container Removed?' with the options of abort or confirm. I use an external fridge for my milk, so never need to disconnect the milk container.
When this happens, it seems that any remote commands are no longer functional - the only solution seems to be to press one of the buttons physically on the machine.
I am hoping it might eventually time out, but even after an hour, it is still displayed.
Is there any way of overriding or bypassing this message?

## Version of the custom_component

1.1.12

## Configuration

Standard configuration with one coffee maker - no other devices

## Debug log

Not included as I suspect it is irrelevant.

**Comment by ekutner** [comment]
Where do you see this message, on the machine itself?
Anyway, I don't think there is anything that can be done about it. The integration just shows the controls that are made available by the API. If you don't see any switch that would control this message then it can't be controlled by the integration. You may want to look in the appliance's settings to see if there is anything there that would control displaying this reminder.

**Comment by ChadH360** [comment]
Yes, on the machine itself.
It was there for over two hours (my auto shutoff is set to two hours), so I don't think it was going to time out.
I discovered that if I use the Alexa skill to turn it off, the same message will flash up briefly, but it will carry on with the shutdown as normal. I don't know whether their Alexa Skill uses the same API, but it makes me think their must be some variable that allows messages to be bypassed (I believe they also have a method of disabling the rinse on startup, although never managed to get that to work with my model)
As a workaround, my solution is to use the HA Alexa Media Player integration to just tell Alexa to turn the coffee machine off. It works a treat!

This is such a great integration. I'd been using the HA built in one for years, and recently discovered just how much better this one is!
Thanks for your work :)

**Comment by ekutner** [comment]
Thanks, I'm happy to hear you like it.
Unfortunately I have no idea what the HA Alexa integration does differently as its code isn't open. It's closed code that runs on HC servers. The only things I have to go with is the API documentation and that doesn't have any special options for shutting down an appliance.  That said, since you've found a workaround I'm going to close this issue. Feel free to open a new one of more information about it becomes available.
