### ISSUE TITLE
Siemens Dishwasher Energy and Water entities show as %

### ISSUE THREAD

**Issue by chasp152** [ekutner/home-connect-hass#458]
## Describe the bug
I successfully added my dishwasher but some entities are showing as % when I was expected energy or volume: 
* Energy (I expected kWh): 
<img width="707" alt="image" src="https://github.com/user-attachments/assets/4283b431-dd6a-41c9-99c3-554eed7c3dba" />
* Water (I expected L or m3): 
<img width="690" alt="image" src="https://github.com/user-attachments/assets/02844e44-0d5a-49a0-8c6d-3c7c5fbe5c10" />

## Version of the custom_component: 
1.1.12

## Configuration
Using default

## Debug log
[home-assistant_home_connect_alt_2024-12-16T11-03-31.171Z.log](https://github.com/user-attachments/files/18148946/home-assistant_home_connect_alt_2024-12-16T11-03-31.171Z.log)

**Comment by ekutner** [comment]
This is how it's being reported by the API so that's how it's going to stay. It has been discussed multiple time and you can join the discussion in #420
