### ISSUE TITLE
Add service for API call programs​/active​/options​/{optionkey}

### ISSUE THREAD

**Issue by crhammock** [ekutner/home-connect-hass#46]
Version of the custom_component 0.4.9

Would it be possible to add a service for the API call below, primarily for use with an oven

​/homeappliances​/{haId}​/programs​/active​/options​/{optionkey}

The existing start program service seems to use the ​/homeappliances​/{haId}​/programs​/active which works fine if the oven is off.  However in the case of an oven, any automation would probably require the oven pre heated first before starting the actual cooking.  In my mind this would start with the /homeappliances​/{haId}​/programs​/active "service" to pre heat the oven followed by a change to the active timer and or temperature once the oven is ready which would require the ​/homeappliances​/{haId}​/programs​/active​/options​/{optionkey} service.

**Comment by ekutner** [comment]
This was added to beta version 0.7.0-b3

**Comment by crhammock** [comment]
Thanks for the quick response.  I have upgrade to the latest beta and have access to the new "set program option".

I tried entering Cooking.Oven.Option.SetpointTemperature as the option key and 180 as the Option value and I get the below errors in the logs

```
2022-06-10 19:24:56 DEBUG (MainThread) [home_connect_async.appliance] Calling /api/homeappliances/NEFF-B58VT68H0B-68A40E30F7D3/programs/active/options/Cooking.Oven.Option.SetpointTemperature with:
{
  "data": {
    "key": "Cooking.Oven.Option.SetpointTemperature",
    "value": "180"
  }
}
2022-06-10 19:24:57 DEBUG (MainThread) [home_connect_async.api] HTTP put /api/homeappliances/NEFF-B58VT68H0B-68A40E30F7D3/programs/active/options/Cooking.Oven.Option.SetpointTemperature (code=409  count=13)
2022-06-10 19:24:57 DEBUG (MainThread) [home_connect_async.api] API call failed with code=409 error=SDK.Error.InvalidOptionValue
2022-06-10 19:24:57 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Key Cooking.Oven.Option.SetpointTemperature has unexpected type or value 180
2022-06-10 19:24:57 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139808306451888] Error handling message: Key Cooking.Oven.Option.SetpointTemperature has unexpected type or value 180 (unknown_error)
```

I also tried entering BSH.Common.Option.Duration as the option key and 1500 as the Option value and I get the below errors in the logs

`2022-06-10 19:29:18 DEBUG (MainThread) [home_connect_async.appliance] Attempting to set unavailable option: BSH.Common.Option.Duration`

Seems like these are two different error which is strange,  I do know that unlike the /programs/active call the programs​/active​/options​/{optionkey} does require the "unit" type 

For example 

    - key: Cooking.Oven.Option.SetpointTemperature
      value: 180
      unit: °C

Not sure if that is what is going on here but it might be worth adding?  If you can expose the oauth tokens in the debug logs it would be easy for me to do some testing direct from curl and the CLI to provide some comparison

Thanks again

**Comment by ekutner** [comment]
The first error is because you tried to send what is expected to be a numeric value as a string. If you are using the developer tools in HA to send the call you must switch to YAML mode and make sure there are no single or double quotes around the value.

The second error is because you tried to set an option that can't be set, at least not at the state of the appliance when you tried to set it. To verify this I'm going to need a more complete log and also for you to press the "Home Connect Debug" button just before calling the service (and make sure the output is included in the log).

**Comment by crhammock** [comment]
@ekutner my apologies, I didn't test correctly.  I can confirm the temperature and duration is now working as expected once I started using the yaml option from the dev tools > services and removing the quotes that the UI mode seemed to introduce.

thanks for your efforts, I think this enhancement can be closed.

**Comment by ekutner** [comment]
Happy to hear that, enjoy.
