### ISSUE TITLE
Salt and Rinse Aid status not showing

### ISSUE THREAD

**Issue by g7ukk** [ekutner/home-connect-hass#465]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by g7ukk** [comment]
Is it possible for the dishwasher rinse aid and salt low status to show

**Comment by ekutner** [comment]
These are events. It's been discussed at least 10 times already, please use the search.

**Comment by g7ukk** [comment]
I did try the search, thanks

Regards
Greg Firth

On 29 Dec 2024, at 16:38, ekutner ***@***.***> wrote:

﻿

These are events. It's been discussed at least 10 times already, please use the search.

**Comment by ekutner** [comment]
https://github.com/search?q=repo%3Aekutner%2Fhome-connect-hass%20salt&type=issues
