### ISSUE TITLE
Device sometimes/often not updated

### ISSUE THREAD

**Issue by emufan** [ekutner/home-connect-hass#50]
## Version of the custom_component
v0.5.0-b2

## Configuration

```
home_connect_alt:
  client_id: !secret home_connect_alt_client_id
  client_secret: !secret home_connect_alt_client_secret
  language: de-DE
  sensor_value_translation: local
```

Add your logs here.

```
2022-06-10 18:15:49 ERROR (MainThread) [aiohttp_sse_client.client] fetch https://api.home-connect.com/api/homeappliances/events failed: 401
2022-06-11 15:02:11 ERROR (MainThread) [aiohttp_sse_client.client] fetch https://api.home-connect.com/api/homeappliances/events failed: 429
```

## Describe the bug
The above logs are there, but not correlated to the missing status of my appliances, here example dishwasher.

In 2 of 3 times, if I start and run a program, the integration does not show anything about it. Only if I restart the integration, the new/running status is correct again.

![image](https://user-images.githubusercontent.com/22775515/173193210-66b985c0-785d-4b88-a40c-9abb48886947.png)

Here the morning, everything was o.k. Status "Run" in cyan and every other entity was right and got updated during runtime. Then the noon. I switched on the dishwasher at 12:57. Correct. But started 2-3 seconds afterwards. But the entity didn't go to "Run", nor did this change until now (in the meantime finished and off) and nor any other entity got updated.

It was finished at 15:14 (HC App) so this isn't correlated to the timestamp from the error log above either.

## Debug log

Enabled now, but have to restart and wait until the next behavior like this one.

Searched already in the closed issues, but didn't find a 1:1 one. Known behavior? With the core integration, I never had this before. This was 100% stable in this regards.

**Comment by ekutner** [comment]
The integration is relying on events coming from the server to update the its state, without the log I can't know which events were received.
Unless you have a good reason to do so, don't use a beta release, and if you do then please update to b4 which has some important fixes.

**Comment by emufan** [comment]
As said, I have now enabled the log and will wait.

Regarding beta. I have not decided to install special update. v0.5.0-b2 has been offered from HACS as standard non-beta-release. So most probably you have forgotten to flag it correctly. 

![image](https://user-images.githubusercontent.com/22775515/173221207-f8abfabd-a14a-4b8d-8ce0-4d66ecc0303d.png)

![image](https://user-images.githubusercontent.com/22775515/173221223-2a3637fc-1ad9-4afb-92b3-d001dfbbb0ed.png)

**Comment by ekutner** [comment]
You're right, I did forget to mark it, but still, it is unstable and it's better not to use it.

**Comment by emufan** [comment]
Already went back to 0.4.10. Thanks for the advice.

Since yesterday I have a blocked application. Can this be related to the betas? With beta it showed 8 hours, 7:59, 7:58 blocking countdown. With 0.4.10 it is now showing only LOADING. But I assume, that I have still to wait for 7 hours.

And no, not too many devices, re-boots, etc. Yesterday, there was only one device switched on. Suspecious.

**Comment by ekutner** [comment]
There is nothing there that would cause more calls than before. With a full debug log I can try to check why you were blocked. Just to confirm, you have a dedicated HC app for this integration, not one shared with the built-in one?

**Comment by ekutner** [comment]
@srslykev it's the same answer as before, I need a full debug log of at least 24h before the block, to try to see if there was an excessive number of API calls that could have been avoided.

**Comment by srslykev** [comment]
Sorry for the late reply. I've attached the log file from restart ("LOADED") to API block.
[home_connect_alt_log.txt](https://github.com/ekutner/home-connect-hass/files/8990217/home_connect_alt_log.txt)
Thanks a lot for your work!

**Comment by ekutner** [comment]
So this is the second time in the last 30 min that I'm looking at a log that has multiple DISCONNECT/CONNECT events in a short period of time (the other was #60 ). This is clearly a bug in the HC and I opened an issue with them to report it. Note that from past experience it can take them weeks to respond.

**Comment by ekutner** [comment]
@srslykev it seems there is a new firmware update that solve this problem, see in #60
