### ISSUE TITLE
"soft" reloading of the integration (without polling HomeConnect server)

### ISSUE THREAD

**Issue by pswid** [ekutner/home-connect-hass#51]
I would like to work on translations, but for tests I need to do restarts. Unfortunately every restart generates a lot of queries to HomeConnect server, which very quickly results in a blockade for 24 hours.
Could you add e.g. a service that will perform such a "soft" restart, please?

**Comment by ekutner** [comment]
First, I'm not aware of any way to do that. Second, even if there was a way it wouldn't help because the translation is not handled by the integration but by HA itself.
