### ISSUE TITLE
bsh_common_status_operationstate not updating

### ISSUE THREAD

**Issue by wokkeltje13** [ekutner/home-connect-hass#52]
The plugin is working correctly and respond fast to changes on my dischwacher.

except bsh_common_status_operationstate does not receive the updates except when I click reload the add in. especially the status run, finished seems to work a lot better (strange) but this was not the case a couple of days ago. then every state change was direct.

I do not have the official plugin and a reload fixes the issue, so I don't think it is related to the number of requests. Door closed and so is sending the status directly, just not the operation state.

I use the operation state to count every time the dishwacher is starting.

**Comment by wokkeltje13** [comment]
[home-assistant .log](https://github.com/ekutner/home-connect-hass/files/8912163/home-assistant.log)
attached is the logfile with the moment I pressed reload

OperationState "run" does not come without reload anymore
state "finished" is arriving immediately when program is finished

**Comment by ekutner** [comment]
You can find the states in the HC documentation.

**Comment by alexdelprete** [comment]
> You can find the states in the HC documentation.

Ok, I'll look into that.

Regarding the issue of missing states etc., would that be fixed by b7?

**Comment by ekutner** [comment]
as i said, yes

**Comment by wokkeltje13** [comment]
I can confirm that the operation state is updating instantly. tnx for the quick fix

**Comment by ekutner** [comment]
Great, happy t hear that.
