### ISSUE TITLE
How to see events

### ISSUE THREAD

**Issue by X1pheR** [ekutner/home-connect-hass#53]
The documentation states that events are exposed as 'home_connect_alt_event' but I can't seem to find them in the logs or as event listener in the developer tools. How can I see the events so that I can build an automation? For starters to actually see what it contains. The Home Connect mobile app sends push messages like the door is open, dishwasher needs cleaning, etc. I'm hoping this is exposed as these events so I can build automations from them. An example would also be nice in the documentation. 😉 In stead of only asking I must say that I love the integration. Seeing what and how it exposes the entities. Much better than the native one in every aspect! 👌🏼

**Comment by ekutner** [comment]
Thank you.
To see the events you can use the events listener in developer tools. Note that most events are filtered out except for operation state changes, so you'll only see them when a program starts, finishes, etc. If you have a use case for other events let me know what it is.
