### ISSUE TITLE
Changing temperature on oven

### ISSUE THREAD

**Issue by Symbiot78** [ekutner/home-connect-hass#59]
Maybe I missed it.. but.. 

is there a way I can actually set the temp on my siemens oven?
I can turn it on.. I can choose a program.. but not set a specific temperature. 

it should be available through the API:

https://api-docs.home-connect.com/programs-and-options?#oven_setpoint-temperature-option

so if it's not part of the HC alt. integration - I'd like to suggest it :-)

I have dishes where I need to change temperatures during cooking.. that'd be wonderful if I could automate.

**Comment by ekutner** [comment]
The controls are automatically added based on what is supported by the API for the appliance. If you don't see a control for this then most likely it isn't supported but if you want to make sure then press the Home Connect Debug button in HA and upload the log here.

**Comment by Symbiot78** [comment]
here's the log:

https://pastebin.com/ww0qJ4FL

**Comment by ekutner** [comment]
Please activate debug mode (see README for instruction), then select a program. Verify that the Selected Program sensor shows the same program you selected. Now press the Debug button again and upload the log.

**Comment by Symbiot78** [comment]
Well obviously it works now - always the IT-way… doesn’t work until you ask for help then it’s like there’s never been an issue😅

**Comment by ekutner** [comment]
Okay, I'm not sure why it didn't work the first time but I suggest you keep the debug logging enabled for a while and reopen the issue if it happens again
