### ISSUE TITLE
unauthorized client

### ISSUE THREAD

**Issue by alessiovalvano** [ekutner/home-connect-hass#62]
Hello, i receive error:

{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiNmFkMThhYzAwYmMwYzEyMzg4YWQ3NDA1NDE4MWI1YzgiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL215LmhvbWUtYXNzaXN0YW50LmlvL3JlZGlyZWN0L29hdXRoIn0.ZiDlxa2a5lWG6R1Lef2BvwITFKPVv5xmofzVhPUSaIc"
}

can you help me?

**Comment by ensnared** [comment]
Same here. I did not create a separate application, figured I'd use the same one and just disabled the official integration in HA.

**Comment by maciekb** [comment]
You must enable and configure https://my.home-assistant.io/ functionality, or enter a different redirection URI which is correct for your HA configuration.

**Comment by alessiovalvano** [comment]
i set on the app of HomeConnect the redirect URI corrected with my DSN, but the verification link always have  https://my.home-assistant.io/, by the way it's configured on my installation, if i go to that address, i see my public dns.

**Comment by alessiovalvano** [comment]
great for you, mine still don't.
how can i delete some "cache" becasue i created a new application on home connect, but home assistant don't ask me again to insert client/secret

**Comment by alessiovalvano** [comment]
https://my.home-assistant.io/redirect/config_flow_start?domain=home_connect_alt)

i used this link, and follow the instruction and now it's working!
great thank you!

**Comment by julianjwong** [comment]
The trick that worked for me was to update the redirect URIs via the Home Connect website https://developer.home-connect.com/applications/ to include 3 of them.

https://my.home-assistant.io/redirect/oauth
http://192.168.0.230:8123/auth/external/callback
https://<yourduckdns>.duckdns.org/auth/external/callback

**Comment by bsmeding** [comment]
For me I also needed to add `https://my.home-assistant.io/redirect/config_flow_start?domain=home_connect_alt` as redirect URL otherwise it doesn't work
