### ISSUE TITLE
Cooking.Oven.Program.HeatingMode.PreHeating Not working

### ISSUE THREAD

**Issue by crhammock** [ekutner/home-connect-hass#64]
I am using 0.7.0-b10 of the integration

When I use the "Home Connect Alt: Start Program service" 

with the following data

```
data:
  device_id: dummyid
  program_key: Cooking.Oven.Program.HeatingMode.PreHeating
  options:
    - key: Cooking.Oven.Option.SetpointTemperature
      value: 200
    - key: BSH.Common.Option.Duration
      value: 6000
```

I get the below error message

```
2022-06-21 20:09:18 WARNING (MainThread) [home_connect_async.appliance] The selected program in not one of the available programs (not supported by the API)
2022-06-21 20:09:18 ERROR (MainThread) [homeassistant.components.script.oven_preheating] Oven PreHeating: Choose at step 1: choice 1: Error executing script. Error for call_service at pos 1: The specified program in not one of the available programs (not supported by the API)
2022-06-21 20:09:18 ERROR (MainThread) [homeassistant.components.script.oven_preheating] Oven PreHeating: Error executing script. Error for choose at pos 1: The specified program in not one of the available programs (not supported by the API)
2022-06-21 20:09:18 ERROR (MainThread) [homeassistant.components.script.oven_pizza2] Oven Pizza 2: Error executing script. Error for call_service at pos 1: The specified program in not one of the available programs (not supported by the API)
2022-06-21 20:09:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140161139232480] The specified program in not one of the available programs (not supported by the API)
Traceback (most recent call last):
  File "/config/custom_components/home_connect_alt/services.py", line 35, in async_start_program
    await appliance.async_start_program(program_key, options)
  File "/usr/local/lib/python3.9/site-packages/home_connect_async/appliance.py", line 320, in async_start_program
    raise HomeConnectError("The specified program in not one of the available programs (not supported by the API)")
home_connect_async.common.HomeConnectError: ('The specified program in not one of the available programs (not supported by the API)', None, None, None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 290, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 398, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 428, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 683, in _async_call_service_step
    await self._async_run_long_action(service_task)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 644, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 290, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 398, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 428, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 892, in _async_choose_step
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1025, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 644, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/home_connect_alt/services.py", line 37, in async_start_program
    raise HomeAssistantError(ex.error_description if ex.error_description else ex.msg)
homeassistant.exceptions.HomeAssistantError: The specified program in not one of the available programs (not supported by the API)
```

I have confirmed the function works via https://apiclient.home-connect.com.  I suspect maybe as your integration is only allowing cooking functions support by the device and maybe the preheating mode isn't reported as supported, not sure why, maybe it is a default function supported by all ovens or maybe there is an error with the code used to pull these modes?  Let me know if there is any further troubleshooting I can do to assist.

**Comment by ekutner** [comment]
The integration allows using only programs which are reported as available by the API. You can call the /available endpoint to see which programs are reported as available when you get this error and press the Home Connect Debug button to dump into the log the internal state of the integration and what it thinks is available. Those two lists should match.
Let me know what you find.

**Comment by crhammock** [comment]
I can confirm Cooking.Oven.Program.HeatingMode.PreHeating is not listed as an available program from my oven, however it clearly does work, I cant comment on why it isn't listed by the api it is one of the few modes in the documentation with significant explanation, it is also the first https://api-docs.home-connect.com/programs-and-options?#oven, I wonder if maybe it is a mode supported by all ovens and so isn't part of the support mode call or maybe because it is not strictly a heating mode (its a pre heating mode) maybe it isn't listed.  Either way would be good to include it if possible for completeness.

`  "appliances": {
    "NEFF-B58VT68H0B-68A40E30F7D3": {
      "name": "Oven",
      "brand": "Neff",
      "vib": "B58VT68H0B",
      "connected": true,
      "type": "Oven",
      "enumber": "B58VT68H0B/63",
      "haId": "NEFF-B58VT68H0B-68A40E30F7D3",
      "uri": "/api/homeappliances/NEFF-B58VT68H0B-68A40E30F7D3",
      "available_programs": {
        "Cooking.Oven.Program.HeatingMode.PizzaSetting": {
          "key": "Cooking.Oven.Program.HeatingMode.PizzaSetting",
          "name": "Circotherm intensive",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.SlowCook": {
          "key": "Cooking.Oven.Program.HeatingMode.SlowCook",
          "name": "Slow cook",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.TopBottomHeatingEco": {
          "key": "Cooking.Oven.Program.HeatingMode.TopBottomHeatingEco",
          "name": "Top | bottom heating eco",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.HotAirEco": {
          "key": "Cooking.Oven.Program.HeatingMode.HotAirEco",
          "name": "CircoTherm eco",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.HotAir": {
          "key": "Cooking.Oven.Program.HeatingMode.HotAir",
          "name": "CircoTherm",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.TopBottomHeating": {
          "key": "Cooking.Oven.Program.HeatingMode.TopBottomHeating",
          "name": "Top/bottom heating",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.HotAirGrilling": {
          "key": "Cooking.Oven.Program.HeatingMode.HotAirGrilling",
          "name": "Circo-roasting",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.BottomHeating": {
          "key": "Cooking.Oven.Program.HeatingMode.BottomHeating",
          "name": "Bottom heating",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.Defrost": {
          "key": "Cooking.Oven.Program.HeatingMode.Defrost",
          "name": "Defrost setting",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.PreheatOvenware": {
          "key": "Cooking.Oven.Program.HeatingMode.PreheatOvenware",
          "name": "Plate warming",
          "options": null,
          "execution": "selectandstart",
          "active": false
        },
        "Cooking.Oven.Program.HeatingMode.KeepWarm": {
          "key": "Cooking.Oven.Program.HeatingMode.KeepWarm",
          "name": "Keep warm",
          "options": null,
          "execution": "selectandstart",
          "active": false
        }
      },
      "active_program": null,
      "selected_program": null,
      "status": {
        "BSH.Common.Status.DoorState": {
          "key": "BSH.Common.Status.DoorState",
          "value": "BSH.Common.EnumType.DoorState.Closed",
          "name": "Door",
          "displayvalue": "Closed"
        },
        "BSH.Common.Status.LocalControlActive": {
          "key": "BSH.Common.Status.LocalControlActive",
          "value": false,
          "name": "Local operation active",
          "displayvalue": null
        },
        "BSH.Common.Status.RemoteControlStartAllowed": {
          "key": "BSH.Common.Status.RemoteControlStartAllowed",
          "value": true,
          "name": "Remote Start",
          "displayvalue": null
        },
        "BSH.Common.Status.RemoteControlActive": {
          "key": "BSH.Common.Status.RemoteControlActive",
          "value": true,
          "name": "Remote Control",
          "displayvalue": null
        },
        "BSH.Common.Status.OperationState": {
          "key": "BSH.Common.Status.OperationState",
          "value": "BSH.Common.EnumType.OperationState.Inactive",
          "name": "Operation state",
          "displayvalue": "Inactive"
        },
        "Cooking.Oven.Status.CurrentCavityTemperature": {
          "key": "Cooking.Oven.Status.CurrentCavityTemperature",
          "value": 59,
          "name": null,
          "displayvalue": null
        }
      },
      "settings": {
        "BSH.Common.Setting.ChildLock": {
          "key": "BSH.Common.Setting.ChildLock",
          "value": false,
          "type": "Boolean",
          "name": "Childproof lock",
          "unit": null,
          "displayvalue": null,
          "min": null,
          "max": null,
          "stepsize": null,
          "allowedvalues": null,
          "execution": null,
          "liveupdate": null,
          "access": "readWrite"
        },
        "BSH.Common.Setting.PowerState": {
          "key": "BSH.Common.Setting.PowerState",
          "value": "BSH.Common.EnumType.PowerState.Standby",
          "type": "BSH.Common.EnumType.PowerState",
          "name": "Power status",
          "unit": null,
          "displayvalue": "Standby",
          "min": null,
          "max": null,
          "stepsize": null,
          "allowedvalues": [
            "BSH.Common.EnumType.PowerState.MainsOff",
            "BSH.Common.EnumType.PowerState.Off",
            "BSH.Common.EnumType.PowerState.On",
            "BSH.Common.EnumType.PowerState.Standby"
          ],
          "execution": null,
          "liveupdate": null,
          "access": "readWrite"
        },
        "BSH.Common.Setting.AlarmClock": {
          "key": "BSH.Common.Setting.AlarmClock",
          "value": 0,
          "type": "Int",
          "name": "Alarm",
          "unit": "seconds",
          "displayvalue": null,
          "min": null,
          "max": null,
          "stepsize": null,
          "allowedvalues": null,
          "execution": null,
          "liveupdate": null,
          "access": "readWrite"
        }
      },
      "commands": {},
      "startonly_options": null,
      "startonly_program": null
    }
  }
}`

**Comment by ekutner** [comment]
There are many types and models of appliances and the integration doesn't know anything about them. Everything it knows comes from interrogating the API and I don't want to make any assumptions about what is and isn't supported. Anything which is not listed by the official API will not be directly supported by the integration. That said, I will consider removing the validation, specifically for service calls, and let the caller deal with the API error in case of using an invalid program or option.

I'll keep this issue open while thinking about it.

**Comment by crhammock** [comment]
completely understand, would it help if I reach out to Home Connect support and see if I can get a more official answer why the pre heating mode isn't listed by the API when querying the device?

**Comment by crhammock** [comment]
@ekutner I have just downloaded the 0.5.2 version and called with the following service 

service: home_connect_alt.start_program
data:
  validate: false
  device_id: 9fd48f816b36df242875253259896d58
  program_key: Cooking.Oven.Program.HeatingMode.PreHeating
  options:
    - key: Cooking.Oven.Option.SetpointTemperature
      value: 200
    - key: BSH.Common.Option.Duration
      value: 900

Works as expected thanks again for your efforts, I have asked the question of the homeconnect devs why this heating mode is not returned as available and am waiting on a response.

I am having some further issues with the set_program_option service not accepting temperature and duration updates, I thought I tested this and had it working but now I can't seem to get it to work.  Is it possible to include this validate parameter into the "set active option" service or would you rather I raise a new issues with detail and debugs?

**Comment by crhammock** [comment]
@ekutner 

I have raised with Home Connect Dev team on why the PreHeating option is not returned and their response is below, not sure if this changes anything on how you would approach its integration, it seems it is not an oven mode available on the oven, more a script that runs on the cloud API to select a supported mode to preheat.  For me the existing work around works fine and I would argue has value outside of this specific use case.

> Cooking.Oven.Program.HeatingMode.PreHeating is not returned by your oven because this is not a real program, but rather an API specific feature to allow running pre-heating on an oven. In reality if you start this “program” remotely an oven will run one of its programs (like top/bottom heating) with fast pre-heat option for some time to reach setpoint temperature.
> You may read about this here:
> https://api-docs.home-connect.com/programs-and-options?#oven
> 
> For some programs there’s fast pre-heat option that you may use. Please mind that if you’d like to set your own program parameters you need to first:
> 1.	GET https://apiclient.home-connect.com/#/programs/get_available_programs for a list of programs supported on the appliance.
> 2.	PUT /homeappliances/{haId}/programs/selected – select the program on the appliance.
> 3.	GET /homeappliances/{haId}/programs/selected/options – get a list of all options of the program.
> 4.	PUT /homeappliances/{haId}/programs/selected/options – set program options and their values.
>

**Comment by ekutner** [comment]
Interesting. and doesn't make sense to me, If the program works there is no reason it shouldn't be returned by the API. Anyway, it is what it is. If there's nothing else I'm going to close this issue.

**Comment by crhammock** [comment]
Yes doesn't make a whole lot of sense to me, I think maybe the available modes comes direct from the oven (via the cloud API) where as the preheating is more like a cloud API function.  Either way please feel free to close the issue.  Thanks again for your efforts
