### ISSUE TITLE
Bug when Pausing my washing machine

### ISSUE THREAD

**Issue by osulivanDE** [ekutner/home-connect-hass#65]
When pausing the program of my dishwasher and resuming the program i cannot pause the program again. 

The Button/Icon will stay at the "resume" position until i reload the integration. Then i can pause and resume one more time.

This is the position where the integration got stuck after pausing and resuming the program:
<img width="392" alt="Bildschirmfoto 2022-06-23 um 18 55 13" src="https://user-images.githubusercontent.com/44095221/175353499-609c49cd-a471-4dff-a913-187ddef181b5.png">

This is the position where the integration stands afer reloading the integration after it got stuck. With this i can pause the program again (one more time). See, the Icon changed:
<img width="379" alt="Bildschirmfoto 2022-06-23 um 18 59 01" src="https://user-images.githubusercontent.com/44095221/175354120-6ad92657-3ad8-4d76-ae74-8afefd3f7003.png">

Can i help with further logs or descriptions?

PS: It seems the icon changes based on the possible options. Is it also possible to change the Text from "Start" to "Pause" when the corresponding option is possible?

home_connect_alt:
  client_id: ID
  client_secret: SECRET
  language: de
  sensor_value_translation: local

Newest Version

**Comment by ekutner** [comment]
It should already change from Start to Pause to Resume, as appropriate. However, there is something weird about those names. Based on you configuration they should have been something like "Bosch Dishwasher Start". Did you change the name in HA configuration? If you did then the name you configured overrides the name provided by the integration so you won't see it change.

**Comment by ekutner** [comment]
Right, I'm going to need a debug log to figure out why that happened (see the README for instructions how to enable it).
After you enable debug logging and restart HA, try to reproduce the problematic flow but press the Home Connect Debug button after every step and upload the log file.
It will be helpful if you specify the exact time of every step, so I don't have to spend a lot of time digging through the log.

**Comment by osulivanDE** [comment]
Sorry for the delay. I could reproduce the problem and created a log. Is there a way to sent this log to you directly?
There seem to be serialnumbers of my devices in the logfiles.

**Comment by osulivanDE** [comment]
Thanks for you patience. I hope i did it all right with the logs and debug button. 
I could reproduce the problem again.

[HCA2.txt](https://github.com/ekutner/home-connect-hass/files/9032988/HCA2.txt)
[HCA1.txt](https://github.com/ekutner/home-connect-hass/files/9032989/HCA1.txt)

**Comment by ekutner** [comment]
See the READ for instructions how to enable debug logging. Also, please add the following line to the home_connect_alt config section in your configuration.yaml file:
log_mode: 7

Then upload the whole debug file and see my note about specifying the time of each step (when you started the program, paused, it, resumed it, etc.).
