### ISSUE TITLE
Questions, comments, discussions - where?

### ISSUE THREAD

**Issue by von-Chaps** [ekutner/home-connect-hass#73]
I'm pretty new to this integration, but I think it's got a lot of great features and also some good potential based on the way it has been built. However, I'm struggling to understand some aspects of how it works and why it's the way it is. It seems like a big hassle for the developer if I open a new issue with every question, comment or suggestion I might have. It fills the open issue list with noise and to be sure will start to irritate people.

Personally, I could go and read the code and probably, eventually figure out the "how?" of my questions, but that probably would not address the "why?" - have my questions been asked before? is there a good reason it's the way it is? is it historical baggage? is a change in the pipeline... etc. I can't be the only one.

So, this is the context of my asking - _is there somewhere we can discuss this integration_? I thought of the Home Assistant forum, but it's quite noisy and hard to find what you're looking for. HA has a discord server but, right now I don't use discord (although of course I could). Perhaps, if there is nothing else, this issue could remain and be used as a discussion jumping off point?

Mainly, this is up to you @ekutner - or would you prefer to just not have this kind of thing? I've been on the receiving end of issue tracking systems and it can be demoralising if all you ever see is people asking about stuff they think doesn't work.

I'll leave it at that for now and see what people think although, as I say, I have a bunch of questions lined up....

TIA

**Comment by ekutner** [comment]
I don't have a problem with such discussions but prefer to keep them in github.
I created a discussion for general topics so feel free to use it.
