### ISSUE TITLE
Bosch WTWH7660GB Dryer - advanced options not showing

### ISSUE THREAD

**Issue by cromelex** [ekutner/home-connect-hass#91]
Using V0.5.4

I have a Bosch WTWH7660GB Dryer, and Home Connect Alt is not showing me the extra "options" that are available in Home Connect

There are 2 sensors that relate to specific options, which do not show under controls, as I would expect (here everything was greyed out as the machine was off at the time, but they don't show in any situation).

![image](https://user-images.githubusercontent.com/96779452/183651537-53ef48b4-3334-4ae7-9b85-da477ef707da.png)

- sensor.bosch_wtwh7660gb_68a40e768757_laundrycare_dryer_option_dryingtargetadjustment
- binary_sensor.bosch_wtwh7660gb_68a40e768757_laundrycare_dryer_option_gentle

In the Home Connect app, they show under "Options"
![image](https://user-images.githubusercontent.com/96779452/183651442-2e576c3b-eb9b-4f0e-a0fe-1fbf6ff04979.png)

I have a dishwasher and a washing machine where these type of options (I call them options as that's the "header" in the Home Connect app) show as both a sensor/binary sensor but also a switch that you can control. They work absolutely fine for both Dishwasher and Washing Machine, which is I am opening this as an issue for the Dryer.

Not sure if this is something that could be fixed - It would be really helpful as for a lot of clothes I need the "gentle" option to be enabled and I can't program shortcuts without it.

**Comment by ekutner** [comment]
The integration automatically creates HA entities for every option that is made available by the API. If it's not there it's probably not available through the API. The HC mobile app is using an internal API which allows it to communicate directly with appliances over the local wifi and has access to programs and options that are not available through the public API.

**Comment by cromelex** [comment]
Understood. Thanks for the clarification, I wasn't aware of the internal vs public API.

Are you aware of any contact point/email address at Bosch/Home Connect that I could email requesting this? I know it's unrealistic to expect anything, but minimum I can do is email them as a client and request it.

**Comment by ekutner** [comment]
The only way I found is using the support form on their website (https://developer.home-connect.com/support/contact). When they respond, which isn't always, it can take a few weeks.
