### ISSUE TITLE
Siemens eq.9 s700 - statistics and missing options

### ISSUE THREAD

**Issue by ChristophCaina** [ekutner/home-connect-hass#92]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The Home Connect App provides a couple of features for the Siemens eq.9 Coffemachine.
For example, it provides the following statistics:

the amount of cups for each drink (espesso, coffee, cappuchino, etc.)
the amount of hot water 
how many cups you need to do until you need to clean the device, or descale the machine.

You can also switch the Cup-heating on or off - or select the bean tank (left / right)

The app also provides other features, such as the Serial number of the device, the Version (Firmware?)
And to switch the child protection on / off

I would really like to have these options available in HomeAssistant - if possible;
And I would like to help in getting them into the integration (just need to know how I can contribute)

**Describe alternatives you've considered**

**Additional context**

**Comment by ekutner** [comment]
The HC mobile app is using an internal protocol/API which is not available to external developers and has more information and control than what is available in the pubic API which is available to external developers. The mobile app is also able to communicate directly with appliances when connected to the same wifi network, this too is not available to external developers.
The integration automatically generates HA entities for every property exposed by the API, if it's not in HA then it's not made available by the API and there is nothing to do about it other than ask HC to add support for it.

**Comment by ChristophCaina** [comment]
thanks for the reply and information 👍 
That's sad ...
But if there's a way to communicate directly with the device over the network - it could be an idea for another kind of integration (local instead of cloud ?)

maybe I need to dig a bit deeper into this... :)

**Comment by ekutner** [comment]
There is definitely a way, it's just not documented, you can see some work being done on this here: https://github.com/osresearch/hcpy/ but I don't think it's mature enough to base an integration on it and I certainly don't have the time or motivation to develop it further.
